---
title: "6mg_outliers"
author: "Yi"
date: "3/31/2020"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r include=FALSE}
library(haven)
library(tidyverse)
```

```{r}
data <- read_sav("/Users/zhan039/Desktop/USC_HEAL/P4/03242020/6mg_with scording added_3.23.2020.sav")
```

```{r}
Range <- function(varvec){
  upper <- mean(varvec, na.rm = T) + 2 * sd(varvec, na.rm = T)
  lower <- mean(varvec, na.rm = T) - 2 * sd(varvec, na.rm = T)
  range <- paste("(", round(lower, 2), ",", round(upper, 2), ")")
  return(range)
}

Outliers <- function(varvec){
  upper <- mean(varvec, na.rm = T) + 2 * sd(varvec, na.rm = T)
  lower <- mean(varvec, na.rm = T) - 2 * sd(varvec, na.rm = T)
  
  ind <- (varvec > upper) | (varvec < lower) | is.na(varvec)
  return(ind)
}

Table.Print <- function(table, title) {
  if (nrow(table) > 0) {
    knitr::kable(table, caption = title)
  }
}
```

### PANAS
```{r}
# PANAS
PANAS <- select(data, redcap_id, PANAS_PreE_PA, PANAS_PreE_NA, PANAS_PostE_PA, PANAS_PostE_NA, PANAS_PostR_PA, PANAS_PostR_NA)

PANAS_range <- cbind(apply(PANAS[, -1], 2, Range))
colnames(PANAS_range) <- "(Mean - 2SD, Mean + 2SD)"
knitr::kable(PANAS_range, caption = "Ranges to define outliers for PANAS variables")

outliers.PANAS <- apply(PANAS[, -1], 2, Outliers)
num.outliers.PANAS <- apply(outliers.PANAS, 2, sum)
knitr::kable(num.outliers.PANAS, caption = "Number of Ouliers in PANAS variables", col.names = "# of outliers")

# PANAS PreE PA
Table.Print(PANAS[Outliers(PANAS$PANAS_PreE_PA), c("redcap_id", "PANAS_PreE_PA")], "PANAS_PreE_PA")

# PANAS PreE NA
Table.Print(PANAS[Outliers(PANAS$PANAS_PreE_NA), c("redcap_id", "PANAS_PreE_NA")], "PANAS_PreE_NA")

# PANAS PostE PA
Table.Print(PANAS[Outliers(PANAS$PANAS_PostE_PA), c("redcap_id", "PANAS_PostE_PA")], "PANAS_PostE_PA")

# PANAS PostE NA
Table.Print(PANAS[Outliers(PANAS$PANAS_PostE_NA), c("redcap_id", "PANAS_PostE_NA")], "PANAS_PostE_NA")

# PANAS PostR PA
Table.Print(PANAS[Outliers(PANAS$PANAS_PostR_PA), c("redcap_id", "PANAS_PostR_PA")], "PANAS_PostR_PA")

# PANAS PostR NA
Table.Print(PANAS[Outliers(PANAS$PANAS_PostR_NA), c("redcap_id", "PANAS_PostR_NA")], "PANAS_PostR_NA")
```

### MNWS
```{r}
MNWS <- select(data, redcap_id, MNWS_PreE_Mean, MNWS_PostE_Mean, MNWS_PostR_Mean)

MNWS_range <- cbind(apply(MNWS[, -1], 2, Range))
colnames(MNWS_range) <- "(Mean - 2SD, Mean + 2SD)"
knitr::kable(MNWS_range, caption = "Ranges to define outliers for MNWS variables")


outliers.MNWS <- apply(MNWS[, -1], 2, Outliers)
num.outliers.MNWS <- apply(outliers.MNWS, 2, sum)
knitr::kable(num.outliers.MNWS, caption = "Number of Ouliers in MNWS variables", col.names = "# of outliers")

# MNWS_PreE_Mean
Table.Print(MNWS[Outliers(MNWS$MNWS_PreE_Mean), c("redcap_id", "MNWS_PreE_Mean")], "MNWS_PreE_Mean")

# MNWS_PostE_Mean
Table.Print(MNWS[Outliers(MNWS$MNWS_PostE_Mean), c("redcap_id", "MNWS_PostE_Mean")], "MNWS_PostE_Mean")

# MNWS_PostR_Mean
Table.Print(MNWS[Outliers(MNWS$MNWS_PostR_Mean), c("redcap_id", "MNWS_PostR_Mean")], "MNWS_PostR_Mean")
```

### QSU
```{r}
QSU <- select(data, redcap_id, QSU_PreE_Mean, QSU_PostE_Mean, QSU_PostR_Mean)

QSU_range <- cbind(apply(QSU[, -1], 2, Range))
colnames(QSU_range) <- "(Mean - 2SD, Mean + 2SD)"
knitr::kable(QSU_range, caption = "Ranges to define outliers for QSU variables")

outliers.QSU <- apply(QSU[, -1], 2, Outliers)
num.outliers.QSU <- apply(outliers.QSU, 2, sum)
knitr::kable(num.outliers.QSU, caption = "Number of Ouliers in QSU variables", col.names = "# of outliers")

# QSU_PreE_Mean
Table.Print(QSU[Outliers(QSU$QSU_PreE_Mean), c("redcap_id", "QSU_PreE_Mean")], "QSU_PreE_Mean")

# QSU_PostE_Mean
Table.Print(QSU[Outliers(QSU$QSU_PostE_Mean), c("redcap_id", "QSU_PostE_Mean")], "QSU_PostE_Mean")

# QSU_PostR_Mean
Table.Print(QSU[Outliers(QSU$QSU_PostR_Mean), c("redcap_id", "QSU_PostR_Mean")], "QSU_PostR_Mean")
```

### SHAPS
```{r}
SHAPS <- select(data, redcap_id, SHAPS_PreE_Sum, SHAPS_PostE_Sum, SHAPS_PreE_Mean, SHAPS_PostE_Mean)

SHAPS_range <- cbind(apply(SHAPS[, -1], 2, Range))
colnames(SHAPS_range) <- "(Mean - 2SD, Mean + 2SD)"
knitr::kable(SHAPS_range, caption = "Ranges to define outliers for SHAPS variables")

outliers.SHAPS <- apply(SHAPS[, -1], 2, Outliers)
num.outliers.SHAPS <- apply(outliers.SHAPS, 2, sum)
knitr::kable(num.outliers.SHAPS, caption = "Number of Ouliers in SHAPS variables", col.names = "# of outliers")

# SHAPS_PreE_Sum
Table.Print(SHAPS[Outliers(SHAPS$SHAPS_PreE_Sum), c("redcap_id", "SHAPS_PreE_Sum")], "SHAPS_PreE_Sum")

# SHAPS_PostE_Sum
Table.Print(SHAPS[Outliers(SHAPS$SHAPS_PostE_Sum), c("redcap_id", "SHAPS_PostE_Sum")], "SHAPS_PostE_Sum")

# SHAPS_PreE_Mean
Table.Print(SHAPS[Outliers(SHAPS$SHAPS_PreE_Mean), c("redcap_id", "SHAPS_PreE_Mean")], "SHAPS_PreE_Mean")

# SHAPS_PostE_Mean
Table.Print(SHAPS[Outliers(SHAPS$SHAPS_PostE_Mean), c("redcap_id", "SHAPS_PostE_Mean")], "SHAPS_PostE_Mean")
```

### FRS
```{r}
FRS_cost <- select(data, redcap_id, FRS_cost)

FRS_cost_range <- cbind(apply(FRS_cost[, -1], 2, Range))
colnames(FRS_cost_range) <- "(Mean - 2SD, Mean + 2SD)"
knitr::kable(FRS_cost_range, caption = "Ranges to define outliers for FRS_cost")

outliers.FRS.cost <- apply(FRS_cost[, -1], 2, Outliers)
num.outliers.FRS.cost <- apply(outliers.FRS.cost, 2, sum)
knitr::kable(num.outliers.FRS.cost, caption = "Number of Ouliers in FRS_cost", col.names = "# of outliers")

Table.Print(FRS_cost[Outliers(FRS_cost$FRS_cost), c("redcap_id", "FRS_cost")], "FRS_cost")
```

### CIS
```{r}
CIS <- select(data, redcap_id, PreE_CIS_Mean, PostE_CIS_Mean)

CIS_range <- cbind(apply(CIS[, -1], 2, Range))
colnames(CIS_range) <- "(Mean - 2SD, Mean + 2SD)"
knitr::kable(CIS_range, caption = "Ranges to define outliers for CIS variables")

outliers.CIS <- apply(CIS[, -1], 2, Outliers)
num.outliers.CIS <- apply(outliers.CIS, 2, sum)
knitr::kable(num.outliers.CIS, caption = "Number of Ouliers in CIS variables", col.names = "# of outliers")

# CIS_Mean
#Table.Print(CIS[Outliers(CIS$CIS_Mean), c("redcap_id", "CIS_Mean")], "CIS_Mean")

# PreE_CIS_Mean
Table.Print(CIS[Outliers(CIS$PreE_CIS_Mean), c("redcap_id", "PreE_CIS_Mean")], "PreE_CIS_Mean")

# PostE_CIS_Mean
Table.Print(CIS[Outliers(CIS$PostE_CIS_Mean), c("redcap_id", "PostE_CIS_Mean")], "PostE_CIS_Mean")
```

### CRS
```{r results = "asis"}
CRS <- select(data, redcap_id, starts_with("postec_crs"))

CRS_range <- cbind(apply(CRS[, -1], 2, Range))
colnames(CRS_range) <- "(Mean - 2SD, Mean + 2SD)"
knitr::kable(CRS_range, caption = "Ranges to define outliers for CRS variables")

outliers.CRS <- apply(CRS[, -1], 2, Outliers)
num.outliers.CRS <- apply(outliers.CRS, 2, sum)
knitr::kable(num.outliers.CRS, caption = "Number of Ouliers in CRS variables", col.names = "# of outliers")

for (i in c(2 : length(colnames(CRS)))) {
  
  col <- colnames(CRS)[i]
  table <- CRS[Outliers(as.vector(as.matrix(CRS[, col]))), c("redcap_id", col)]
  print(knitr::kable(table, caption = col))

}
```

