---
title: "EVOC_Methods_Paper"
author: "Yi"
date: "8/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
data.origin <- read.csv("/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/Final_Data/EVOC_pilot1_08072020.csv", na.strings = "")

data <- data.origin
```

```{r}
FreqPerc <- function(varname){
  freq <- table(varname, data$project_type, useNA = "always")
  perct <- round(prop.table(table(varname, data$project_type, useNA = "always"), margin = 2) * 100, 1)
  nperct <- paste(freq, " ", "(", perct, "%", ")", sep = "")
  
  nperct <- as.data.frame(matrix(nperct, ncol = 6))
  
  colnames(nperct) <- c(colnames(freq)[1:length(colnames(freq)) - 1], "Missing")
  rownames(nperct) <- c(rownames(freq)[1:length(rownames(freq)) - 1], "Missing")

  return(nperct)
}


FreqPerc.Sub <- function(varname, subset){
  freq <- table(subset[, varname], subset[, "project_type"], useNA = "always")
  perct <- round(prop.table(freq, margin = 2) * 100, 1)
  nperct <- paste(freq, " ", "(", perct, "%", ")", sep = "")
  
  nperct <- as.data.frame(matrix(nperct, ncol = 6))
  
  colnames(nperct) <- c(colnames(freq)[1:length(colnames(freq)) - 1], "Missing")
  rownames(nperct) <- c(rownames(freq)[1:length(rownames(freq)) - 1], "Missing")

  return(nperct)  
}

MeanSD <- function(varname, subset){
  m <- round(tapply(subset[, varname], subset[, "project_type"], mean, na.rm = T), 1)
  sd <- round(tapply(subset[, varname], subset[, "project_type"], sd, na.rm = T), 1)
  m.sd <- paste(m, " ", "(", sd, ")", sep = "")
  
  m.sd <- as.data.frame(matrix(m.sd, ncol = 5))
  colnames(m.sd) <- rownames(m)
  rownames(m.sd) <- varname
  
  return(m.sd)
}

```


```{r Demographics prepare variables}
# gender
table(data$gender, useNA = "always")

data <- mutate(data, gender_3c = ifelse(gender == 1, 1, ifelse(gender == 2, 2, 3)))
table(data$gender_3c, useNA = "always")

# eth
table(data$eth, useNA = "always")

# race
apply(data[, startsWith(colnames(data), "race")], 2, table, useNA = "always")

data$sum.race <- rowSums(data[, startsWith(colnames(data), "race")], na.rm = T)

data[data$sum.race > 1, c("sum.race", colnames(data)[startsWith(colnames(data), "race")])]
table(data$sum.race, useNA = "always")

data <- mutate(data, race_new = ifelse(sum.race > 1 | race___6 %in% 1, 5, 
                                       ifelse(race___1 %in% 1, 1, 
                                              ifelse(race___2 %in% 1, 2, 
                                                     ifelse(race___3 %in% 1, 3,
                                                            ifelse(race___4 %in% 1, 6,
                                                                   ifelse(race___5 %in% 1, 4,
                                                                                 ifelse(race___7 %in% 1, 6, NA))))))))

apply(data[, startsWith(colnames(data), "race")], 2, table, useNA = "always")
apply(data[data$sum.race == 1, startsWith(colnames(data), "race")], 2, table, useNA = "always")
apply(data[data$sum.race > 1, startsWith(colnames(data), "race")], 2, table, useNA = "always")
nrow(data[data$sum.race > 1, ])

22 + 115
table(data$race_new, useNA = "always")

# College Degree
table(data$degree_program, useNA = "always") # no "Don't Know"
data <- mutate(data, college_degree = ifelse(degree_program > 5, 1, 0))
table(data$college_degree, useNA = "always")

# Highest Level of Education
data <- mutate(data, highest_edu = ifelse(degree_program < 6, degree_program,
                                          ifelse(degree_program > 7, degree_program - 1,
                                                 ifelse(degree_program %in% 6 | degree_program %in% 7, 6, NA))))
table(data$highest_edu, useNA = "always")

# currently enrolled in a degree program
table(data$current_degree_program, useNA = "always")

# own or rent home
table(data$own_rent, useNA = "always")

# current financial situation
table(data$overall_income, useNA = "always")

# childhood financial situation
table(data$family_income, useNA = "always")

# number of attention checks failed
table(data$sum_att_failure_3item, useNA = "always")
```

```{r Demographics Analysis}
varlist <- c("gender_3c", "eth", "race_new", "college_degree", "highest_edu", "current_degree_program", "own_rent", "overall_income", "family_income", "sum_att_failure_3item")

Demo <- data.frame(matrix(nrow = 0, ncol = 6))
colnames(Demo) <- c(levels(data$project_type), "Missing")

for (i in 1:length(varlist)) {
  var <- data[, varlist[i]]
  tempt.tab <- FreqPerc(var)
  rownames(tempt.tab) <- paste(varlist[i], "=", rownames(tempt.tab), sep = "")
  Demo <- rbind(Demo, tempt.tab)
}

Demo
```

```{r save results of Demo}
# write.csv(Demo, file = "/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/Pilot1_Methods_Paper/Demo.csv")
```

```{r E-cig Use prepare variables E-cig use}
### E-cigarette use
## check missing
ever.use.all <- colnames(data)[startsWith(colnames(data), "ever_")]
ever.use <- ever.use.all[1:6]  # remove "other"

last.30.all <- colnames(data)[startsWith(colnames(data), "last_30_ecig_")]
last.30 <- last.30.all[2:7]  # remove "last_30_ecig_yn" "last_30_ecig_other"

days.last.30.all <- colnames(data)[endsWith(colnames(data), "_30_days")]
days.last.30 <- days.last.30.all[1:6]

apply(data[, ever.use], 2, table, useNA = "always")
apply(data[, last.30], 2, table, useNA = "always")
apply(data[, days.last.30], 2, table, useNA = "always")
table(data$last_30_ecig_yn, useNA = "always")

table(data[data$ever_disp == 2, "last_30_ecig_dispose"], useNA = "always")
table(data[data$ever_pen == 2, "last_30_ecig_pen"], useNA = "always")
table(data[data$ever_mod == 2, "last_30_ecig_mod"], useNA = "always")
table(data[data$ever_box_mod == 2, "last_30_ecig_box_mod"], useNA = "always")
table(data[data$ever_juul == 2, "last_30_ecig_juul"], useNA = "always")
table(data[data$ever_pod == 2, "last_30_ecig_pod"], useNA = "always")

data[data$last_30_ecig_dispose %in% 1 & data$last_30_ecig_yn %in% 0, c("redcapid", "last_30_ecig_dispose", "last_30_ecig_yn", "disp_30_days")]  # remove redcapid 1015, 1078, 2042 for Disposable
data[data$last_30_ecig_dispose %in% 9 & data$last_30_ecig_yn %in% 0, c("redcapid", "last_30_ecig_dispose", "last_30_ecig_yn", "disp_30_days")]
data[data$last_30_ecig_dispose %in% 1 & data$disp_30_days %in% 1, c("redcapid", "last_30_ecig_dispose", "last_30_ecig_yn", "disp_30_days")]  # remove redcapid 1130, 6075, 2114, 2119 for Disposable
rm.dispose <- data[data$last_30_ecig_dispose %in% 1 & data$last_30_ecig_yn %in% 0, "redcapid"]


data[data$last_30_ecig_pen %in% 1 & data$last_30_ecig_yn %in% 0, c("redcapid", "last_30_ecig_pen", "last_30_ecig_yn", "pen_30_days")]  # remove redcapid 1073, 7234, 6046, 6065, 6094, 6119, 6129, 6159, 3117 for Vape Pen
data[data$last_30_ecig_pen %in% 9 & data$last_30_ecig_yn %in% 0, c("redcapid", "last_30_ecig_pen", "last_30_ecig_yn", "pen_30_days")] 
data[data$last_30_ecig_pen %in% 1 & data$pen_30_days %in% 1, c("redcapid", "last_30_ecig_pen", "last_30_ecig_yn", "pen_30_days")] 
rm.pen <- data[data$last_30_ecig_pen %in% 1 & data$last_30_ecig_yn %in% 0, "redcapid"]  

data[data$last_30_ecig_mod %in% 1 & data$last_30_ecig_yn %in% 0, c("redcapid", "last_30_ecig_mod", "last_30_ecig_yn", "mod_30_days")]  # remove redcapid 7252, 6046, 6065, 6129
data[data$last_30_ecig_mod %in% 9 & data$last_30_ecig_yn %in% 0, c("redcapid", "last_30_ecig_mod", "last_30_ecig_yn", "mod_30_days")]
data[data$last_30_ecig_mod %in% 1 & data$mod_30_days %in% 1, c("redcapid", "last_30_ecig_mod", "last_30_ecig_yn", "mod_30_days")]
rm.mod <- data[data$last_30_ecig_mod %in% 1 & data$last_30_ecig_yn %in% 0, "redcapid"] 

data[data$last_30_ecig_box_mod %in% 1 & data$last_30_ecig_yn %in% 0, c("redcapid", "last_30_ecig_box_mod", "last_30_ecig_yn", "box_30_days")]  # remove redcapid 7252, 6040, 6159 for Box Mod
data[data$last_30_ecig_box_mod %in% 9 & data$last_30_ecig_yn %in% 0, c("redcapid", "last_30_ecig_box_mod", "last_30_ecig_yn", "box_30_days")]  # remove redcapid 2042 for Box Mod
data[data$last_30_ecig_box_mod %in% 1 & data$box_30_days %in% 1, c("redcapid", "last_30_ecig_box_mod", "last_30_ecig_yn", "box_30_days")] 
rm.box <- data[data$last_30_ecig_box_mod %in% 1 & data$last_30_ecig_yn %in% 0 | data$last_30_ecig_box_mod %in% 9 & data$last_30_ecig_yn %in% 0, "redcapid"] 

data[data$last_30_ecig_juul %in% 1 & data$last_30_ecig_yn %in% 0, c("redcapid", "last_30_ecig_juul", "last_30_ecig_yn", "juul_30_days")]  # remove redcapid 1015, 1092, 7258, 6040, 6066, 2148, 3022, 3116, 3117 for JUUL
data[data$last_30_ecig_juul %in% 9 & data$last_30_ecig_yn %in% 0, c("redcapid", "last_30_ecig_juul", "last_30_ecig_yn", "juul_30_days")]
data[data$last_30_ecig_juul %in% 1 & data$juul_30_days %in% 1, c("redcapid", "last_30_ecig_juul", "last_30_ecig_yn", "juul_30_days")]
rm.juul <- data[data$last_30_ecig_juul %in% 1 & data$last_30_ecig_yn %in% 0, "redcapid"]

data[data$last_30_ecig_pod %in% 1 & data$last_30_ecig_yn %in% 0, c("redcapid", "last_30_ecig_pod", "last_30_ecig_yn", "pod_30_days")]  # remove redcapid 7252, 2042 for pod
data[data$last_30_ecig_pod %in% 9 & data$last_30_ecig_yn %in% 0, c("redcapid", "last_30_ecig_pod", "last_30_ecig_yn", "pod_30_days")]
data[data$last_30_ecig_pod %in% 1 & data$pod_30_days %in% 1, c("redcapid", "last_30_ecig_pod", "last_30_ecig_yn", "pod_30_days")]
rm.pod <- data[data$last_30_ecig_pod %in% 1 & data$last_30_ecig_yn %in% 0, "redcapid"]

## create variables 
EverUse <- function(var.ever, var.last, var.30.last){
  temp.data <- mutate(data, temp_ever_use_new = ifelse(get(var.ever) %in% 0, 0, 
                                            ifelse(get(var.ever) %in% 1, 1, 
                                                   ifelse(get(var.ever) %in% 2 & get(var.last) %in% 0 | get(var.last) %in% 9 & get(var.30.last) %in% 1, 2, 
                                                          ifelse(get(var.30.last) %in% 2, 3, 
                                                                 ifelse(get(var.30.last) %in% c(3, 4, 5), 4,
                                                                        ifelse(get(var.30.last) %in% c(6, 7), 5, NA)))))))
  
  return(temp.data)
}

dispose <- EverUse("ever_disp", "last_30_ecig_dispose", "disp_30_days")
data <- rename(dispose, "ever_disp_new" = temp_ever_use_new)
table(data$ever_disp_new, useNA = "always")

pen <- EverUse("ever_pen", "last_30_ecig_pen", "pen_30_days")
data <- rename(pen, "ever_pen_new"= temp_ever_use_new)
table(data$ever_pen_new, useNA = "always")

mod <- EverUse("ever_mod", "last_30_ecig_mod", "mod_30_days")
data <- rename(mod, "ever_mod_new" = temp_ever_use_new)
table(data$ever_mod_new, useNA = "always")

box <- EverUse("ever_box_mod", "last_30_ecig_box_mod", "box_30_days")
data <- rename(box, "ever_box_mod_new" = temp_ever_use_new)
table(data$ever_box_mod_new, useNA = "always")

juul <- EverUse("ever_juul", "last_30_ecig_juul", "juul_30_days")
data <- rename(juul, "ever_juul_new" = temp_ever_use_new)
table(data$ever_juul_new, useNA = "always")

pod <- EverUse("ever_pod", "last_30_ecig_pod", "pod_30_days")
data <- rename(pod, "ever_pod_new" = temp_ever_use_new)
table(data$ever_pod_new, useNA = "always")
```

```{r E-cig Use prepare variables First Device and others}
### First device use
data$sum.ever.use.all <- rowSums(data[, ever.use.all])
table(data$sum.ever.use.all, useNA = "always")

first.device.all <- colnames(data)[startsWith(colnames(data), "first_")]
apply(data[, first.device.all], 2, table, useNA = "always")
data$sum.first.device.all <- rowSums(data[, first.device.all], na.rm = T)

table(data[data$sum.ever.use.all > 0, "sum.first.device.all"], useNA = "always")

nrow(data[data$sum.ever.use.all > 0, ])

# analysis example:    FreqPerc.Sub("first_disp", data[data$ever_disp > 0, ])

### Device Used Most Often in the Past 30 Days
last.30.device <- last.30.all[2:8]
data$sum.last.30.device <- rowSums(data[, last.30.device], na.rm = T)
table(data$sum.last.30.device, useNA = "always")

most.device <- colnames(data)[endsWith(colnames(data), "_most")]
data$sum.most.device <- rowSums(data[, most.device], na.rm = T)
table(data$sum.most.device, useNA = "always")

table(data[data$last_30_ecig_dispose %in% 1, "sum.most.device"], useNA = "always")
table(data[data$last_30_ecig_pen %in% 1, "sum.most.device"], useNA = "always")
table(data[data$last_30_ecig_mod %in% 1, "sum.most.device"], useNA = "always")
table(data[data$last_30_ecig_box_mod %in% 1, "sum.most.device"], useNA = "always")
table(data[data$last_30_ecig_juul %in% 1, "sum.most.device"], useNA = "always")
table(data[data$last_30_ecig_pod %in% 1, "sum.most.device"], useNA = "always")
table(data[data$last_30_ecig_other %in% 1, "sum.most.device"], useNA = "always")

data[data$last_30_ecig_pen %in% 1 & data$sum.most.device %in% 0, c("redcapid", last.30.device, most.device)]  # redcapid 1001
pen.most <- data[!data$redcapid %in% 1001, ]

data[data$last_30_ecig_juul %in% 1 & data$sum.most.device %in% 0, c("redcapid", last.30.device, most.device)]  # redcapid 1111
juul.most <- data[!data$redcapid %in% 1111, ]

###  First flavor used
table(data[data$last_30_ecig_yn %in% 1, "flavor_first"], useNA = "always")

### Most common flavor used in past 30 days
table(data[data$last_30_ecig_yn %in% 1, "eliq_flavor2"], useNA = "always")

### Type of nicotine usually used
table(data[data$last_30_ecig_yn %in% 1, "nic_form"], useNA = "always")

### Typical nicotine level
nic.level <- colnames(data)[startsWith(colnames(data), "nic_level___")]
apply(data[data$last_30_ecig_yn %in% 1, nic.level], 2, table, useNA = "always")

nic.percent <- colnames(data)[startsWith(colnames(data), "nicotine_percent___")]
apply(data[data$last_30_ecig_yn %in% 1, nic.percent], 2, table, useNA = "always")

### Own device
table(data$ecig_2, useNA = "always")

### Among JUUL users
juul.use <- colnames(data)[startsWith(colnames(data), "juul_usage_")]
apply(data[data$ever_juul %in% 2, juul.use], 2, table, useNA = "always")

boxplot(data$juul_usage_day ~ data$project_type)
boxplot(data$juul_usage_week ~ data$project_type)
boxplot(data$juul_usage_month ~ data$project_type)

data[data$juul_usage_month %in% 900, ]
data.juul <- data[!data$juul_usage_month %in% 900, ]
```

```{r E-cig use Analysis tab1}
FreqPerc.noNA <- function(varname){
  freq <- table(varname, data$project_type, useNA = "no")
  perct <- round(prop.table(table(varname, data$project_type, useNA = "no"), margin = 2) * 100, 1)
  nperct <- paste(freq, " ", "(", perct, "%", ")", sep = "")
  
  nperct <- as.data.frame(matrix(nperct, ncol = 5))
  
  colnames(nperct) <- colnames(freq)
  rownames(nperct) <- rownames(freq)

  return(nperct)
}

E_cigarette_use <- colnames(data)[startsWith(colnames(data), "ever_") & endsWith(colnames(data), "new")]

tab1_E_cig_use <- data.frame(matrix(nrow = 0, ncol = 6))
colnames(tab1_E_cig_use) <- c(levels(data$project_type), "Missing")

for (i in 1:length(E_cigarette_use)) {
  var <- data[, E_cigarette_use[i]]
  tempt.tab <- FreqPerc(var)
  rownames(tempt.tab) <- paste(E_cigarette_use[i], "=", rownames(tempt.tab), sep = "")
  tab1_E_cig_use <- rbind(tab1_E_cig_use, tempt.tab)
}

tab1_E_cig_use

tab1_E_cig_use_noNA <- data.frame(matrix(nrow = 0, ncol = 5)) 
colnames(tab1_E_cig_use_noNA) <- levels(data$project_type)

for (i in 1:length(E_cigarette_use)) {
  var <- data[, E_cigarette_use[i]]
  tempt.tab <- FreqPerc.noNA(var)
  rownames(tempt.tab) <- paste(E_cigarette_use[i], "=", rownames(tempt.tab), sep = "")
  tab1_E_cig_use_noNA <- rbind(tab1_E_cig_use_noNA, tempt.tab)
}

tab1_E_cig_use_noNA
```

```{r save results of tab1}
# write.csv(tab1_E_cig_use, file = "/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/Pilot1_Methods_Paper/E_cig_use_tab1.csv")

# write.csv(tab1_E_cig_use_noNA, file = "/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/Pilot1_Methods_Paper/E_cig_use_tab1_noNA.csv")
```

```{r tab1 row max}
E_cigarette_use

data$max_use_all_dev <- apply(data[, E_cigarette_use], 1, max, na.rm = T)
select(data, redcapid, all_of(E_cigarette_use), max_use_all_dev)
table(data$max_use_all_dev, useNA = "always")

FreqPerc(data$max_use_all_dev)
```

```{r E-cig use Analysis tab2}
first.device.all
ever.use.all

tab2_fist_device <- data.frame(matrix(nrow = 0, ncol = 6))
colnames(tab2_fist_device) <- c(levels(data$project_type), "Missing")

for (i in 1:length(first.device.all)) {
  var <- first.device.all[i]
  sub <- data[data[, ever.use.all[i]] > 0, ]
  tempt.tab <- FreqPerc.Sub(var, sub)
  rownames(tempt.tab) <- paste(first.device.all[i], "=", rownames(tempt.tab), sep = "")
  tab2_fist_device <- rbind(tab2_fist_device, tempt.tab)
}

tab2_fist_device

table(data[data$ever_disp > 0, "first_disp"], data[data$ever_disp > 0, "project_type"], useNA = "always")
prop.table(table(data[data$ever_disp > 0, "first_disp"], data[data$ever_disp > 0, "project_type"], useNA = "always"), margin = 2)

table(data[data$ever_pen > 0, "first_pen"], data[data$ever_pen > 0, "project_type"], useNA = "always")
prop.table(table(data[data$ever_pen > 0, "first_pen"], data[data$ever_pen > 0, "project_type"], useNA = "always"), margin = 2)
```

```{r save results of tab2}
# write.csv(tab2_fist_device, file = "/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/Pilot1_Methods_Paper/E_cig_use_tab2.csv")
```

```{r E-cig use Analysis tab3}
most.device
last.30.device

tab3_most_device <- data.frame(matrix(nrow = 0, ncol = 6))
colnames(tab3_most_device) <- c(levels(data$project_type), "Missing")

for (i in 1:length(most.device)) {
  var <- most.device[i]
  sub <- data[data[, last.30.device[i]] %in% 1, ]
  tempt.tab <- FreqPerc.Sub(var, sub)
  rownames(tempt.tab) <- paste(most.device[i], "=", rownames(tempt.tab), sep = "")
  tab3_most_device <- rbind(tab3_most_device, tempt.tab)
}

tab3_most_device

FreqPerc.Sub("pen_most", pen.most[pen.most$last_30_ecig_pen %in% 1, ])
FreqPerc.Sub("juul_most", juul.most[juul.most$last_30_ecig_juul %in% 1, ])

table(data[data$last_30_ecig_dispose %in% 1, "disp_most"], data[data$last_30_ecig_dispose %in% 1, "project_type"], useNA = "always")
prop.table(table(data[data$last_30_ecig_dispose %in% 1, "disp_most"], data[data$last_30_ecig_dispose %in% 1, "project_type"], useNA = "always"), margin = 2)

table(data[data$last_30_ecig_pen %in% 1, "pen_most"], data[data$last_30_ecig_pen %in% 1, "project_type"], useNA = "always")
prop.table(table(data[data$last_30_ecig_pen %in% 1, "pen_most"], data[data$last_30_ecig_pen %in% 1, "project_type"], useNA = "always"), margin = 2)
```

```{r save results of tab3}
# write.csv(tab3_most_device, file = "/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/Pilot1_Methods_Paper/E_cig_use_tab3.csv")
```

```{r E-cig use Analysis tab4}
varlist_tab4 <- c("flavor_first", "eliq_flavor2", "nic_form", nic.level, nic.percent)

tab4_flavor_nic <- data.frame(matrix(nrow = 0, ncol = 6))
colnames(tab4_flavor_nic ) <- c(levels(data$project_type), "Missing")

for (i in 1:length(varlist_tab4)) {
  var <- varlist_tab4[i]
  sub <- data[data$last_30_ecig_yn %in% 1, ]
  tempt.tab <- FreqPerc.Sub(var, sub)
  rownames(tempt.tab) <- paste(varlist_tab4[i], "=", rownames(tempt.tab), sep = "")
  tab4_flavor_nic <- rbind(tab4_flavor_nic, tempt.tab)
}

tab4_flavor_nic
```

```{r save results of tab4}
# write.csv(tab4_flavor_nic, file = "/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/Pilot1_Methods_Paper/E_cig_use_tab4.csv")
```

```{r E-cig use Analysis tab5}
tab5_own_device <- FreqPerc(data[, "ecig_2"])
```

```{r save results of tab5}
#write.csv(tab5_own_device, file = "/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/Pilot1_Methods_Paper/E_cig_use_tab5.csv")
```

```{r E-cig use Analysis tab6}
juul.use

MeanSD("juul_usage_day", data[data$ever_juul %in% 2, ])
MeanSD("juul_usage_week", data[data$ever_juul %in% 2, ])
MeanSD("juul_usage_month", data.juul[data.juul$ever_juul %in% 2, ])

```

```{r prepare variables create the redcap survey time}
# create the redcap survey time
time.ncol <- ends_with("timestamp", vars = colnames(data))
start <- time.ncol[2]
end <- time.ncol[length(time.ncol)]

data$start.time <- strptime(data[, start], format = "%Y-%m-%d %H:%M:%S") 
data$end.time <- strptime(data[, end], format = "%Y-%m-%d %H:%M:%S")

data$diff.time <- difftime(data$end.time, data$start.time, units = "secs")
data$diff.time <- as.numeric(data$diff.time)
```

```{r}
boxplot(data$diff.time ~ data$project_type)
```

```{r}
table(data[data$project_type == "pp", ]$diff.time, useNA = "always")
data[data$diff.time == 20338, ]  # remove redcapid 6035

rc.time <- data[!data$redcapid %in% 6035, ]
boxplot(rc.time$diff.time ~ rc.time$project_type)
```

```{r}
hist(rc.time$diff.time, breaks = 100)
```

```{r}
tapply(rc.time$diff.time, rc.time$project_type, summary)
tapply(rc.time$diff.time, rc.time$project_type, IQR)

```

