---
title: "states"
author: "Yi"
date: "12/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(gmodels)
```


```{r}
data.origin <- read.csv("/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/Final_Data/EVOC_pilot1_08072020.csv", na.strings = "")

data <- data.origin
```

```{r}
FreqPerc <- function(varname){
  freq <- table(varname, data$project_type, useNA = "always")
  perct <- round(prop.table(table(varname, data$project_type, useNA = "always"), margin = 2) * 100, 1)
  nperct <- paste(freq, " ", "(", perct, "%", ")", sep = "")
  
  nperct <- as.data.frame(matrix(nperct, ncol = 6))
  
  colnames(nperct) <- c(colnames(freq)[1:length(colnames(freq)) - 1], "Missing")
  rownames(nperct) <- c(rownames(freq)[1:length(rownames(freq)) - 1], "Missing")

  return(nperct)
}
```


```{r states}
table(data$state, useNA = "always")
states <- FreqPerc(data$state)
```

```{r}
data.region <- mutate(data, region = ifelse(state %in% c(7, 19, 21, 29, 39, 45, 30, 32, 38), "Northeast",
                                     ifelse(state %in% c(14, 13, 22, 35, 49, 15, 16, 23, 25, 27, 34, 41), "Midwest", 
                                            ifelse(state %in% c(8, 51, 9, 10, 20, 33, 40, 46, 48, 1, 17, 24, 42, 4, 18, 36, 43), "South", 
                                                   ifelse(state %in% c(3, 6, 12, 31, 26, 44, 28, 50, 2, 5, 11, 37, 47), "West", NA)))))

regions <- FreqPerc(data.region$region)
```


```{r}
write.csv(states, "/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/Pilot1_Methods_Paper/updated09302020/states.csv")
write.csv(regions, "/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/Pilot1_Methods_Paper/updated09302020/regions.csv")
```

```{r}
CrossTable(data.region$region, data.region$project_type, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, format = "SPSS")

```

