---
title: "check_codebook_w2"
author: "Yi"
date: "4/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(haven)
library(gmodels)
```

```{r}
data <- read.csv("/Users/zhan039/Desktop/USC_HEAL/ADVANCE/check_codebook/W2/ADVANCEW2Survey_DATA_2021-04-14_1033.csv")
```

```{r substance use}
data %>% select(., contains("_spec"))  # all spec questions are removed

# Please specify which type of prescription pills you have used. [28] -[30]
lapply(data[, c("a2_life_use_sub_20a___1", "a2_life_use_sub_23a___1", "a2_life_use_sub_21a___1")], table, data$a2_life_use_sub_43a, useNA = "always")

# Please specify which type of other drugs you have used. [31] - [37]
lapply(data[, c("a2_life_use_sub_38a___1", "a2_life_use_sub_39a___1", "a2_life_use_sub_40a___1", "a2_life_use_sub_41a___1", "a2_life_use_sub_18a___1", "a2_life_use_sub_42a___1", "a2_life_use_sub_drug_other___1")], table, data$a2_life_use_sub_24a, useNA = "always")

#  Which substance did you use first? [39]-[66]
life_use <- select(data, contains("a2_life_use_sub_")) %>% select(., -c(a2_life_use_sub_43a, a2_life_use_sub_24a, contains("spec"))) %>% colnames(.)

first_use <- c()
  
for (i in 1:length(life_use)) {
  
  life_use_n <- life_use[i]
  if (grepl("___1", life_use_n)) {
    life_use_n <- substr(life_use_n, 1, nchar(life_use_n)-4)
  }
  
  first_use[i] <- sub("life_use", "first", life_use_n)
}

life_use
first_use

for (i in 1:length(life_use)) {
  table_life_first <- data %>% group_by(get(life_use[i]), get(first_use[i])) %>% summarise(n = n()) %>% spread(2, 3) 

  print(table_life_first)
}  # no issue


# In the past 30 days, how many days total have youused...? [69]-[96]
past_30_use <- c()
  
for (i in 1:length(life_use)) {
  
  life_use_n <- life_use[i]
  if (grepl("___1", life_use_n)) {
    life_use_n <- substr(life_use_n, 1, nchar(life_use_n)-4)
  }
  
  if (i %in% c(1, 2, 18:length(life_use))) {
    past_30_use[i] <- sub("life", "past_30", life_use_n)
  } else{
    past_30_use[i] <- sub("life_use", "past_30", life_use_n)
  }
  
}

life_use
past_30_use

for (i in 1:length(life_use)) {
  table_life_past_30 <- data %>% group_by(get(life_use[i]), get(past_30_use[i])) %>% summarise(n = n()) %>% spread(2, 3) 

  print(table_life_past_30)
}  # need to check 28

life_use[28]

table(data$a2_life_use_sub_drug_other___1, data$a2_past_30_use_sub_drug_other, useNA = "always")  # one issue  
table(data$a2_life_use_sub_42a___1, data$a2_past_30_use_sub_drug_other, useNA = "always")  # no issue


# Would you try any of the following substances if one of your best friends ordered it to you ?[99]-[105]
data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), any_vars(. %in% 1)) %>% select(., record_id, a2_life_use_sub_1a, a2_life_use_sub_2a) %>% arrange(desc(a2_life_use_sub_1a), desc(a2_life_use_sub_2a))

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), any_vars(. %in% 1)) %>% group_by(a2_try_friend_cig) %>% summarise(n = n())

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), all_vars(!.%in% 1)) %>% group_by(a2_try_friend_cig) %>% summarise(n = n())

table(data$a2_life_use_sub_3a, data$a2_try_friend_ecig, useNA = "always")
table(data$a2_life_use_sub_10a, data$a2_try_friend_mj, useNA = "always")
table(data$a2_life_use_sub_25a, data$a2_try_friend_mjfood, useNA = "always")
table(data$a2_life_use_sub_27a, data$a2_try_friend_e_mj, useNA = "always")
table(data$a2_life_use_sub_30a, data$a2_try_friend_mj_conc, useNA = "always")
table(data$a2_life_use_sub_11a, data$a2_try_friend_alc, useNA = "always")


# Do you think you would use any of the followingsubstances in the next year? [106]-[112]
data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), any_vars(. %in% 1)) %>% group_by(a2_use_next_yr_cig) %>% summarise(n = n())

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), all_vars(!.%in% 1)) %>% group_by(a2_use_next_yr_cig) %>% summarise(n = n())

table(data$a2_life_use_sub_3a, data$a2_use_next_yr_ecig, useNA = "always")
table(data$a2_life_use_sub_10a, data$a2_use_next_yr_mj, useNA = "always")
table(data$a2_life_use_sub_25a, data$a2_use_next_yr_mjfood, useNA = "always")
table(data$a2_life_use_sub_27a, data$a2_use_next_yr_e_mj, useNA = "always")
table(data$a2_life_use_sub_30a, data$a2_use_next_yr_mj_conc, useNA = "always")
table(data$a2_life_use_sub_11a, data$a2_use_next_yr_alc, useNA = "always")


# Are you curious about using any of the followingsubstances? [113]-[119]
data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), any_vars(. %in% 1)) %>% group_by(a2_curious_cig) %>% summarise(n = n())

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), all_vars(!.%in% 1)) %>% group_by(a2_curious_cig) %>% summarise(n = n())

table(data$a2_life_use_sub_3a, data$a2_curious_ecig, useNA = "always")
table(data$a2_life_use_sub_10a, data$a2_curious_mj, useNA = "always")
table(data$a2_life_use_sub_25a, data$a2_curious_mjfood, useNA = "always")
table(data$a2_life_use_sub_27a, data$a2_curious_e_mj, useNA = "always")
table(data$a2_life_use_sub_30a, data$a2_curious_mj_conc, useNA = "always")
table(data$a2_life_use_sub_11a, data$a2_curious_alc, useNA = "always")


# I think I might enjoy, experience pleasure, or feel goodusing the following substances...[120]-[126]
data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), any_vars(. %in% 1)) %>% group_by(a2_enjoy_cig) %>% summarise(n = n())

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), all_vars(!.%in% 1)) %>% group_by(a2_enjoy_cig) %>% summarise(n = n())

table(data$a2_life_use_sub_3a, data$a2_enjoy_ecig, useNA = "always")
table(data$a2_life_use_sub_10a, data$a2_enjoy_mj, useNA = "always")
table(data$a2_life_use_sub_25a, data$a2_enjoy_mjfood, useNA = "always")
table(data$a2_life_use_sub_27a, data$a2_enjoy_e_mj, useNA = "always")
table(data$a2_life_use_sub_30a, data$a2_enjoy_mj_conc, useNA = "always")
table(data$a2_life_use_sub_11a, data$a2_enjoy_alc, useNA = "always")


# I think I might feel bad, sick, or embarrassed using thefollowing substances...[127]-[133]
data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), any_vars(. %in% 1)) %>% group_by(a2_feel_bad_cig) %>% summarise(n = n())

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), all_vars(!.%in% 1)) %>% group_by(a2_feel_bad_cig) %>% summarise(n = n())

table(data$a2_life_use_sub_3a, data$a2_feel_bad_ecig, useNA = "always")
table(data$a2_life_use_sub_10a, data$a2_feel_bad_mj, useNA = "always")
table(data$a2_life_use_sub_25a, data$a2_feel_bad_mjfood, useNA = "always")
table(data$a2_life_use_sub_27a, data$a2_feel_bad_e_mj, useNA = "always")
table(data$a2_life_use_sub_30a, data$a2_feel_bad_mj_conc, useNA = "always")
table(data$a2_life_use_sub_11a, data$a2_feel_bad_alc, useNA = "always")

# [141] [143] [145] [147] [149] [151] [153]
data %>% filter(., a2_schoolid %in% 101) %>% select(., starts_with("a2_friend") & ends_with("_101")) %>% lapply(., table, useNA = "always")

data %>% filter(., !a2_schoolid %in% 101) %>% select(., starts_with("a2_friend") & ends_with("_101")) %>% lapply(., table, useNA = "always")

# [155] [157] [159] [161] [163] [165] [167]
data %>% filter(., a2_schoolid %in% 102) %>% select(., starts_with("a2_friend") & ends_with("_102")) %>% lapply(., table, useNA = "always")  # all are missing values

data %>% filter(., !a2_schoolid %in% 102) %>% select(., starts_with("a2_friend") & ends_with("_102")) %>% lapply(., table, useNA = "always")

data %>% select(., starts_with("a2_friend") & ends_with("_102")) %>% lapply(., table, useNA = "always")  # all are missing values

table(data$a2_schoolid, useNA = "always")  # schoolid 102 is collected

# [169] [171] [173] [175] [177] [179] [181]
data %>% filter(., a2_schoolid %in% 103) %>% select(., starts_with("a2_friend") & ends_with("_103")) %>% lapply(., table, useNA = "always") 

data %>% filter(., !a2_schoolid %in% 103) %>% select(., starts_with("a2_friend") & ends_with("_103")) %>% lapply(., table, useNA = "always") 

# [183] [185] [187] [189] [191] [193] [195]
data %>% filter(., a2_schoolid %in% 104) %>% select(., starts_with("a2_friend") & ends_with("_104")) %>% lapply(., table, useNA = "always") 

data %>% filter(., !a2_schoolid %in% 104) %>% select(., starts_with("a2_friend") & ends_with("_104")) %>% lapply(., table, useNA = "always") 

# [197] [199] [201] [203] [205] [207] [209]
data %>% filter(., a2_schoolid %in% 105) %>% select(., starts_with("a2_friend") & ends_with("_105")) %>% lapply(., table, useNA = "always") 

data %>% filter(., !a2_schoolid %in% 105) %>% select(., starts_with("a2_friend") & ends_with("_105")) %>% lapply(., table, useNA = "always") 

# [211] [213] [215] [217] [219] [221] [223]
data %>% filter(., a2_schoolid %in% 106) %>% select(., starts_with("a2_friend") & ends_with("_106")) %>% lapply(., table, useNA = "always") 

data %>% filter(., !a2_schoolid %in% 106) %>% select(., starts_with("a2_friend") & ends_with("_106")) %>% lapply(., table, useNA = "always") 

# [225] [227] [229] [231] [233] [235] [237]
data %>% filter(., a2_schoolid %in% 107) %>% select(., starts_with("a2_friend") & ends_with("_107")) %>% lapply(., table, useNA = "always") 

data %>% filter(., !a2_schoolid %in% 107) %>% select(., starts_with("a2_friend") & ends_with("_107")) %>% lapply(., table, useNA = "always") 

# [239] [241] [243] [245] [247] [249] [251]
data %>% filter(., a2_schoolid %in% 108) %>% select(., starts_with("a2_friend") & ends_with("_108")) %>% lapply(., table, useNA = "always")  # All are missing values

data %>% filter(., !a2_schoolid %in% 108) %>% select(., starts_with("a2_friend") & ends_with("_108")) %>% lapply(., table, useNA = "always") 

data %>% select(., starts_with("a2_friend") & ends_with("_108")) %>% lapply(., table, useNA = "always")  # all are missing values

table(data$a2_schoolid, useNA = "always")  # schoolid 108 is collected

# [253] [255] [257] [259] [261] [263] [265]
data %>% filter(., a2_schoolid %in% 109) %>% select(., starts_with("a2_friend") & ends_with("_109")) %>% lapply(., table, useNA = "always")

data %>% filter(., !a2_schoolid %in% 109) %>% select(., starts_with("a2_friend") & ends_with("_109")) %>% lapply(., table, useNA = "always")

# [267] [269] [271] [273] [275] [277] [279]
data %>% filter(., a2_schoolid %in% 110) %>% select(., starts_with("a2_friend") & ends_with("_110")) %>% lapply(., table, useNA = "always")  # not asked

data %>% filter(., !a2_schoolid %in% 110) %>% select(., starts_with("a2_friend") & ends_with("_110")) %>% lapply(., table, useNA = "always") 

data %>% select(., starts_with("a2_friend") & ends_with("_110")) %>% lapply(., table, useNA = "always")  # All are missing values

table(data$a2_schoolid, useNA = "always")  # No data collected from schoolid 110

# [281] [283] [285] [287] [289] [291] [293] 
data %>% filter(., a2_schoolid %in% 111) %>% select(., starts_with("a2_friend") & ends_with("_111")) %>% lapply(., table, useNA = "always")  # not asked

data %>% filter(., !a2_schoolid %in% 111) %>% select(., starts_with("a2_friend") & ends_with("_111")) %>% lapply(., table, useNA = "always") 

data %>% select(., starts_with("a2_friend") & ends_with("_111")) %>% lapply(., table, useNA = "always")   # All are missing values

table(data$a2_schoolid, useNA = "always")  # No data collected from schoolid 111

# [295] [297] [299] [301] [303] [305] [307] 
data %>% filter(., a2_schoolid %in% 112) %>% select(., starts_with("a2_friend") & ends_with("_112")) %>% lapply(., table, useNA = "always") 

data %>% filter(., !a2_schoolid %in% 112) %>% select(., starts_with("a2_friend") & ends_with("_112")) %>% lapply(., table, useNA = "always") 

# [309] [311] [313] [315] [317] [319] [321]
data %>% filter(., a2_schoolid %in% 113) %>% select(., starts_with("a2_friend") & ends_with("_113")) %>% lapply(., table, useNA = "always")  # All are missing values

data %>% filter(., !a2_schoolid %in% 113) %>% select(., starts_with("a2_friend") & ends_with("_113")) %>% lapply(., table, useNA = "always")  

data %>% select(., starts_with("a2_friend") & ends_with("_113")) %>% lapply(., table, useNA = "always")  # All are missing values

table(data$a2_schoolid, useNA = "always")  # schoolid 113 is collected

# [323] [325] [327] [329] [331] [333] [335]
data %>% filter(., a2_schoolid %in% 114) %>% select(., starts_with("a2_friend") & ends_with("_114")) %>% lapply(., table, useNA = "always")  # All are missing values

data %>% filter(., !a2_schoolid %in% 114) %>% select(., starts_with("a2_friend") & ends_with("_114")) %>% lapply(., table, useNA = "always")  

data %>% select(., starts_with("a2_friend") & ends_with("_114")) %>% lapply(., table, useNA = "always")  # All are missing values

table(data$a2_schoolid, useNA = "always")  # schoolid 114 is collected

# [337] [339] [241] [343] [345] [347] [349] are skipped because school 115 is not colleted


# During the past 30 days, did anyone refuse to sell youthese items because of your age? [351]-[355]
data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), any_vars(. %in% c(2, 3))) %>% group_by(a2_past30sell_1) %>% summarise(n = n())

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), all_vars(!. %in% c(2, 3))) %>% group_by(a2_past30sell_1) %>% summarise(n = n())

table(data$a2_life_use_sub_27a, data$a2_past30sell_2, useNA = "always")

data %>% filter_at(vars(a2_life_use_sub_8a, a2_life_use_sub_10a, a2_life_use_sub_25a, a2_life_use_sub_27a, a2_life_use_sub_26a, a2_life_use_sub_30a), any_vars(. %in% c(2, 3))) %>% group_by(a2_past30sell_3) %>% summarise(n = n())

data %>% filter_at(vars(a2_life_use_sub_8a, a2_life_use_sub_10a, a2_life_use_sub_25a, a2_life_use_sub_27a, a2_life_use_sub_26a, a2_life_use_sub_30a), all_vars(!. %in% c(2, 3))) %>% group_by(a2_past30sell_3) %>% summarise(n = n())

table(data$a2_life_use_sub_11a, data$a2_past30sell_4, useNA = "always")
table(data$a2_life_use_sub_6a, data$a2_past30sell_5, useNA = "always")

```

```{r Ecig}
# Have you ever used the following electronic nicotinedevices? [392]-[399]
Ecig_Ever <- colnames(data)[startsWith(colnames(data), "a2_ever")][1:8]

lapply(data[, Ecig_Ever], table, data$a2_life_use_sub_3a, useNA = "always")


# Which substance did you use first? (Select one)[401]-[408]
Ecig_First <- paste(Ecig_Ever, "first", sep = "_")

Ecig_Ever
Ecig_First

for (i in 1:length(Ecig_Ever)) {
  table_ever_first <- table(get(Ecig_Ever[i], data), get(Ecig_First[i], data), useNA = "always")
  cat(Ecig_Ever[i], Ecig_First[i])
  print(table_ever_first)
  cat("\n")
}


# In the past 30 days, how many days have you used the following types of electronic nicotine devices? [410]-[417]
Ecig_Past30 <- paste(gsub("ever", "ecig", Ecig_Ever), "last30", sep = "_")

Ecig_Ever
Ecig_Past30

for (i in 1:length(Ecig_Ever)) {
  table_ever_past30 <- table(get(Ecig_Ever[i], data), get(Ecig_Past30[i], data), useNA = "always")
  cat(Ecig_Ever[i], Ecig_First[i])
  print(table_ever_past30)
  cat("\n")
}


# These next few questions are about your experiences withe-cigarettes. [419]-[424]
Ecig_Experience <- c(colnames(data)[startsWith(colnames(data), "a2_ecig")][26:33], colnames(data)[startsWith(colnames(data), "a2_nic")])

Ecig_Experience

lapply(data[, Ecig_Experience], table, data$a2_life_use_sub_3a, useNA = "always")  # ecig_access have issues

table(data$a2_ecig_access___8, data$a2_ecig_access_spec, useNA = "always")


# The following questions are regarding the flavor of e-liquids you use in your device. [425]-[428]
Ecig_Flavor <- colnames(data)[startsWith(colnames(data), "a2_ecig_flavor")]

Ecig_Flavor

lapply(data[, Ecig_Flavor], table, data$a2_life_use_sub_3a, useNA = "always")


# attachment [430]-[432]
data %>% select(., contains("a2_ecig_attach_yn___")) %>% lapply(., table, data$a2_life_use_sub_3a, useNA = "always")

data %>% filter_at(vars(a2_ecig_attach_yn___1, a2_ecig_attach_yn___2), any_vars(. %in% 1)) %>% filter_at(vars(a2_past_30_sub_3a), all_vars(. %in% c(2:7))) %>% group_by(a2_ecig_attach_last30) %>% summarise(n = n())
table(data$a2_ecig_attach_last30, useNA = "always")


# bout [433]-[434]
table(data$a2_life_use_sub_3a, data$a2_ecig_bout_times_last30, useNA = "always")
table(data$a2_life_use_sub_3a, data$a2_ecig_bout_puffs_last30, useNA = "always")


# spend [435]
table(data$a2_life_use_sub_3a, data$a2_ecig_spend, useNA = "always")


# How would you rate the following from your first experience vaping nicotine? [436]-[447] 
Ecig_ese <- colnames(data)[startsWith(colnames(data), "a2_ese_ecig")]

Ecig_ese

lapply(data[, Ecig_ese], table, data$a2_life_use_sub_3a, useNA = "always")

table(data$a2_life_use_sub_3a, data$a2_ecig_quit_6mo, useNA = "always")
table(data$a2_ecig_quit_6mo, data$a2_ecig_quit_6mo_times, useNA = "always")


# hovc: The following questions are regarding your experience inthe last 6 months with use of electronic nicotine devices, NOT marijuana.Questions regarding marijuana will be asked in a later part of the survey. Inthe last 6 months, [448]-[457]
data %>% select(., starts_with("a2_hovc_")) %>% lapply(., table, data$a2_life_use_sub_3a, useNA = "always")


# stop vape: Many people experience problems when they stop or cutdown on their tobacco use. During the past 6 months, did you use any ofthe following to try to stop vaping nicotine ? [458]-[467]
data %>% select(., starts_with("a2_stop_vape_")) %>% lapply(., table, data$a2_ecig_quit_6mo, useNA = "always")
data %>% group_by(a2_ecig_quit_6mo, a2_stop_vape_face) %>% summarise(n = n())

table(data$a2_stop_vape_rx_med, data$a2_stop_vape_rx_med_spec, useNA = "always")
table(data$a2_stop_vape_another, data$a2_stop_vape_another_spec, useNA = "always")


# Ecig label : The following questions will ask your opinions about anelectronic vaping solution for e-cigarettes because we are interested howteens perceive them. We would like to know your opinions, even if you havenever vaped. Imagine if you saw these e-liquid solutions and how youmight react. [468]-[483] are removed due to text contents

table(data$random_ecig_label, useNA = "always")
data %>% select(., starts_with("a2_ecig_label_")) %>% lapply(., table, data$random_ecig_label, useNA = "always")


```

```{r Cigarette}
# The following questions are regarding your experience withuse of cigarettes. [491]-[496]
data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), any_vars(. %in% c(2, 3))) %>% group_by(a2_life_cig_100) %>% summarise(n = n())

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), all_vars(!. %in% c(2, 3))) %>% group_by(a2_life_cig_100) %>% summarise(n = n())

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), any_vars(. %in% c(2, 3))) %>% group_by(a2_cig_current_use) %>% summarise(n = n())

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), all_vars(!. %in% c(2, 3))) %>% group_by(a2_cig_current_use) %>% summarise(n = n())

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), any_vars(. %in% c(2, 3))) %>% group_by(a2_cig_bout_number_last30) %>% summarise(n = n())

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), all_vars(!. %in% c(2, 3))) %>% group_by(a2_cig_bout_number_last30) %>% summarise(n = n())

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), any_vars(. %in% 3)) %>% group_by(a2_cig_menthol_use) %>% summarise(n = n())

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), all_vars(!. %in% 3)) %>% group_by(a2_cig_menthol_use) %>% summarise(n = n())

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), any_vars(. %in% 3)) %>% group_by(a2_cig_flav_use) %>% summarise(n = n())

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), all_vars(!. %in% 3)) %>% group_by(a2_cig_flav_use) %>% summarise(n = n())

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), any_vars(. %in% c(2, 3))) %>% group_by(a2_cig_first_flav) %>% summarise(n = n())

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), all_vars(!. %in% c(2, 3))) %>% group_by(a2_cig_first_flav) %>% summarise(n = n())


# Cig ese: How would you rate the following from your firstexperience smoking a cigarette? [498]-[507]
data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), any_vars(. %in% c(2, 3))) %>% select(., starts_with("a2_ese_cig")) %>% lapply(., table, useNA = "always")

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), all_vars(!. %in% c(2, 3))) %>% select(., starts_with("a2_ese_cig")) %>% lapply(., table, useNA = "always")


# Cig quit: During the PAST 6 MONTHS, have you stopped smokingcigarettes for ONE DAY or longer BECAUSE YOU WERETRYING TO QUIT SMOKING? [508]-[509]
data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), any_vars(. %in% c(2, 3))) %>% select(., a2_cig_quit_last6mo) %>% table(., useNA = "always")

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), all_vars(!. %in% c(2, 3))) %>% select(., a2_cig_quit_last6mo) %>% table(., useNA = "always")

table(data$a2_cig_quit_last6mo, data$a2_cig_quit_times_last6mo, useNA = "always")


# honc [510]-[519]
data %>% group_by(a2_life_use_sub_1a, a2_life_use_sub_2a) %>% summarise(n = n())

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), any_vars(. %in% 3)) %>% select(., starts_with("a2_honc_")) %>% lapply(., table, useNA = "always")

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), all_vars(!. %in% 3)) %>% select(., starts_with("a2_honc_")) %>% lapply(., table, useNA = "always")


# cig quit: Many people experience problems when they stop or cutdown on their tobacco use. During the past 6 months, after stopping orcutting down on your use of cigarettes, did you EVER... [520]-[538]
Cig_Quit <- colnames(data)[startsWith(colnames(data), "a2_cig_quit")][3:21]

Cig_Quit

lapply(data[, Cig_Quit], table, data$a2_cig_quit_last6mo, useNA = "always")


# flav past 30 During the past 30 days, which flavors did you usually use inyour little cigars or cigarillos?[541]
data %>% filter_at(vars(a2_past_30_sub_5a, a2_past_30_sub_6a), any_vars(. %in% c(2:7))) %>% select(., contains("a2_cigarillo_flav_past30")) %>% lapply(., table, useNA = "always")

data %>% filter_at(vars(a2_past_30_sub_5a, a2_past_30_sub_6a), all_vars(!. %in% c(2:7))) %>% select(., contains("a2_cigarillo_flav_past30")) %>% lapply(., table, useNA = "always")

data %>% select(., contains("a2_cigarillo_flav_past30")) %>% lapply(., table, useNA = "always")


select(data, record_id, a2_past_30_sub_5a, a2_past_30_sub_6a, contains("a2_cigarillo_flav_past30"))
```

```{r marijuana}
Mj_life <- paste("a2_life_use_sub_", c(8, 10, 25, 27, 26, 30), "a", sep = "")

Mj_life

# Which type of marijuana did you use first? [545]-[551]
Mj_type_first <- paste("a2_mj_type_", c(1:6), "_first", sep = "")

Mj_life
Mj_type_first

for (i in 1:length(Mj_type_first)) {
  table_Mj_life_type_first <- table(get(Mj_life[i], data), get(Mj_type_first[i], data), useNA = "always")
  cat(Mj_life[i], Mj_type_first[i])
  print(table_Mj_life_type_first)
  cat("\n")
}

data %>% filter_at(Mj_life, any_vars(. %in% c(2, 3))) %>% select(., a2_mj_type_11_first) %>% table(., useNA = "always")
data %>% filter_at(Mj_life, all_vars(!. %in% c(2, 3))) %>% select(., a2_mj_type_11_first) %>% table(., useNA = "always")
table(data$a2_mj_type_11_first, useNA = "always")


# Which type of marijuana do you use most often? (Pleaseselect one) [553]-[559]
Mj_type_most <- paste("a2_mj_type_", c(1:6), "_most", sep = "")

Mj_life
Mj_type_most

for (i in 1:length(Mj_type_most)) {
  table_Mj_life_type_most <- table(get(Mj_life[i], data), get(Mj_type_most[i], data), useNA = "always")
  cat(Mj_life[i], Mj_type_most[i])
  print(table_Mj_life_type_most)
  cat("\n")
}

data %>% filter_at(Mj_life, any_vars(. %in% c(2, 3))) %>% select(., a2_mj_type_11_most) %>% table(., useNA = "always")
data %>% filter_at(Mj_life, all_vars(!. %in% c(2, 3))) %>% select(., a2_mj_type_11_most) %>% table(., useNA = "always")
table(data$a2_mj_type_11_most, useNA = "always")


# How would you rate your first experience vapingmarijuana ?[561]-[570]
Emj_experience <- colnames(data)[startsWith(colnames(data), "a2_emj_mlbse")]

Emj_experience

lapply(data[, Emj_experience], table, data$a2_life_use_sub_27a, useNA = "always")


# How would you rate your first experience smokingmarijuana? [571]-[580]
Mjsmoke_experience <- colnames(data)[startsWith(colnames(data), "a2_mjsmoke_mlbse")]

Mjsmoke_experience

lapply(data[, Mjsmoke_experience], table, data$a2_life_use_sub_10a, useNA = "always")


# How would you rate your first experience using ediblemarijuana? [581]-[590]
EdibleMj_experience <- colnames(data)[startsWith(colnames(data), "a2_edible_mj_mlbse")]

EdibleMj_experience

lapply(data[, EdibleMj_experience], table, data$a2_life_use_sub_25a, useNA = "always")


# During the past 30 days, on the days you smokedmarijuana, about how many marijuana cigarettes, joints,blunts, bowls, or the equivalent, did you usually have? [591]
data %>% filter_at(vars(a2_past_30_sub_10a, a2_past_30_sub_8a), any_vars(. %in% c(2:7))) %>% select(., a2_mj_amount_last30) %>% table(., useNA = "always")

data %>% filter_at(vars(a2_past_30_sub_10a, a2_past_30_sub_8a), all_vars(!. %in% c(2:7))) %>% select(., a2_mj_amount_last30) %>% table(., useNA = "always")


# emj bout [592]-[593]
table(data$a2_past_30_sub_27a, data$a2_emj_bout_times_last30, useNA = "always")
table(data$a2_past_30_sub_27a, data$a2_emj_bout_puffs_last30, useNA = "always")


# emj flav [594]
table(data$a2_past_30_sub_27a, data$a2_emj_flav_last30, useNA = "always")


# In a typical month when you use marijuana, how muchmarijuana do you usually use ? [596]
Mj_life

data %>% filter_at(Mj_life, any_vars(. %in% c(2, 3))) %>% select(., a2_dfaq_4) %>% table(., useNA = "always")
data %>% filter_at(Mj_life, all_vars(!. %in% c(2, 3))) %>% select(., a2_dfaq_4) %>% table(., useNA = "always")


# spend [597]
data %>% filter_at(Mj_life, any_vars(. %in% c(2, 3))) %>% select(., a2_mj_spend_last30) %>% table(., useNA = "always")
data %>% filter_at(Mj_life, all_vars(!. %in% c(2, 3))) %>% select(., a2_mj_spend_last30) %>% table(., useNA = "always")


# use [598]
data %>% filter_at(Mj_life, any_vars(. %in% c(2, 3))) %>% select(., contains("a2_mj_use_purpose___")) %>% lapply(., table, useNA = "always")
data %>% filter_at(Mj_life, all_vars(!. %in% c(2, 3))) %>% select(., contains("a2_mj_use_purpose___")) %>% lapply(., table, useNA = "always")


# cast [600]-[605]
data %>% filter_at(Mj_life, any_vars(. %in% 3)) %>% select(., contains("a2_cast_")) %>% lapply(., table, useNA = "always")
data %>% filter_at(Mj_life, all_vars(!. %in% 3)) %>% select(., contains("a2_cast_")) %>% lapply(., table, useNA = "always")


# mj access [606]
data %>% filter_at(Mj_life, any_vars(. %in% c(2, 3))) %>% select(., contains("a2_mj_access___")) %>% lapply(., table, useNA = "always")
data %>% filter_at(Mj_life, all_vars(!. %in% c(2, 3))) %>% select(., contains("a2_mj_access___")) %>% lapply(., table, useNA = "always")


# [608]
data %>% filter_at(Mj_life, any_vars(. %in% c(2, 3))) %>% select(., a2_mj_presc_ever) %>% table(., useNA = "always")
data %>% filter_at(Mj_life, all_vars(!. %in% c(2, 3))) %>% select(., a2_mj_presc_ever) %>% table(., useNA = "always")

# [609]
data %>% select(., contains("a2_mj_vape_reason___")) %>% lapply(., table, data$a2_life_use_sub_27a, useNA = "always")


# [610]
data %>% select(., contains("a2_mj_conc_reason___")) %>% lapply(., table, data$a2_life_use_sub_30a, useNA = "always")


# [611]
data %>% select(., contains("a2_mj_edible_reason___")) %>% lapply(., table, data$a2_life_use_sub_25a, useNA = "always")
```

```{r alcohol}
# [616]-[620]
Alc <- colnames(data)[startsWith(colnames(data), "a2_alc")][c(1:10)]

Alc

lapply(data[, Alc], table, data$a2_past_30_sub_11a, useNA = "always")

table(data$a2_alc_type_now___7, data$a2_alc_type_now_other, useNA = "always")
table(data$a2_alc_type_freq, data$a2_alc_type_freq_other, useNA = "always")

# rapi: Different things happen to people while they are drinkingalcohol or because of their alcohol drinking. Several of these things arelisted below. Indicate how many times each of these things happened toyou within the last 12 months. [622]-[637]
Rapi <- colnames(data)[startsWith(colnames(data), "a2_rapi")]

Rapi

lapply(data[, Rapi], table, data$a2_life_use_sub_11a, useNA = "always")



```

```{r medications}
# dast: [646]-[655]
data %>% filter_at(vars(a2_life_use_sub_43a, a2_life_use_sub_24a), any_vars(. %in% c(2, 3))) %>% select(., contains("a2_dast10_")) %>% lapply(., table, useNA = "always")

data %>% filter_at(vars(a2_life_use_sub_43a, a2_life_use_sub_24a), all_vars(!. %in% c(2, 3))) %>% select(., contains("a2_dast10_")) %>% lapply(., table, useNA = "always")



```

```{r respiratory effect}
table(data$a2_wheeze_1, data$a2_wheeze_12mo, useNA = "always")
table(data$a2_asthma_dr, data$a2_asthma_age, useNA = "always")

data %>% select(., starts_with("a2_breath_1")) %>% lapply(., table, data$a2_breath_1, useNA = "always")
```

```{r demographics}
table(data$a2_gender, useNA = "always")
# select(data, a2_gender)

table(data$a2_sexuality, useNA = "always")
table(data$a2_sexuality, data$a2_lgbt_age, useNA = "always")

data %>% filter_at(vars(a2_sexuality), all_vars(. %in% c(2:9))) %>% select(., a2_lgbt_out_family) %>% table(., useNA = "always")

data %>% filter_at(vars(a2_sexuality), all_vars(!. %in% c(2:9))) %>% select(., a2_lgbt_out_family) %>% table(., useNA = "always")  # There might be some issues here

data %>% filter_at(vars(a2_sexuality), all_vars(!. %in% c(2:9))) %>% filter(., !is.na(a2_lgbt_out_family)) %>% select(., a2_sex_birth, a2_sexuality, a2_lgbt_out_family)  # 5 participants have issues here

data %>% filter_at(vars(a2_sexuality), all_vars(. %in% c(2:9))) %>% filter(., !is.na(a2_lgbt_out_family)) %>% select(., a2_sex_birth, a2_sexuality, a2_lgbt_out_family)  # sex identities of all lgbt (3 participants) are Female

table(data$a2_lgbt_out_family, useNA = "always")  
table(data$a2_sex_birth)
table(data$a2_sex_birth, data$a2_lgbt_out_family, useNA = "always")

data %>% filter_at(vars(a2_sexuality), all_vars(. %in% c(2:9))) %>% filter_at(vars(a2_lgbt_out_family), all_vars(!is.na(.))) %>% select(., a2_sex_birth)

data %>% filter(., a2_sex_birth %in% 1 & !is.na(a2_lgbt_out_family)) %>% select(., a2_sexuality, a2_lgbt_out_family)

select(data, starts_with("a2_lgbt"))
```

```{r Act and Feel}
Rcads <- colnames(data)[startsWith(colnames(data), "a2_rcads")][1:47]

Rcads

data %>% filter_at(Rcads, any_vars(. %in% c(2:4))) %>% select(., a2_rcads_47_difficulty) %>% table(., useNA = "always")

data %>% filter_at(Rcads, all_vars(!. %in% c(2:4))) %>% select(., a2_rcads_47_difficulty) %>% table(., useNA = "always")

```

```{r covid}
table(data$a2_covid_yesno, data$a2_covid_doctor, useNA = "always")
table(data$a2_covid_test, data$a2_covid_test_result, useNA = "always")
lapply(data[, c("a2_covid_feeling", "a2_covid_care")], table, data$a2_covid_yesno, useNA = "always")

table(data$a2_covid_yesno, data$a2_covid_feeling, useNA = "always")

data %>% filter(., !a2_covid_yesno %in% c(1, 3) & !is.na(a2_covid_feeling)) %>% select(., record_id, a2_covid_yesno, a2_covid_feeling)

data %>% select(., starts_with("a2_covid_care_no___")) %>% lapply(., table, data$a2_covid_care, useNA = "always")

data %>% select(., starts_with("a2_covid_care_yes___")) %>% lapply(., table, data$a2_covid_care, useNA = "always")



table(data$a2_covid_yesno, data$a2_covid_likelihood, useNA = "always")
table(data$a2_covid_yesno, data$a2_covid_likelihood_feel, useNA = "always")
data %>% filter(., !a2_covid_yesno %in% 2 & !is.na(a2_covid_likelihood_feel))

data %>% select(., starts_with("a2_covid_friends_symp")) %>% lapply(., table, data$a2_covid_friends, useNA = "always")

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), any_vars(. %in% c(2, 3))) %>% select(., starts_with("a2_covid_cig_slider")) %>% lapply(., table, useNA = "always")

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a), all_vars(!. %in% c(2, 3))) %>% select(., starts_with("a2_covid_cig_slider")) %>% lapply(., table, useNA = "always")

data %>% filter_at(vars(a2_life_use_sub_3a), any_vars(. %in% c(2, 3))) %>% select(., starts_with("a2_covid_ecig_slider")) %>% lapply(., table, useNA = "always")

data %>% filter_at(vars(a2_life_use_sub_3a), all_vars(!. %in% c(2, 3))) %>% select(., starts_with("a2_covid_ecig_slider")) %>% lapply(., table, useNA = "always")

data %>% filter_at(Mj_life, any_vars(. %in% c(2, 3))) %>% select(., starts_with("a2_covid_mj_slider")) %>% lapply(., table, useNA = "always")

data %>% filter_at(Mj_life, all_vars(!. %in% c(2, 3))) %>% select(., starts_with("a2_covid_mj_slider")) %>% lapply(., table, useNA = "always")

data %>% filter_at(vars(a2_life_use_sub_11a), any_vars(. %in% c(2, 3))) %>% select(., starts_with("a2_covid_alc_slider")) %>% lapply(., table, useNA = "always")

data %>% filter_at(vars(a2_life_use_sub_11a), all_vars(!. %in% c(2, 3))) %>% select(., starts_with("a2_covid_alc_slider")) %>% lapply(., table, useNA = "always")

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a, a2_life_use_sub_3a, a2_life_use_sub_7a, all_of(Mj_life), a2_life_use_sub_11a), any_vars(. %in% c(2, 3))) %>% select(., a2_covid_share_subs) %>% table(., useNA = "always")

data %>% filter_at(vars(a2_life_use_sub_1a, a2_life_use_sub_2a, a2_life_use_sub_3a, a2_life_use_sub_7a, all_of(Mj_life), a2_life_use_sub_11a), all_vars(!. %in% c(2, 3))) %>% select(., a2_covid_share_subs) %>% table(., useNA = "always")

table(data$a2_covid_share_subs, useNA = "always")

table(data$a2_covid_comp, data$a2_covid_comp_no, useNA = "always")
table(data$a2_covid_comp_no, data$a2_covid_comp_yes, useNA = "always")

table(data$a2_covid_hotspot_school, data$a2_covid_hotspot_school_yes, useNA = "always")
```

