---
title: "menthol analysis"
author: "Yi"
date: "11/18/2019"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(haven)
library(tidyverse)
library(car)
library(effsize)
library(rcompanion)
```

```{r}
# functions
# Valid N
ValidN <- function(var) {
  return(sum(!is.na(var)))
}

# mean SD N
Mean.SD.N <- function(var){
 return(c(mean(var, na.rm = T),
  sd(var, na.rm = T),
  sum(!is.na(var))))
}

# t test
Ttest <- function(var){
  LeveneTest <- leveneTest(var, group = as.factor(filter.data$shq_8), center = mean)
  LeveneTest$result[1] <- ifelse(LeveneTest$`Pr(>F)`[1] < 0.05, FALSE, TRUE)
  LeveneTest$result[2] <- !LeveneTest$result[1]
  return(t.test(var[filter.data$shq_8 == 1], var[filter.data$shq_8 == 2], var.equal = LeveneTest$result[1]))
}

# frequency and percentage
FreqPercent <- function(var){
  frequency <- table(var)
  percentage <- frequency/sum(!is.na(var)) * 100
  return(rbind(frequency, percentage))
}

# chi-square or fisher test
ChiSqFisher <- function(var){
  chi.sq <- chisq.test(rbind(table(var[filter.data$shq_8 == 1]), table(var[filter.data$shq_8 == 2])), correct = F)
  fisher <- fisher.test(rbind(table(var[filter.data$shq_8 == 1]), table(var[filter.data$shq_8 == 2])))
  print(c("Chi-square:",chi.sq, "Fisher:",fisher))
}

# Hedges's g
CohensD <- function(var){
  d <- cohen.d(var[filter.data$shq_8 == 1], var[filter.data$shq_8 == 2], paired = F, na.rm = T, within = F, hedges.correction = T)
  return(d)
}

# Cramer's V
CramersV <- function(var){
  v <- cramerV(rbind(table(var[filter.data$shq_8 == 1]), table(var[filter.data$shq_8 == 2])))
  return(v)
}
```


```{r}
data <- read_sav("/Users/zhan039/Desktop/USC_HEAL/Menthol/fix_grow_data.sav")

# teleform.repeat <- read_sav("/Users/zhan039/Desktop/USC HEAL/GROW/GROW DATA-20190920T175512Z-001/Yi/teleform_repeat.sav")

head(data)
```


```{r}
# filter observations by race 
filter.data <- filter(data, piq_5 %in% 0 & (PIQ_6c_T %in% 1 | piq_6___3 %in% 1))
```

```{r}
# split data to menthol and unmenthol
table(filter.data$shq_8)
filter.data <- filter.data[!is.na(filter.data$shq_8), ]
menthol.data <- filter(filter.data, shq_8 == 1)
unmenthol.data <- filter(filter.data, shq_8 == 2)
nrow(menthol.data)
nrow(unmenthol.data)
```

```{r}
# table of brand
# table(tolower(filter.data$BRAND)) 

# as_tibble(FreqPercent(tolower(menthol.data$BRAND)))
# as_tibble(FreqPercent(tolower(unmenthol.data$BRAND)))
# ValidN(filter.data$BRAND)
```

```{r shq}
# Smoking History Questionnaire (shq)
shq.continuous <- c("shq_2","shq_3","shq_4", "shq_5", "shq_11","shq_12", "shq_13", "shq_16", "shq_17", "shq_18", "shq_19", "shq_20", "shq_21", "shq_22", "shq_23", "shq_24", "shq_25", "shq_26", "shq_27") # recode shq_1, shq_9___1 to shq_9___10, recode shq_34, shq_35

# continuous variables
apply(menthol.data[, shq.continuous], 2, Mean.SD.N)
apply(unmenthol.data[, shq.continuous], 2, Mean.SD.N)
apply(filter.data[, shq.continuous], 2, ValidN)

apply(filter.data[, shq.continuous], 2, Ttest)
apply(filter.data[, shq.continuous], 2, CohensD)

# (mean(filter.data[filter.data$shq_8 == 1, ]$shq_3, na.rm = T) - mean(filter.data[filter.data$shq_8 == 2, ]$shq_3, na.rm = T))/sqrt((length(filter.data[filter.data$shq_8 == 1, ]$shq_3)*sd(filter.data[filter.data$shq_8 == 1, ]$shq_3, na.rm = T)^2 + length(filter.data[filter.data$shq_8 == 2, ]$shq_3)* sd(filter.data[filter.data$shq_8 == 2, ]$shq_3, na.rm = T)^2)/(length(filter.data[filter.data$shq_8 == 1, ]$shq_3) + length(filter.data[filter.data$shq_8 == 2, ]$shq_3)))

# fix shq_1: remove impossible values
 # menthol.shq_1.outliers <- boxplot(menthol.data$shq_1)$out
 # unmenthol.shq_1.outliers <- boxplot(unmenthol.data$shq_1)$out
 # filter.data.cleanshq1 <- filter(filter.data, (shq_8 == 1 & !shq_1 %in% menthol.shq_1.outliers) | (shq_8 == 2 & !shq_1 %in% unmenthol.shq_1.outliers))

menthol.shq1.mean <- mean(menthol.data$shq_1, na.rm = T)
menthol.shq1.sd <- sd(menthol.data$shq_1, na.rm = T)

unmenthol.shq1.mean <- mean(unmenthol.data$shq_1, na.rm = T)
unmenthol.shq1.sd <- sd(unmenthol.data$shq_1, na.rm = T)

filter.out.shq1 <- filter(filter.data, shq_8 == 1 & (shq_1 < (menthol.shq1.mean - 2 * menthol.shq1.sd) | shq_1 > (menthol.shq1.mean + 2 * menthol.shq1.sd)) | shq_8 == 2 & (shq_1 < (unmenthol.shq1.mean - 2 * unmenthol.shq1.sd) | shq_1 > (unmenthol.shq1.mean + 2 * unmenthol.shq1.sd)))  # remove shq_1 == 2020 and shq_1 == 1314


filter.data.cleanshq1 <- filter.data[!(filter.data$shq_1 %in% filter.out.shq1$shq_1), ]

Mean.SD.N(filter.data.cleanshq1[filter.data.cleanshq1$shq_8 == 1, ]$shq_1)
Mean.SD.N(filter.data.cleanshq1[filter.data.cleanshq1$shq_8 == 2, ]$shq_1)
ValidN(filter.data.cleanshq1$shq_1)

shq_1.levene <- leveneTest(filter.data.cleanshq1$shq_1, group = as.factor(filter.data.cleanshq1$shq_8), center = mean)
shq_1.levene$result[1] <- ifelse(shq_1.levene$`Pr(>F)`[1] < 0.05, FALSE, TRUE)
t.test(filter.data.cleanshq1[filter.data.cleanshq1$shq_8 == 1, ]$shq_1, filter.data.cleanshq1[filter.data.cleanshq1$shq_8 == 2, ]$shq_1, var.equal = shq_1.levene$result[1])
cohen.d(filter.data.cleanshq1[filter.data.cleanshq1$shq_8 == 1, ]$shq_1, filter.data.cleanshq1[filter.data.cleanshq1$shq_8 == 2, ]$shq_1, paired = F, na.rm = T, within = F, hedges.correction = T)


# combine shq_9___ to calculate the count of products
shq_9___test <- filter(filter.data, is.na(shq_9___1) & is.na(shq_9___2) & is.na(shq_9___3) & is.na(shq_9___4) & is.na(shq_9___5) & is.na(shq_9___6) & is.na(shq_9___7) & is.na(shq_9___8) & is.na(shq_9___9) & is.na(shq_9___10)) # the participant who has missing values in all questions about ever use of products: cleaned_SID = 50392

filter.data.combineshq9 <- filter(filter.data, !(is.na(shq_9___1) & is.na(shq_9___2) & is.na(shq_9___3) & is.na(shq_9___4) & is.na(shq_9___5) & is.na(shq_9___6) & is.na(shq_9___7) & is.na(shq_9___8) & is.na(shq_9___9) & is.na(shq_9___10))) # filter out the participant who doesn't have valid information on ever use of products

filter.data.combineshq9 <- mutate(filter.data.combineshq9, 
                                  shq_9___1 = ifelse(is.na(shq_9___1), 0, shq_9___1), 
                                  shq_9___2 = ifelse(is.na(shq_9___2), 0, shq_9___2), 
                                  shq_9___3 = ifelse(is.na(shq_9___3), 0, shq_9___3), 
                                  shq_9___4 = ifelse(is.na(shq_9___4), 0, shq_9___4), 
                                  shq_9___5 = ifelse(is.na(shq_9___5), 0, shq_9___5), 
                                  shq_9___6 = ifelse(is.na(shq_9___6), 0, shq_9___6), 
                                  shq_9___7 = ifelse(is.na(shq_9___7), 0, shq_9___7), 
                                  shq_9___8 = ifelse(is.na(shq_9___8), 0, shq_9___8), 
                                  shq_9___9 = ifelse(is.na(shq_9___9), 0, shq_9___9), 
                                  shq_9___10 = ifelse(is.na(shq_9___10), 0, shq_9___10))

filter.data.combineshq9$shq_9 <- filter.data.combineshq9$shq_9___1 + filter.data.combineshq9$shq_9___2 + filter.data.combineshq9$shq_9___3 + filter.data.combineshq9$shq_9___4 + filter.data.combineshq9$shq_9___5 + filter.data.combineshq9$shq_9___6 + filter.data.combineshq9$shq_9___7 + filter.data.combineshq9$shq_9___8 + filter.data.combineshq9$shq_9___9 + filter.data.combineshq9$shq_9___10  

apply(filter.data.combineshq9[filter.data.combineshq9$shq_8 == 1, "shq_9"], 2, Mean.SD.N)
apply(filter.data.combineshq9[filter.data.combineshq9$shq_8 == 2, "shq_9"], 2, Mean.SD.N)

apply(filter.data.combineshq9[, "shq_9"], 2, ValidN)

shq_9.levene <- leveneTest(filter.data.combineshq9$shq_9, group = as.factor(filter.data.combineshq9$shq_8), center = mean)
shq_9.levene$result[1] <- ifelse(shq_9.levene$`Pr(>F)`[1] < 0.05, FALSE, TRUE)
t.test(filter.data.combineshq9[filter.data.combineshq9$shq_8 == 1, ]$shq_9, filter.data.combineshq9[filter.data.combineshq9$shq_8 == 2, ]$shq_9, var.equal = shq_9.levene$result[1])
cohen.d(filter.data.combineshq9[filter.data.combineshq9$shq_8 == 1, ]$shq_9, filter.data.combineshq9[filter.data.combineshq9$shq_8 == 2, ]$shq_9, paired = F, na.rm = T, within = F, hedges.correction = T)


# combine shq_16 to shq_27 to calculate the count of withdraw symptoms
filter.data.withdraw <- filter(filter.data, !(is.na(shq_16) & is.na(shq_17) & is.na(shq_18) & is.na(shq_19) & is.na(shq_20) & is.na(shq_21) & is.na(shq_22) & is.na(shq_23) & is.na(shq_24) & is.na(shq_25) & is.na(shq_26) & is.na(shq_27)))

filter.data.withdraw <- mutate(filter.data.withdraw, 
                               shq_16d = ifelse(is.na(shq_16), 0, ifelse(shq_16 == 1, 0, 1)),
                               shq_17d = ifelse(is.na(shq_17), 0, ifelse(shq_17 == 1, 0, 1)),
                               shq_18d = ifelse(is.na(shq_18), 0, ifelse(shq_18 == 1, 0, 1)),
                               shq_19d = ifelse(is.na(shq_19), 0, ifelse(shq_19 == 1, 0, 1)),
                               shq_20d = ifelse(is.na(shq_20), 0, ifelse(shq_20 == 1, 0, 1)),
                               shq_21d = ifelse(is.na(shq_21), 0, ifelse(shq_21 == 1, 0, 1)),
                               shq_22d = ifelse(is.na(shq_22), 0, ifelse(shq_22 == 1, 0, 1)),
                               shq_23d = ifelse(is.na(shq_23), 0, ifelse(shq_23 == 1, 0, 1)),
                               shq_24d = ifelse(is.na(shq_24), 0, ifelse(shq_24 == 1, 0, 1)),
                               shq_25d = ifelse(is.na(shq_25), 0, ifelse(shq_25 == 1, 0, 1)),
                               shq_26d = ifelse(is.na(shq_26), 0, ifelse(shq_26 == 1, 0, 1)),
                               shq_27d = ifelse(is.na(shq_27), 0, ifelse(shq_27 == 1, 0, 1)))

table(filter.data.withdraw$shq_16, useNA = "always")
table(filter.data.withdraw$shq_16d, useNA = "always")

filter.data.withdraw <- mutate(filter.data.withdraw, withdraw.count = shq_16d + shq_17d +shq_18d + shq_19d + shq_20d + shq_21d + shq_22d + shq_23d + shq_24d + shq_25d + shq_26d + shq_27d)

summary(filter.data.withdraw$withdraw.count)

Mean.SD.N(filter.data.withdraw[filter.data.withdraw$shq_8 == 1, ]$withdraw.count)
Mean.SD.N(filter.data.withdraw[filter.data.withdraw$shq_8 == 2, ]$withdraw.count)
ValidN(filter.data.withdraw$withdraw.count)

withdraw.levene <- leveneTest(filter.data.withdraw$withdraw.count, group = as.factor(filter.data.withdraw$shq_8), center = mean)

withdraw.levene$result[1] <- ifelse(withdraw.levene$`Pr(>F)`[1] < 0.05, FALSE, TRUE)
t.test(filter.data.withdraw[filter.data.withdraw$shq_8 == 1, ]$withdraw.count, filter.data.withdraw[filter.data.withdraw$shq_8 == 2, ]$withdraw.count, var.equal = withdraw.levene$result[1])
cohen.d(filter.data.withdraw[filter.data.withdraw$shq_8 == 1, ]$withdraw.count, filter.data.withdraw[filter.data.withdraw$shq_8 == 2, ]$withdraw.count, paired = F, na.rm = T, within = F, hedges.correction = T)



# categorize the count of withdraw symptoms to 2 levels
filter.data.withdraw <- mutate(filter.data.withdraw, withdraw.di = ifelse(withdraw.count == 0, 0, 1))
FreqPercent(filter.data.withdraw[filter.data.withdraw$shq_8 == 1, ]$withdraw.di)
FreqPercent(filter.data.withdraw[filter.data.withdraw$shq_8 == 2, ]$withdraw.di)
ValidN(filter.data.withdraw$withdraw.di)

withdraw.chisq <- chisq.test(rbind(table(filter.data.withdraw[filter.data.withdraw$shq_8 == 1, ]$withdraw.di), table(filter.data.withdraw[filter.data.withdraw$shq_8 == 2, ]$withdraw.di)), correct = F)
withdraw.fisher <- fisher.test(rbind(table(filter.data.withdraw[filter.data.withdraw$shq_8 == 1, ]$withdraw.di), table(filter.data.withdraw[filter.data.withdraw$shq_8 == 2, ]$withdraw.di)))
withdraw.chisq
withdraw.fisher
  
# categorical variables
shq.cat <- c("shq_6", "shq_7", "shq_10", "shq_14", "shq_15___1", "shq_15___2", "shq_15___3", "shq_15___4", "shq_15___5", "shq_15___6", "shq_15___7", "shq_15___8")  # recode shq_28 ~ shq_33

apply(menthol.data[, shq.cat], 2, FreqPercent)
apply(unmenthol.data[, shq.cat], 2, FreqPercent)
apply(filter.data[, shq.cat], 2, table)
apply(filter.data[, c("shq_6", "shq_7", "shq_10", "shq_14")], 2, ValidN)
apply(filter.data[, c("shq_15___1", "shq_15___2", "shq_15___3", "shq_15___4", "shq_15___5", "shq_15___6", "shq_15___7", "shq_15___8")], 2, ValidN)

# apply(filter.data[, shq.use[!shq.use %in% c(shq.continuous, "shq_8")]], 2, ChiSqFisher)
# ChiSqFisher(filter.data$shq_5)
# fisher.test(rbind(table(filter.data$shq_5[filter.data$shq_8 == 1]), table(filter.data$shq_5[filter.data$shq_8 == 2])))
ChiSqFisher(filter.data$shq_6)
CramersV(filter.data$shq_6)

ChiSqFisher(filter.data$shq_7)
CramersV(filter.data$shq_7)
# ChiSqFisher(filter.data$shq_9___1)
# ChiSqFisher(filter.data$shq_9___2)
# ChiSqFisher(filter.data$shq_9___3)
# ChiSqFisher(filter.data$shq_9___4)
# ChiSqFisher(filter.data$shq_9___5)
# ChiSqFisher(filter.data$shq_9___6)
# ChiSqFisher(filter.data$shq_9___7) can't use it because the cell of 0 is filled with 415
# chisq.test(matrix(c(415, 0, 249, 1), nrow = 2))
# fisher.test(matrix(c(415, 0, 249, 1), nrow = 2))
# ChiSqFisher(filter.data$shq_9___8)
# ChiSqFisher(filter.data$shq_9___9)
# ChiSqFisher(filter.data$shq_9___10)
ChiSqFisher(filter.data$shq_10)
CramersV(filter.data$shq_10)

ChiSqFisher(filter.data$shq_14)
CramersV(filter.data$shq_14)

ChiSqFisher(filter.data$shq_15___1)
CramersV(filter.data$shq_15___1)

ChiSqFisher(filter.data$shq_15___2)
CramersV(filter.data$shq_15___2)

ChiSqFisher(filter.data$shq_15___3)
CramersV(filter.data$shq_15___3)

ChiSqFisher(filter.data$shq_15___4)
CramersV(filter.data$shq_15___4)

ChiSqFisher(filter.data$shq_15___5)
CramersV(filter.data$shq_15___5)

ChiSqFisher(filter.data$shq_15___6)
CramersV(filter.data$shq_15___6)

ChiSqFisher(filter.data$shq_15___7)
CramersV(filter.data$shq_15___7)

ChiSqFisher(filter.data$shq_15___8)
CramersV(filter.data$shq_15___8)


# collapse shq_28 ~ shq_33 to mother's family and father's family
filter.data.family <- mutate(filter.data, father.family = ifelse(shq_28 %in%  1 | shq_28 %in% 2 | shq_29 %in% 1 | shq_29 %in% 2 | shq_30 %in% 1 | shq_30 %in% 2, 1, ifelse(shq_28 %in% 3 & shq_29 %in% 3 & shq_30 %in% 3, 0, NA)), mother.family = ifelse(shq_31 %in% 1 | shq_31 %in% 2 | shq_32 %in% 1 | shq_32 %in% 2 | shq_33 %in% 1 | shq_33 %in% 2, 1, ifelse(shq_31 %in% 3 & shq_32 %in% 3 & shq_33 %in% 3, 0, NA)))

FreqPercent(filter.data.family[filter.data.family$shq_8 == 1, ]$father.family)
FreqPercent(filter.data.family[filter.data.family$shq_8 == 2, ]$father.family)
ValidN(filter.data.family$father.family)

father.chisq <- chisq.test(rbind(table(filter.data.family[filter.data.family$shq_8 == 1, ]$father.family), table(filter.data.family[filter.data.family$shq_8 == 2, ]$father.family)), correct = F)
father.fisher <- fisher.test(rbind(table(filter.data.family[filter.data.family$shq_8 == 1, ]$father.family), table(filter.data.family[filter.data.family$shq_8 == 2, ]$father.family)))
father.chisq
father.fisher
cramerV(rbind(table(filter.data.family[filter.data.family$shq_8 == 1, ]$father.family), table(filter.data.family[filter.data.family$shq_8 == 2, ]$father.family)))


FreqPercent(filter.data.family[filter.data.family$shq_8 == 1, ]$mother.family)
FreqPercent(filter.data.family[filter.data.family$shq_8 == 2, ]$mother.family)
ValidN(filter.data.family$mother.family)

mother.chisq <- chisq.test(rbind(table(filter.data.family[filter.data.family$shq_8 == 1, ]$mother.family), table(filter.data.family[filter.data.family$shq_8 == 2, ]$mother.family)), correct = F)
mother.fisher <- fisher.test(rbind(table(filter.data.family[filter.data.family$shq_8 == 1, ]$mother.family), table(filter.data.family[filter.data.family$shq_8 == 2, ]$mother.family)))
mother.chisq
mother.fisher
cramerV(rbind(table(filter.data.family[filter.data.family$shq_8 == 1, ]$mother.family), table(filter.data.family[filter.data.family$shq_8 == 2, ]$mother.family)))


# collapse brothers and sisters variables
filter.data.siblings <- mutate(filter.data, sibling.prop = shq_35/shq_34 * 100)
filter.data.siblings <- filter(filter.data.siblings, 0 <= sibling.prop & sibling.prop <= 100)
Mean.SD.N(filter.data.siblings[filter.data.siblings$shq_8 == 1, ]$sibling.prop)
Mean.SD.N(filter.data.siblings[filter.data.siblings$shq_8 == 2, ]$sibling.prop)
ValidN(filter.data.siblings$sibling.prop)

sibling.levene <- leveneTest(filter.data.siblings$sibling.prop, group = as.factor(filter.data.siblings$shq_8), center = mean)

sibling.levene$result[1] <- ifelse(sibling.levene$`Pr(>F)`[1] < 0.05, FALSE, TRUE)
t.test(filter.data.siblings[filter.data.siblings$shq_8 == 1, ]$sibling.prop, filter.data.siblings[filter.data.siblings$shq_8 == 2, ]$sibling.prop, var.equal = sibling.levene$result[1])
cohen.d(filter.data.siblings[filter.data.siblings$shq_8 == 1, ]$sibling.prop, filter.data.siblings[filter.data.siblings$shq_8 == 2, ]$sibling.prop, paired = F, na.rm = T, within = F, hedges.correction = T)


```



```{r FTND}
# FTND
apply(menthol.data[, "FTND_SUM"], 2, Mean.SD.N)
apply(unmenthol.data[, "FTND_SUM"], 2, Mean.SD.N)
sum(!is.na(filter.data$FTND_SUM))
apply(filter.data[, "FTND_SUM"], 2, Ttest)
CohensD(filter.data$FTND_SUM)


# BCS
apply(menthol.data[, c("BCS_Addiction_Mean", "BCS_External_Mean", "BCS_Internal_Mean", "BCS_Mean")], 2, Mean.SD.N)
apply(unmenthol.data[, c("BCS_Addiction_Mean", "BCS_External_Mean", "BCS_Internal_Mean", "BCS_Mean")], 2, Mean.SD.N)
apply(filter.data[, c("BCS_Addiction_Mean", "BCS_External_Mean", "BCS_Internal_Mean", "BCS_Mean")], 2, ValidN)
apply(filter.data[, c("BCS_Addiction_Mean", "BCS_External_Mean", "BCS_Internal_Mean", "BCS_Mean")], 2, Ttest)

# WISDM
apply(menthol.data[, c("WISDM_AA_Mean", "WISDM_A_Mean", "WISDM_LC_Mean", "WISDM_CE_Mean", "WISDM_C_Mean", "WISDM_CEAP_Mean", "WISDM_S_Mean", "WISDM_TSP_Mean", "WISDM_Tol_Mean", "WISDM_WC_Mean", "WISDM_AE_Mean", "WISDM_TOT_Mean")], 2, Mean.SD.N)
apply(unmenthol.data[, c("WISDM_AA_Mean", "WISDM_A_Mean", "WISDM_LC_Mean", "WISDM_CE_Mean", "WISDM_C_Mean", "WISDM_CEAP_Mean", "WISDM_S_Mean", "WISDM_TSP_Mean", "WISDM_Tol_Mean", "WISDM_WC_Mean", "WISDM_AE_Mean", "WISDM_TOT_Mean")], 2, Mean.SD.N)
apply(filter.data[, c("WISDM_AA_Mean", "WISDM_A_Mean", "WISDM_LC_Mean", "WISDM_CE_Mean", "WISDM_C_Mean", "WISDM_CEAP_Mean", "WISDM_S_Mean", "WISDM_TSP_Mean", "WISDM_Tol_Mean", "WISDM_WC_Mean", "WISDM_AE_Mean", "WISDM_TOT_Mean")], 2, ValidN)
apply(filter.data[, c("WISDM_AA_Mean", "WISDM_A_Mean", "WISDM_LC_Mean", "WISDM_CE_Mean", "WISDM_C_Mean", "WISDM_CEAP_Mean", "WISDM_S_Mean", "WISDM_TSP_Mean", "WISDM_Tol_Mean", "WISDM_WC_Mean", "WISDM_AE_Mean", "WISDM_TOT_Mean")], 2, Ttest)


# DAST
apply(menthol.data[, c("DAST_Sum", "DAST_Classification")], 2, Mean.SD.N)
apply(unmenthol.data[, c("DAST_Sum", "DAST_Classification")], 2, Mean.SD.N)
apply(filter.data[, c("DAST_Sum", "DAST_Classification")], 2, ValidN)
apply(filter.data[, c("DAST_Sum", "DAST_Classification")], 2, Ttest)

# AUDIT
apply(menthol.data[, c("AUDIT_Sum", "AUDIT_Risk_Level")], 2, Mean.SD.N)
apply(unmenthol.data[, c("AUDIT_Sum", "AUDIT_Risk_Level")], 2, Mean.SD.N)
apply(filter.data[, c("AUDIT_Sum", "AUDIT_Risk_Level")], 2, ValidN)
apply(filter.data[, c("AUDIT_Sum", "AUDIT_Risk_Level")], 2, Ttest)

# SHS
apply(menthol.data[, "SHS_Mean"], 2, Mean.SD.N)
apply(unmenthol.data[, "SHS_Mean"], 2, Mean.SD.N)
apply(filter.data[, "SHS_Mean"], 2, ValidN)
apply(filter.data[, "SHS_Mean"], 2, Ttest)

# MIBI
apply(menthol.data[, "MIBI_Mean"], 2, Mean.SD.N)
apply(unmenthol.data[, "MIBI_Mean"], 2, Mean.SD.N)
apply(filter.data[, "MIBI_Mean"], 2, ValidN)
apply(filter.data[, "MIBI_Mean"], 2, Ttest)

# NPS
apply(menthol.data[, "NPS_Mean"], 2, Mean.SD.N)
apply(unmenthol.data[, "NPS_Mean"], 2, Mean.SD.N)
apply(filter.data[, "NPS_Mean"], 2, ValidN)
apply(filter.data[, "NPS_Mean"], 2, Ttest)

# EDDS
apply(menthol.data[, "EDDS_Mean"], 2, Mean.SD.N)
apply(unmenthol.data[, "EDDS_Mean"], 2, Mean.SD.N)
apply(filter.data[, "EDDS_Mean"], 2, ValidN)
apply(filter.data[, "EDDS_Mean"], 2, Ttest)

# SSS
apply(menthol.data[, "sss_1"], 2, Mean.SD.N)
apply(unmenthol.data[, "sss_1"], 2, Mean.SD.N)
apply(filter.data[, "sss_1"], 2, ValidN)
apply(filter.data[, "sss_1"], 2, Ttest)

# base_co
apply(menthol.data[, "co"], 2, Mean.SD.N)
apply(unmenthol.data[, "co"], 2, Mean.SD.N)
apply(filter.data[, "co"], 2, ValidN)
apply(filter.data[, "co"], 2, Ttest)

```

```{r mental health}
# CESD 
apply(menthol.data[, "CESD_TOT_SUM"], 2, Mean.SD.N)
apply(unmenthol.data[, "CESD_TOT_SUM"], 2, Mean.SD.N)
apply(filter.data[, "CESD_TOT_SUM"], 2, ValidN)
filter.data.cutoff <- mutate(filter.data, CESD_TOT_SUM_CAT = ifelse(CESD_TOT_SUM > 16, 1, 0))
ChiSqFisher(filter.data.cutoff$CESD_TOT_SUM_CAT)

# RAQ
apply(menthol.data[, "RAQ_Mean"], 2, Mean.SD.N)
apply(unmenthol.data[, "RAQ_Mean"], 2, Mean.SD.N)
apply(filter.data[, "RAQ_Mean"], 2, ValidN)
apply(filter.data[, "RAQ_Mean"], 2, Ttest)
apply(filter.data[, "RAQ_Mean"], 2, CohensD)

# IDAS
apply(menthol.data[, "IDAS_gd_MEAN"], 2, Mean.SD.N)
apply(unmenthol.data[, "IDAS_gd_MEAN"], 2, Mean.SD.N)
apply(filter.data[, "IDAS_gd_MEAN"], 2, ValidN)
apply(filter.data[, "IDAS_gd_MEAN"], 2, Ttest)
apply(filter.data[, "IDAS_gd_MEAN"], 2, CohensD)

apply(menthol.data[, "IDAS_dy_MEAN"], 2, Mean.SD.N)
apply(unmenthol.data[, "IDAS_dy_MEAN"], 2, Mean.SD.N)
apply(filter.data[, "IDAS_dy_MEAN"], 2, ValidN)
apply(filter.data[, "IDAS_dy_MEAN"], 2, Ttest)
apply(filter.data[, "IDAS_dy_MEAN"], 2, CohensD)

apply(menthol.data[, "IDAS_lass_MEAN"], 2, Mean.SD.N)
apply(unmenthol.data[, "IDAS_lass_MEAN"], 2, Mean.SD.N)
apply(filter.data[, "IDAS_lass_MEAN"], 2, ValidN)
apply(filter.data[, "IDAS_lass_MEAN"], 2, Ttest)
apply(filter.data[, "IDAS_lass_MEAN"], 2, CohensD)

apply(menthol.data[, "IDAS_insom_MEAN"], 2, Mean.SD.N)
apply(unmenthol.data[, "IDAS_insom_MEAN"], 2, Mean.SD.N)
apply(filter.data[, "IDAS_insom_MEAN"], 2, ValidN)
apply(filter.data[, "IDAS_insom_MEAN"], 2, Ttest)
apply(filter.data[, "IDAS_insom_MEAN"], 2, CohensD)

apply(menthol.data[, "IDAS_al_MEAN"], 2, Mean.SD.N)
apply(unmenthol.data[, "IDAS_al_MEAN"], 2, Mean.SD.N)
apply(filter.data[, "IDAS_al_MEAN"], 2, ValidN)
apply(filter.data[, "IDAS_al_MEAN"], 2, Ttest)
apply(filter.data[, "IDAS_al_MEAN"], 2, CohensD)

apply(menthol.data[, "IDAS_ag_MEAN"], 2, Mean.SD.N)
apply(unmenthol.data[, "IDAS_ag_MEAN"], 2, Mean.SD.N)
apply(filter.data[, "IDAS_ag_MEAN"], 2, ValidN)
apply(filter.data[, "IDAS_ag_MEAN"], 2, Ttest)
apply(filter.data[, "IDAS_ag_MEAN"], 2, CohensD)

apply(menthol.data[, "IDAS_temp_MEAN"], 2, Mean.SD.N)
apply(unmenthol.data[, "IDAS_temp_MEAN"], 2, Mean.SD.N)
apply(filter.data[, "IDAS_temp_MEAN"], 2, ValidN)
apply(filter.data[, "IDAS_temp_MEAN"], 2, Ttest)
apply(filter.data[, "IDAS_temp_MEAN"], 2, CohensD)

apply(menthol.data[, "IDAS_wb_MEAN"], 2, Mean.SD.N)
apply(unmenthol.data[, "IDAS_wb_MEAN"], 2, Mean.SD.N)
apply(filter.data[, "IDAS_wb_MEAN"], 2, ValidN)
apply(filter.data[, "IDAS_wb_MEAN"], 2, Ttest)
apply(filter.data[, "IDAS_wb_MEAN"], 2, CohensD)

apply(menthol.data[, "IDAS_sa_MEAN"], 2, Mean.SD.N)
apply(unmenthol.data[, "IDAS_sa_MEAN"], 2, Mean.SD.N)
apply(filter.data[, "IDAS_sa_MEAN"], 2, ValidN)
apply(filter.data[, "IDAS_sa_MEAN"], 2, Ttest)
apply(filter.data[, "IDAS_sa_MEAN"], 2, CohensD)

apply(menthol.data[, "IDAS_panic_MEAN"], 2, Mean.SD.N)
apply(unmenthol.data[, "IDAS_panic_MEAN"], 2, Mean.SD.N)
apply(filter.data[, "IDAS_panic_MEAN"], 2, ValidN)
apply(filter.data[, "IDAS_panic_MEAN"], 2, Ttest)
apply(filter.data[, "IDAS_panic_MEAN"], 2, CohensD)

apply(menthol.data[, "IDAS_truma_MEAN"], 2, Mean.SD.N)
apply(unmenthol.data[, "IDAS_truma_MEAN"], 2, Mean.SD.N)
apply(filter.data[, "IDAS_truma_MEAN"], 2, ValidN)
apply(filter.data[, "IDAS_truma_MEAN"], 2, Ttest)
apply(filter.data[, "IDAS_truma_MEAN"], 2, CohensD)

apply(menthol.data[, "IDAS_su_MEAN"], 2, Mean.SD.N)
apply(unmenthol.data[, "IDAS_su_MEAN"], 2, Mean.SD.N)
apply(filter.data[, "IDAS_su_MEAN"], 2, ValidN)
apply(filter.data[, "IDAS_su_MEAN"], 2, Ttest)

# SHAPS
apply(menthol.data[, "SHAPS_Mean"], 2, Mean.SD.N)
apply(unmenthol.data[, "SHAPS_Mean"], 2, Mean.SD.N)
apply(filter.data[, "SHAPS_Mean"], 2, ValidN)
apply(filter.data[, "SHAPS_Mean"], 2, Ttest)
apply(filter.data[, "SHAPS_Mean"], 2, CohensD)

# ASI
apply(menthol.data[, "ASI_Mean"], 2, Mean.SD.N)
apply(unmenthol.data[, "ASI_Mean"], 2, Mean.SD.N)
apply(filter.data[, "ASI_Mean"], 2, ValidN)
apply(filter.data[, "ASI_Mean"], 2, Ttest)
apply(filter.data[, "ASI_Mean"], 2, CohensD)

# OCIR
apply(menthol.data[, "OCIR_Washing_Sum"], 2, Mean.SD.N)
apply(unmenthol.data[, "OCIR_Washing_Sum"], 2, Mean.SD.N)
apply(filter.data[, "OCIR_Washing_Sum"], 2, ValidN)
apply(filter.data[, "OCIR_Washing_Sum"], 2, Ttest)
apply(filter.data[, "OCIR_Washing_Sum"], 2, CohensD)

apply(menthol.data[, "OCIR_Obsessing_Sum"], 2, Mean.SD.N)
apply(unmenthol.data[, "OCIR_Obsessing_Sum"], 2, Mean.SD.N)
apply(filter.data[, "OCIR_Obsessing_Sum"], 2, ValidN)
apply(filter.data[, "OCIR_Obsessing_Sum"], 2, Ttest)
apply(filter.data[, "OCIR_Obsessing_Sum"], 2, CohensD)

apply(menthol.data[, "OCIR_Hoarding_Sum"], 2, Mean.SD.N)
apply(unmenthol.data[, "OCIR_Hoarding_Sum"], 2, Mean.SD.N)
apply(filter.data[, "OCIR_Hoarding_Sum"], 2, ValidN)
apply(filter.data[, "OCIR_Hoarding_Sum"], 2, Ttest)
apply(filter.data[, "OCIR_Hoarding_Sum"], 2, CohensD)

apply(menthol.data[, "OCIR_Ordering_Sum"], 2, Mean.SD.N)
apply(unmenthol.data[, "OCIR_Ordering_Sum"], 2, Mean.SD.N)
apply(filter.data[, "OCIR_Ordering_Sum"], 2, ValidN)
apply(filter.data[, "OCIR_Ordering_Sum"], 2, Ttest)
apply(filter.data[, "OCIR_Ordering_Sum"], 2, CohensD)

apply(menthol.data[, "OCIR_Checking_Sum"], 2, Mean.SD.N)
apply(unmenthol.data[, "OCIR_Checking_Sum"], 2, Mean.SD.N)
apply(filter.data[, "OCIR_Checking_Sum"], 2, ValidN)
apply(filter.data[, "OCIR_Checking_Sum"], 2, Ttest)
apply(filter.data[, "OCIR_Checking_Sum"], 2, CohensD)

apply(menthol.data[, "OCIR_Neutralizing_Sum"], 2, Mean.SD.N)
apply(unmenthol.data[, "OCIR_Neutralizing_Sum"], 2, Mean.SD.N)
apply(filter.data[, "OCIR_Neutralizing_Sum"], 2, ValidN)
apply(filter.data[, "OCIR_Neutralizing_Sum"], 2, Ttest)
apply(filter.data[, "OCIR_Neutralizing_Sum"], 2, CohensD)

apply(menthol.data[, "OCIR_Total_Sum"], 2, Mean.SD.N)
apply(unmenthol.data[, "OCIR_Total_Sum"], 2, Mean.SD.N)
apply(filter.data[, "OCIR_Total_Sum"], 2, ValidN)
filter.data.cutoff <- mutate(filter.data.cutoff, OCIR_Total_Sum_CAT = ifelse(OCIR_Total_Sum > 36, 1, 0))
FreqPercent(filter.data.cutoff[filter.data.cutoff$shq_8 == 1,]$OCIR_Total_Sum_CAT)
FreqPercent(filter.data.cutoff[filter.data.cutoff$shq_8 == 2,]$OCIR_Total_Sum_CAT)
chisq.test(rbind(table(filter.data.cutoff[filter.data.cutoff$shq_8 == 1,]$OCIR_Total_Sum_CAT), table(filter.data.cutoff[filter.data.cutoff$shq_8 == 2,]$OCIR_Total_Sum_CAT)), correct = F)
cramerV(rbind(table(filter.data.cutoff[filter.data.cutoff$shq_8 == 1,]$OCIR_Total_Sum_CAT), table(filter.data.cutoff[filter.data.cutoff$shq_8 == 2,]$OCIR_Total_Sum_CAT)))

# TPI
apply(menthol.data[, "TPI_a_MEAN"], 2, Mean.SD.N)
apply(unmenthol.data[, "TPI_a_MEAN"], 2, Mean.SD.N)
apply(filter.data[, "TPI_a_MEAN"], 2, ValidN)
apply(filter.data[, "TPI_a_MEAN"], 2, Ttest)

apply(menthol.data[, "TPI_b_MEAN"], 2, Mean.SD.N)
apply(unmenthol.data[, "TPI_b_MEAN"], 2, Mean.SD.N)
apply(filter.data[, "TPI_b_MEAN"], 2, ValidN)
apply(filter.data[, "TPI_b_MEAN"], 2, Ttest)

apply(menthol.data[, "TPI_c_MEAN"], 2, Mean.SD.N)
apply(unmenthol.data[, "TPI_c_MEAN"], 2, Mean.SD.N)
apply(filter.data[, "TPI_c_MEAN"], 2, ValidN)
apply(filter.data[, "TPI_c_MEAN"], 2, Ttest)

# UPPSP-P
apply(menthol.data[, "UPPSP_NegUrge_Mean"], 2, Mean.SD.N)
apply(unmenthol.data[, "UPPSP_NegUrge_Mean"], 2, Mean.SD.N)
apply(filter.data[, "UPPSP_NegUrge_Mean"], 2, ValidN)
apply(filter.data[, "UPPSP_NegUrge_Mean"], 2, Ttest)
apply(filter.data[, "UPPSP_NegUrge_Mean"], 2, CohensD)

apply(menthol.data[, "UPPSP_PosUrge_Mean"], 2, Mean.SD.N)
apply(unmenthol.data[, "UPPSP_PosUrge_Mean"], 2, Mean.SD.N)
apply(filter.data[, "UPPSP_PosUrge_Mean"], 2, ValidN)
apply(filter.data[, "UPPSP_PosUrge_Mean"], 2, Ttest)
apply(filter.data[, "UPPSP_PosUrge_Mean"], 2, CohensD)

apply(menthol.data[, "UPPSP_Premed_Mean"], 2, Mean.SD.N)
apply(unmenthol.data[, "UPPSP_Premed_Mean"], 2, Mean.SD.N)
apply(filter.data[, "UPPSP_Premed_Mean"], 2, ValidN)
apply(filter.data[, "UPPSP_Premed_Mean"], 2, Ttest)
apply(filter.data[, "UPPSP_Premed_Mean"], 2, CohensD)

apply(menthol.data[, "UPPSP_Preserv_Mean"], 2, Mean.SD.N)
apply(unmenthol.data[, "UPPSP_Preserv_Mean"], 2, Mean.SD.N)
apply(filter.data[, "UPPSP_Preserv_Mean"], 2, ValidN)
apply(filter.data[, "UPPSP_Preserv_Mean"], 2, Ttest)
apply(filter.data[, "UPPSP_Preserv_Mean"], 2, CohensD)

apply(menthol.data[, "UPPSP_Sen_Mean"], 2, Mean.SD.N)
apply(unmenthol.data[, "UPPSP_Sen_Mean"], 2, Mean.SD.N)
apply(filter.data[, "UPPSP_Sen_Mean"], 2, ValidN)
apply(filter.data[, "UPPSP_Sen_Mean"], 2, Ttest)
apply(filter.data[, "UPPSP_Sen_Mean"], 2, CohensD)

# GCPS/GPCS
apply(menthol.data[, "GPCS_CPI"], 2, Mean.SD.N)
apply(unmenthol.data[, "GPCS_CPI"], 2, Mean.SD.N)
apply(filter.data[, "GPCS_CPI"], 2, ValidN)
apply(filter.data[, "GPCS_CPI"], 2, Ttest)

apply(menthol.data[, "GPCS_DS"], 2, Mean.SD.N)
apply(unmenthol.data[, "GPCS_DS"], 2, Mean.SD.N)
apply(filter.data[, "GPCS_DS"], 2, ValidN)
apply(filter.data[, "GPCS_DS"], 2, Ttest)

apply(menthol.data[, "GPCS_Grade"], 2, Mean.SD.N)
apply(unmenthol.data[, "GPCS_Grade"], 2, Mean.SD.N)
apply(filter.data[, "GPCS_Grade"], 2, ValidN)
apply(filter.data[, "GPCS_Grade"], 2, Ttest)

apply(menthol.data[, "GPCS_Persistence"], 2, Mean.SD.N)
apply(unmenthol.data[, "GPCS_Persistence"], 2, Mean.SD.N)
apply(filter.data[, "GPCS_Persistence"], 2, ValidN)
apply(filter.data[, "GPCS_Persistence"], 2, Ttest)

```

```{r piq}
## PIQ
# Gender
FreqPercent(menthol.data$piq_1)
FreqPercent(unmenthol.data$piq_1)
ChiSqFisher(filter.data$piq_1)
ValidN(filter.data$piq_1)
CramersV(filter.data$piq_1)

# age
Mean.SD.N(menthol.data$piq_2)
Mean.SD.N(unmenthol.data$piq_2)
Ttest(filter.data$piq_2)
ValidN(filter.data$piq_2)
CohensD(filter.data$piq_2)

# grandmother and grandfather: hispanic or not
apply(menthol.data[, c("piq_16a", "piq_16b", "piq_16c", "piq_16d")], 2, FreqPercent)
apply(unmenthol.data[, c("piq_16a", "piq_16b", "piq_16c", "piq_16d")], 2, FreqPercent)
ChiSqFisher(filter.data$piq_16a)
CramersV(filter.data$piq_16a)

ChiSqFisher(filter.data$piq_16b)
CramersV(filter.data$piq_16b)

ChiSqFisher(filter.data$piq_16c)
CramersV(filter.data$piq_16c)

ChiSqFisher(filter.data$piq_16d)
CramersV(filter.data$piq_16d)

apply(filter.data[, c("piq_16a", "piq_16b", "piq_16c", "piq_16d")], 2, ValidN)

# Grandmothers and grandfathers: races
sum(!is.na(filter.data[is.na(filter.data$redcap_id), startsWith(colnames(filter.data), "piq_17")][, 1:28]))
sum(!is.na(filter.data[!is.na(filter.data$redcap_id), startsWith(colnames(filter.data), "piq_8")][, 2:29]))

filter.data.race <- mutate(filter.data, 
  piq_17_m_gm_ai = ifelse(is.na(redcap_id), piq_8aa_T, piq_17a___1), 
  piq_17_m_gm_asian = ifelse(is.na(redcap_id), piq_8ab_T, piq_17a___2), 
  piq_17_m_gm_aa = ifelse(is.na(redcap_id), piq_8ac_T, piq_17a___3), 
  piq_17_m_gm_me = ifelse(is.na(redcap_id), piq_8ad_T, piq_17a___4), 
  piq_17_m_gm_pi = ifelse(is.na(redcap_id), piq_8ae_T, piq_17a___5), 
  piq_17_m_gm_white = ifelse(is.na(redcap_id), piq_8af_T, piq_17a___6),
  piq_17_m_gm_dontknow = ifelse(is.na(redcap_id), piq_8ag_T, piq_17a___7), 
  piq_17_m_gf_ai = ifelse(is.na(redcap_id), piq_8ba_T, piq_17b___1), 
  piq_17_m_gf_asian = ifelse(is.na(redcap_id), piq_8bb_T, piq_17b___2), 
  piq_17_m_gf_aa = ifelse(is.na(redcap_id), piq_8bc_T, piq_17b___3), 
  piq_17_m_gf_me = ifelse(is.na(redcap_id), piq_8bd_T, piq_17b___4), 
  piq_17_m_gf_pi = ifelse(is.na(redcap_id), piq_8be_T, piq_17b___5), 
  piq_17_m_gf_white = ifelse(is.na(redcap_id), piq_8bf_T, piq_17b___6), 
  piq_17_m_gf_dontknow = ifelse(is.na(redcap_id), piq_8bg_T, piq_17b___7), 
  piq_17_f_gm_ai = ifelse(is.na(redcap_id), piq_8ca_T, piq_17c___1),
  piq_17_f_gm_asian = ifelse(is.na(redcap_id), piq_8cb_T, piq_17c___2),
  piq_17_f_gm_aa = ifelse(is.na(redcap_id), piq_8cc_T, piq_17c___3),
  piq_17_f_gm_me = ifelse(is.na(redcap_id), piq_8cd_T, piq_17c___4),
  piq_17_f_gm_pi = ifelse(is.na(redcap_id), piq_8ce_T, piq_17c___5),
  piq_17_f_gm_white = ifelse(is.na(redcap_id), piq_8cf_T, piq_17c___6),
  piq_17_f_gm_dontknow = ifelse(is.na(redcap_id), piq_8cg_T, piq_17c___7),
  piq_17_f_gf_ai = ifelse(is.na(redcap_id), piq_8da_T, piq_17d___1),
  piq_17_f_gf_asian = ifelse(is.na(redcap_id), piq_8db_T, piq_17d___2),
  piq_17_f_gf_aa = ifelse(is.na(redcap_id), piq_8dc_T, piq_17d___3),
  piq_17_f_gf_me = ifelse(is.na(redcap_id), piq_8dd_T, piq_17d___4),
  piq_17_f_gf_pi = ifelse(is.na(redcap_id), piq_8de_T, piq_17d___5),
  piq_17_f_gf_white = ifelse(is.na(redcap_id), piq_8df_T, piq_17d___6),
  piq_17_f_gf_dontknow = ifelse(is.na(redcap_id), piq_8dg_T, piq_17d___7)
)

table(filter.data.race$piq_8aa_T, useNA = "always")
table(filter.data.race$piq_17a___1, useNA = "always")
table(filter.data.race$piq_17_m_gm_ai, useNA = "always")

filter.data.race$piq_17_m_gm_sum <- apply(filter.data.race[, startsWith(colnames(filter.data.race), "piq_17_m_gm")], 1, sum, na.rm = T)

filter.data.race$piq_17_m_gf_sum <- apply(filter.data.race[, startsWith(colnames(filter.data.race), "piq_17_m_gf")], 1, sum, na.rm = T)

filter.data.race$piq_17_f_gm_sum <- apply(filter.data.race[, startsWith(colnames(filter.data.race), "piq_17_f_gm")], 1, sum, na.rm = T)

filter.data.race$piq_17_f_gf_sum <- apply(filter.data.race[, startsWith(colnames(filter.data.race), "piq_17_f_gf")], 1, sum, na.rm = T)

filter.data.race$piq_17_all_sum <- apply(filter.data.race[, c("piq_17_m_gm_sum", "piq_17_m_gf_sum", "piq_17_f_gm_sum", "piq_17_f_gf_sum")], 1, sum)  

table(filter.data.race$piq_17_all_sum, useNA = "always")  # no one has missing value for all options

summary(rowSums(is.na(filter.data.race[, startsWith(colnames(filter.data.race), c("piq_17_f", "piq_17_m"))])))


filter.data.race <- mutate(filter.data.race, 
       piq_17_m_gm_aa_only = ifelse(piq_17_m_gm_aa %in% 1 & piq_17_m_gm_sum %in% 1, 1, 0),
       piq_17_m_gf_aa_only = ifelse(piq_17_m_gf_aa %in% 1 & piq_17_m_gf_sum %in% 1, 1, 0),
       piq_17_f_gm_aa_only = ifelse(piq_17_f_gm_aa %in% 1 & piq_17_f_gm_sum %in% 1, 1, 0),
       piq_17_f_gf_aa_only = ifelse(piq_17_f_gf_aa %in% 1 & piq_17_f_gf_sum %in% 1, 1, 0)
       )

filter.data.race$piq_17_all_aa_only <- apply(filter.data.race[, c("piq_17_m_gm_aa_only", "piq_17_m_gf_aa_only", "piq_17_f_gm_aa_only", "piq_17_f_gf_aa_only")], 1, sum, na.rm = T)

table(filter.data.race[filter.data.race$shq_8 == 1, "piq_17_all_aa_only"])
table(filter.data.race[filter.data.race$shq_8 == 2, "piq_17_all_aa_only"])
prop.table(table(filter.data.race[filter.data.race$shq_8 == 1, "piq_17_all_aa_only"])
)
prop.table(table(filter.data.race[filter.data.race$shq_8 == 2, "piq_17_all_aa_only"])
)

chisq.test(rbind(table(filter.data.race[filter.data.race$shq_8 == 1, "piq_17_all_aa_only"]), table(filter.data.race[filter.data.race$shq_8 == 2, "piq_17_all_aa_only"])), correct = F)
cramerV(rbind(table(filter.data.race[filter.data.race$shq_8 == 1, "piq_17_all_aa_only"]), table(filter.data.race[filter.data.race$shq_8 == 2, "piq_17_all_aa_only"])))

# education
filter.data.edu <- mutate(filter.data, education = ifelse(piq_7 %in% 1 | piq_7 %in% 2, 0, 1))
filter.data.edu <- mutate(filter.data.edu, education = ifelse(is.na(piq_7), NA, education))

table(filter.data.edu$education, useNA = "ifany")
table(filter.data.edu$piq_7, useNA = "ifany")

FreqPercent(filter.data.edu[filter.data.edu$shq_8 == 1, ]$education)
FreqPercent(filter.data.edu[filter.data.edu$shq_8 == 2, ]$education)
ValidN(filter.data.edu$education)

edu.chisq <- chisq.test(rbind(table(filter.data.edu[filter.data.edu$shq_8 == 1, ]$education), table(filter.data.edu[filter.data.edu$shq_8 == 2, ]$education)), correct = F)
edu.fisher <- fisher.test(rbind(table(filter.data.edu[filter.data.edu$shq_8 == 1, ]$education), table(filter.data.edu[filter.data.edu$shq_8 == 2, ]$education)))
edu.chisq
cramerV(rbind(table(filter.data.edu[filter.data.edu$shq_8 == 1, ]$education), table(filter.data.edu[filter.data.edu$shq_8 == 2, ]$education)))
edu.fisher

# Marital Status
FreqPercent(menthol.data$piq_8)
FreqPercent(unmenthol.data$piq_8)
ValidN(filter.data$piq_8)

# ChiSqFisher(filter.data$piq_8)

chisq.test(rbind(table(filter.data[filter.data$shq_8 == 1, ]$piq_8), table(filter.data[filter.data$shq_8 == 2, ]$piq_8)), correct = F)
cramerV(rbind(table(filter.data[filter.data$shq_8 == 1, ]$piq_8), table(filter.data[filter.data$shq_8 == 2, ]$piq_8)))

# Employment
filter.data.employ <- mutate(filter.data, employ = ifelse(piq_9 %in% 4, 0, ifelse(piq_9 %in% 3, 1, ifelse(piq_9 %in% 1 | piq_9 %in% 2 | piq_9 %in% 5, 2, NA))))

table(filter.data$piq_9, useNA = "ifany")
table(filter.data.employ$employ, useNA = "ifany")

FreqPercent(filter.data.employ[filter.data.employ$shq_8 == 1, ]$employ)
FreqPercent(filter.data.employ[filter.data.employ$shq_8 == 2, ]$employ)
ValidN(filter.data.employ$employ)

employ.chisq <- chisq.test(rbind(table(filter.data.employ[filter.data.employ$shq_8 == 1, ]$employ), table(filter.data.employ[filter.data.employ$shq_8 == 2, ]$employ)), correct = F)
employ.fisher <- fisher.test(rbind(table(filter.data.employ[filter.data.employ$shq_8 == 1, ]$employ), table(filter.data.employ[filter.data.employ$shq_8 == 2, ]$employ)))
cramerV(rbind(table(filter.data.employ[filter.data.employ$shq_8 == 1, ]$employ), table(filter.data.employ[filter.data.employ$shq_8 == 2, ]$employ)))
employ.chisq
employ.fisher

# Financial Situation
FreqPercent(menthol.data$piq_12)
FreqPercent(unmenthol.data$piq_12)
ValidN(filter.data$piq_12)
ChiSqFisher(filter.data$piq_12)
CramersV(filter.data$piq_12)

# Income
filter.data.income <- mutate(filter.data, income = ifelse(piq_13 == 1, 0, 1))
table(filter.data$piq_13, useNA = "ifany")
table(filter.data.income$income, useNA = "ifany")
 
FreqPercent(filter.data.income[filter.data.income$shq_8 == 1, ]$income)
FreqPercent(filter.data.income[filter.data.income$shq_8 == 2, ]$income)
ValidN(filter.data.income$income)

income.chisq <- chisq.test(rbind(table(filter.data.income[filter.data.income$shq_8 == 1, ]$income), table(filter.data.income[filter.data.income$shq_8 == 2, ]$income)), correct = F)
income.fisher <- fisher.test(rbind(table(filter.data.income[filter.data.income$shq_8 == 1, ]$income), table(filter.data.income[filter.data.income$shq_8 == 2, ]$income)))
cramerV(rbind(table(filter.data.income[filter.data.income$shq_8 == 1, ]$income), table(filter.data.income[filter.data.income$shq_8 == 2, ]$income)))
income.chisq
income.fisher

# Number of People Live in the Household
Mean.SD.N(menthol.data$piq_14)
Mean.SD.N(unmenthol.data$piq_14)
ValidN(filter.data$piq_14)
Ttest(filter.data$piq_14)
CohensD(filter.data$piq_14)

# Personal Recreational Expenditure
Mean.SD.N(menthol.data$piq_15)
Mean.SD.N(unmenthol.data$piq_15)
ValidN(filter.data$piq_15)
Ttest(filter.data$piq_15)
CohensD(filter.data$piq_15)
```

```{r check uppsp}
# rescore UPPSP
# reverse code
uppsp_varname <- colnames(data)[startsWith(colnames(data), "uppsp")]
uppsp_reverse <- uppsp_varname[c(2, 7, 12, 17, 22, 29, 34, 39, 44, 50, 58, 9, 47, 3, 8, 13, 18, 23, 26, 31, 36, 41, 46, 51, 56, 5, 10, 15, 20, 25, 30, 35, 40, 45, 49, 52, 54, 57, 59)]

uppsp.data <- data[, c("cleaned_SID", "shq_8", "piq_5", "PIQ_6c_T", "piq_6___3", uppsp_varname)]

for (i in 1: length(uppsp_reverse)) {
  newvar <- paste(uppsp_reverse[i], "R", sep = "_")
  uppsp.data[, newvar] = 5 - uppsp.data[, uppsp_reverse[i]]
}

uppsp.data[, sort(names(select(uppsp.data, starts_with(uppsp_reverse), ends_with("R"))))]

# Negative Urgency
negurg <- c("uppsp_2_R", "uppsp_7_R", "uppsp_12_R", "uppsp_17_R", "uppsp_22_R", "uppsp_29_R", "uppsp_34_R", "uppsp_39_R", "uppsp_44_R", "uppsp_50_R", "uppsp_53", "uppsp_58_R")

negurg.cutoff <- trunc(length(negurg) * 0.7)

uppsp.data$negurg.validN <- apply(!is.na(uppsp.data[, negurg]), 1, sum)

uppsp.data <- mutate(uppsp.data, uppsp_negurg = ifelse(negurg.validN > negurg.cutoff, rowMeans(uppsp.data[, negurg], na.rm = T), NA))

uppsp.data[, c(negurg, "uppsp_negurg")]

# positive urgency
posurg <- c("uppsp_5_R", "uppsp_10_R", "uppsp_15_R", "uppsp_20_R", "uppsp_25_R", "uppsp_30_R", "uppsp_35_R", "uppsp_40_R", "uppsp_45_R", "uppsp_49_R", "uppsp_52_R", "uppsp_54_R", "uppsp_57_R", "uppsp_59_R")

posurg.cutoff <- trunc(length(posurg) * 0.7)

uppsp.data$posurg.validN <- apply(!is.na(uppsp.data[, posurg]), 1, sum)

uppsp.data <- mutate(uppsp.data, uppsp_posurg = ifelse(posurg.validN > posurg.cutoff, rowMeans(uppsp.data[, posurg], na.rm = T), NA))

uppsp.data[, c(posurg, "uppsp_posurg")]

# (lack of) Premeditation
premed <- c("uppsp_1", "uppsp_6", "uppsp_11", "uppsp_16", "uppsp_21", "uppsp_28", "uppsp_33", "uppsp_38", "uppsp_43", "uppsp_48", "uppsp_55")

premed.cutoff <- trunc(length(premed) * 0.7)

uppsp.data$premed.validN <- apply(!is.na(uppsp.data[, premed]), 1, sum)

uppsp.data <- mutate(uppsp.data, uppsp_premed = ifelse(premed.validN > premed.cutoff, rowMeans(uppsp.data[, premed], na.rm = T), NA))

uppsp.data[, c(premed, "uppsp_premed")]

# (lack of) Perseverance
persev <- c("uppsp_4", "uppsp_9_R", "uppsp_14", "uppsp_19", "uppsp_24", "uppsp_27", "uppsp_32", "uppsp_37", "uppsp_42", "uppsp_47_R")

persev.cutoff <- trunc(length(persev) * 0.7)

uppsp.data$persev.validN <- apply(!is.na(uppsp.data[, persev]), 1, sum)

uppsp.data <- mutate(uppsp.data, uppsp_persev = ifelse(persev.validN > persev.cutoff, rowMeans(uppsp.data[, persev], na.rm = T), NA))

uppsp.data[, c(persev, "uppsp_persev")]

# Sensation Seeking 
sens <- c("uppsp_3_R", "uppsp_8_R", "uppsp_13_R", "uppsp_18_R", "uppsp_23_R", "uppsp_26_R", "uppsp_31_R", "uppsp_36_R", "uppsp_41_R", "uppsp_46_R", "uppsp_51_R", "uppsp_56_R")

sens.cutoff <- trunc(length(sens) * 0.7)

uppsp.data$sens.validN <- apply(!is.na(uppsp.data[, sens]), 1, sum)

uppsp.data <- mutate(uppsp.data, uppsp_sens = ifelse(sens.validN > sens.cutoff, rowMeans(uppsp.data[, sens], na.rm = T), NA))

uppsp.data[, c(sens, "uppsp_sens")]

uppsp.data <- filter(uppsp.data, piq_5 == 0 & PIQ_6c_T == 1 | piq_5 == 0 & piq_6___3 == 1)

Mean.SD.N(uppsp.data[uppsp.data$shq_8 == 1, ]$uppsp_negurg)
Mean.SD.N(uppsp.data[uppsp.data$shq_8 == 2, ]$uppsp_negurg)

Mean.SD.N(uppsp.data[uppsp.data$shq_8 == 1, ]$uppsp_posurg)
Mean.SD.N(uppsp.data[uppsp.data$shq_8 == 2, ]$uppsp_posurg)

Mean.SD.N(uppsp.data[uppsp.data$shq_8 == 1, ]$uppsp_premed)
Mean.SD.N(uppsp.data[uppsp.data$shq_8 == 2, ]$uppsp_premed)

Mean.SD.N(uppsp.data[uppsp.data$shq_8 == 1, ]$uppsp_persev)
Mean.SD.N(uppsp.data[uppsp.data$shq_8 == 2, ]$uppsp_persev)

Mean.SD.N(uppsp.data[uppsp.data$shq_8 == 1, ]$uppsp_sens)
Mean.SD.N(uppsp.data[uppsp.data$shq_8 == 2, ]$uppsp_sens)

```

