---
title: "test"
author: "Yi"
date: "4/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(haven)
```

```{r}
data <- read_sav("/Users/zhan039/Desktop/USC_HEAL/PRISM/10132020_RecreateData/04062021_add_numeric_time/PRISM_scores_demo_rat_new_time.sav")
```

```{r}
data %>% group_by(sid, menthol_status, patch_condition) %>% summarise(n = n())

sum(is.na(data$s1_piq_1))
sum(is.na(data$s1_piq_2))
sum(is.na(data$s1_piq_5))
data %>% select(., starts_with("s1_piq_6___")) %>% lapply(., function(x) sum(is.na(.)))

sum(is.na(data$s1_co))
sum(is.na(data$s1_shq_2))
sum(is.na(data$s1_shq_3))
sum(is.na(data$FTND_SUM))

table(data$menthol_status, useNA = "always")

data %>% select(., contains("co"))
```


```{r}
table(data$s1_piq_5, useNA = "always")
data %>% select(., starts_with("s1_piq_6___")) %>% apply(., 2, table, useNA = "always")

data <- data %>% mutate(., count_race = rowSums(select(., starts_with("s1_piq_6___"))))
data %>% select(., starts_with("s1_piq_6___"), count_race)

table(data$count_race, useNA = "always")
data %>% filter(., count_race <= 1) %>% select(., starts_with("s1_piq_6___")) %>% lapply(., table, useNA = "always")

data %>% filter(., s1_piq_6___1 %in% 1) %>% select(., s1_piq_5, s1_piq_6___1)
data %>% filter_at(vars(starts_with("s1_piq_6___")), all_vars(. %in% 0)) %>% select(., sid, s1_piq_5, starts_with("s1_piq_6___"))


36+1548+324+108

data %>% filter(., is.na(s1_piq_5)) %>% select(., sid, axt, s1_piq_5, starts_with("s1_piq_6___"))

data %>% filter(., sid %in% "18-00613-036") %>% select(., sid, axt, s1_piq_5, starts_with("s1_piq_6___"))

data %>% filter(., s1_shq_2 > 1990) %>% select(., sid, axt, s1_shq_2, s1_dob, s1_piq_2)

table(data$s1_shq_2, useNA = "always")

3*9*4

table(data$sid, useNA = "always")
length(unique(data$sid))

2376-2268
```

