---
title: "enrollment table"
author: "Yi"
date: "9/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
Prolific <- read.csv('/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/04292020/Prolific.csv', na.strings = "")
MTself <- read.csv("/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/04292020/MTself.csv", na.strings = "")
TPMT <- read.csv("/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/04292020/TPMT.csv", na.strings = "")
MTconc <- read.csv("/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/04292020/MTconc.csv", na.strings = "")
PP <- read.csv("/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/04292020/PP.csv", na.strings = "")

data1 <- read.csv("/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/06162020/Prolific3_minus.csv", na.strings = "", stringsAsFactors = F)

data2 <- read.csv("/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/06162020/Prolific3_second.csv", na.strings = "", stringsAsFactors = F)

prolific2 <- read.csv('/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/04292020/Prolific2.csv', na.strings = "", stringsAsFactors = F)
```

```{r}
# eth gender race
colnames(Prolific)[colnames(Prolific) == "prolificid"] <- "Participant_id"
colnames(MTconc)[colnames(MTconc) == "mturkidcon"] <- "Participant_id"
colnames(PP)[colnames(PP) == "aid" ] <- "Participant_id"
colnames(MTself)[colnames(MTself) == "mturkid" ] <- "Participant_id"
colnames(TPMT)[colnames(TPMT) == "tpmturkid"] <- "Participant_id"

colnames(data1)[colnames(data1) == "prolificid"] <- "Participant_id"
colnames(data2)[colnames(data2) == "prolificid"] <- "Participant_id"
colnames(prolific2)[colnames(prolific2) == "prolificid"] <- "Participant_id"

Prolific_a <- select(Prolific, redcapid, Participant_id, eth, gender, starts_with("race___"))
MTself_a <- select(MTself, redcapid, Participant_id, eth, gender, starts_with("race___"))
TPMT_a <- select(TPMT, redcapid, Participant_id, eth, gender, starts_with("race___"))
MTconc_a <- select(MTconc, redcapid, Participant_id, eth, gender, starts_with("race___"))
PP_a <- select(PP, redcapid, Participant_id, eth, gender, starts_with("race___"))

Prolific_a %>% group_by(Participant_id) %>% summarise(n = n()) %>% arrange(desc(n))

MTself_a %>% group_by(Participant_id) %>% summarise(n = n()) %>% arrange(desc(n))
MTself_a[MTself_a$Participant_id == "A1E77HZO63E334", ]
MTself_a <- MTself_a[!MTself_a$redcapid %in% c(2047, 2049), ]

TPMT_a %>% group_by(Participant_id) %>% summarise(n = n()) %>% arrange(desc(n))
TPMT_a[TPMT_a$Participant_id %in% c("A3GW6PLPCEO892", "A33YQ7GA9Q4SDB", "A3HRAENO5FF6BC"), ]
TPMT_a <- TPMT_a[!TPMT_a$redcapid %in% c(3090, 3099, 3100, 3101, 3123), ]

MTconc_a %>% group_by(Participant_id) %>% summarise(n = n()) %>% arrange(desc(n))
MTconc_a[MTconc_a$Participant_id %in% c("A1BHINLXH3E2GJ", "A1BWO4ZG5OB68S", "A1K0S514CEY1UG", "A1K5ILJMG439M5", "A30YR5TPOKQYXJ", "A3180VXVP8MOIH", "A3ZUQODR46SC4", "APZQ9ADUXTS7N"), ] %>% arrange(Participant_id)
```

```{r}
colnames(Prolific)[colnames(Prolific) == "prolificid"] <- "Participant_id"
colnames(MTconc)[colnames(MTconc) == "mturkidcon"] <- "Participant_id"
colnames(PP)[colnames(PP) == "aid" ] <- "Participant_id"
colnames(MTself)[colnames(MTself) == "mturkid" ] <- "Participant_id"
colnames(TPMT)[colnames(TPMT) == "tpmturkid"] <- "Participant_id"

colnames(data1)[colnames(data1) == "prolificpid"] <- "Participant_id"
colnames(data2)[colnames(data2) == "prolificpid"] <- "Participant_id"
colnames(prolific2)[colnames(prolific2) == "prolificpid"] <- "Participant_id"

Prolific_a <- select(Prolific, redcapid, Participant_id, eth, gender, starts_with("race___"))
MTself_a <- select(MTself, redcapid, Participant_id, eth, gender, starts_with("race___"))
TPMT_a <- select(TPMT, redcapid, Participant_id, eth, gender, starts_with("race___"))
MTconc_a <- select(MTconc, redcapid, Participant_id, eth, gender, starts_with("race___"))
PP_a <- select(PP, redcapid, Participant_id, eth, gender, starts_with("race___"))

data1_a <- select(data1, redcapid, Participant_id, eth, gender, starts_with("race___"))
data2_a <- select(data2, redcapid, Participant_id, eth, gender, starts_with("race___"))
prolific2_a <- select(prolific2, redcapid, Participant_id, eth, gender, starts_with("race___"))

data <- rbind(Prolific_a, MTself_a, TPMT_a, MTconc_a, PP_a, data1_a, data2_a, prolific2_a)
```

```{r}
data$sum.race <- rowSums(data[, startsWith(colnames(data), "race")], na.rm = T)

data <- mutate(data, race_new = ifelse(sum.race > 1 | race___6 %in% 1, 6, 
                                       ifelse(race___1 %in% 1, 1, 
                                              ifelse(race___2 %in% 1, 2, 
                                                     ifelse(race___3 %in% 1, 4,
                                                            ifelse(race___4 %in% 1, 3,
                                                                   ifelse(race___5 %in% 1, 5,
                                                                                 ifelse(race___7 %in% 1, 7, NA))))))))

table(data$sum.race, useNA = "always")
apply(data[, startsWith(colnames(data), "race")], 2, table, useNA = "always")

data <- mutate(data, gender_3c = ifelse(gender %in% 1, 1, 
                                        ifelse(gender %in% 2, 2, 
                                               ifelse(!is.na(gender), 3, NA))))
table(data$gender_3c, useNA = "always")
table(data$gender, useNA = "always")
```

```{r}
table(data$eth, useNA = "always")

no.his <- data[data$eth %in% 0, ]
his <- data[data$eth %in% 1, ]
unknow.his <- data[is.na(data$eth), ]

table(his$race_new, his$gender_3c, useNA = "always")
table(no.his$race_new, no.his$gender_3c, useNA = "always")
table(unknow.his$race_new, unknow.his$gender_3c, useNA = "always")

table(data$race_new, useNA = "always")
table(his$gender_3c, useNA = "always")
table(no.his$gender_3c, useNA = "always")
table(unknow.his$gender_3c, useNA = "always")
table(data$eth, useNA = "always")

```

```{r}
data %>% group_by(Participant_id) %>% summarise(n = n()) %>% arrange(desc(n))
```

