---
title: "merge_prolific2&3"
author: "Yi"
date: "6/16/2020"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r load packages, include=FALSE}
library(tidyverse)
library(gdata)
library(descr)
library(expss)
library(kableExtra)
```


```{r read datasets}
data1 <- read.csv("/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/06162020/Prolific3_minus.csv", na.strings = "", stringsAsFactors = F)

data2 <- read.csv("/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/06162020/Prolific3_second.csv", na.strings = "", stringsAsFactors = F)

prolific2 <- read.csv('/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/04292020/Prolific2.csv', na.strings = "", stringsAsFactors = F)

idlist <- read.xls("/Users/zhan039/Desktop/USC_HEAL/EVOC (CONJOINT)/Pilot 3 Eligible.xlsx")
```

```{r check and clean prolific 3, include=FALSE}
length(unique(data1$prolificpid))
length(unique(data2$prolificpid))

# clean data1
data1$num.na <- rowSums(is.na(data1))
data1 %>% group_by(prolificpid) %>% summarise(., n = n()) %>% filter(., n > 1)

data1[data1$prolificpid == "5a2add709408dc00016f57d3", c("redcapid", "prolificpid", "num.na")]  # remove redcapid = 1084
data1[data1$prolificpid == "5cc210247502a000125f9886", c("redcapid", "prolificpid", "num.na")]  # remove redcapid = 1134
data1[data1$prolificpid == "5ce649e53e496100197ae3db", c("redcapid", "prolificpid", "num.na")]  # remove redcapid = 1053
data1[data1$prolificpid == "5d219d16072b440018aebe98", c("redcapid", "prolificpid", "num.na")]  # remove redcapid = 1023

data1[data1$prolificpid == "test", ]  # remove redcapid = 1000

data1 <- data1[!data1$redcapid %in% c(1084, 1134, 1053, 1023, 1000), ] 

# clean data2
data2$num.na <- rowSums(is.na(data2))
data2 %>% group_by(prolificpid) %>% summarise(., n = n()) %>% filter(., n > 1)

data2[data2$prolificpid == "5da2d3e256940100160c3bec", c("redcapid", "prolificpid", "num.na")]  # remove redcapid = 2039  # filter(data2[, c("redcapid", "prolificpid", "num.na")], prolificpid == "5da2d3e256940100160c3bec") cannot detect NA

data2[is.na(data2$prolificpid), c("redcapid", "prolificpid", "num.na")] # remove redcapid = 2000

data2 <- data2[!data2$redcapid %in% c(2000, 2039), ]
```

```{r merge prolific 3, include=FALSE}
# merge prolific 3
length(unique(data1$prolificpid))
length(unique(data2$prolificpid))

intersec_name_3 <- intersect(colnames(data1), colnames(data2))
colnames(data1)[!colnames(data1) %in% intersec_name_3]
colnames(data2)[!colnames(data2) %in% intersec_name_3]
length(intersect(data1$prolificpid, data2$prolificpid))

307 + 2 + 16

prolific3 <- merge(data1, data2, all.x = T, all.y = T)

length(intersect(colnames(data1), colnames(prolific3)))
length(intersect(colnames(data2), colnames(prolific3)))
# full_join(data1, data2, by = intersect(colnames(data1), colnames(data2)))

sum(prolific3$prolificpid %in% idlist$Pilot3Eligible)  # remove polificpid = "test"

prolific3 <- prolific3[prolific3$prolificpid %in% idlist$Pilot3Eligible, ]
```

```{r check and clean prolific 2, include=FALSE}
length(unique(prolific2$prolificpid))

prolific2$num.na <- rowSums(is.na(prolific2))

prolific2 %>% group_by(prolificpid) %>% summarise(n = n()) %>% filter( n > 1)

prolific2[prolific2$prolificpid == "5c315f577626080001a88cb2", c("redcapid", "prolificpid", "num.na")]  # remove redcapid = 8109

prolific2[prolific2$prolificpid == "5c748b9188fdc20017c60436", c("redcapid", "prolificpid", "num.na")]  # remove redcapid = 8272

prolific2[prolific2$prolificpid == "5d010ccecfeb82000117c42a", c("redcapid", "prolificpid", "num.na")]  # remove redcapid = 8241 8244	

prolific2[prolific2$prolificpid == "5d30b94628b06900195d305e", c("redcapid", "prolificpid", "num.na")]  # remove redcapid = 8088		

prolific2[prolific2$prolificpid == "5d6f02d4e0207600167e2317", c("redcapid", "prolificpid", "num.na")]  # remove redcapid = 8158	8168

prolific2[prolific2$prolificpid == "5dac7c198ff76d00166a70c4", c("redcapid", "prolificpid", "num.na")]  # remove redcapid = 8040

prolific2[prolific2$prolificpid == "5df1683537241c07cf8f3984", c("redcapid", "prolificpid", "num.na")]  # remove redcapid = 8160

prolific2 <- prolific2[!prolific2$redcapid %in% c(8109, 8272, 8241, 8244, 8088, 8158,	8168, 8040, 8160), ]


intersec_name_2_3 <- intersect(colnames(prolific2), colnames(prolific3))

colnames(prolific2)[!colnames(prolific2) %in% intersec_name_2_3]
colnames(prolific3)[!colnames(prolific3) %in% intersec_name_2_3]

length(intersect(prolific2$prolificpid, prolific3$prolificpid))

sum(is.na(prolific2$prolificpid))

184 + 49 + 141
```

```{r merge prolifc 2 & 3, include=FALSE}
prolific2$pilot <- 2
prolific3$pilot <- 3
intersec_name_2_3 <- intersect(colnames(prolific2), colnames(prolific3))

185 + 49 + 141

prolific_2_3 <- merge(prolific2, prolific3, all.x = T, all.y = T, by = c("prolificpid", "pilot", intersec_name_2_3[!intersec_name_2_3 %in% c("prolificpid", "pilot")]))
```

```{r Frequency of number of days of use}
# variable list
varlist_num_days <- colnames(prolific_2_3)[endsWith(colnames(prolific_2_3), "30_days")]

# analytical dataset
validdata <- prolific_2_3[prolific_2_3$prolificpid %in% prolific3$prolificpid, ]  # get enrolled in both pilot 2 and 3

LabelNumofDayUse <- function(varname){
  
  val_lab(validdata[, varname]) <- num_lab("
                           1 0 days
                           2 1 or 2 days
                           3 3 to 5 days
                           4 6 to 9 days
                           5 10 to 19 days
                           6 20 to 29 days
                           7 All 30 days
                           ")
}

Days_Pilot <- function(varname){
  
  temp.table <- table(validdata[, varname], validdata$pilot, useNA = "ifany")
  colname <- dimnames(temp.table)[[1]]
  colname[is.na(colname)] <- "Missing Value"
  dimnames(temp.table)[[1]] <- colname
  
 kableExtra::kable(temp.table, format = "html", caption = varname)
  
}

lapply(varlist_num_days, LabelNumofDayUse)
lapply(varlist_num_days, Days_Pilot)
```

```{r every_day_current}
Days_Pilot("vape_every_day_current")
prop.table(table(validdata$vape_every_day_current, validdata$pilot))
```

```{r ecig_bout}
Days_Pilot("ecig_bout_times_last30")
prop.table(table(validdata$ecig_bout_times_last30, validdata$pilot, useNA = "always"))

Days_Pilot("ecig_bout_puffs_last30")
prop.table(table(validdata$ecig_bout_puffs_last30, validdata$pilot, useNA = "always"))

```

```{r dependence based on vape addicion or vape quit effects}
select(validdata, starts_with(c("vape_addiction", "vape_quit_effects")))
table(rowSums(is.na(select(validdata, starts_with(c("vape_addiction", "vape_quit_effects")))
)))  # 8 participants have missing value for all items

validdata$dependence.na <- rowSums(is.na(select(validdata, starts_with(c("vape_addiction", "vape_quit_effects")))))
validdata$dependence.vape <- rowSums(select(validdata, starts_with(c("vape_addiction", "vape_quit_effects"))))  # no need to remove na because number of na is 0 or 10
validdata <- mutate(validdata, dependence.vape.d = ifelse(dependence.vape > 0, 1, 0))

table(validdata$dependence.na, useNA = "always")
table(validdata$dependence.vape, useNA = "always")
table(validdata$dependence.vape.d, useNA = "always")

select(validdata, prolificpid,starts_with(c("vape_addiction", "vape_quit_effects")), dependence.na, dependence.vape, dependence.vape.d)

Days_Pilot("dependence.vape.d")
prop.table(table(validdata$dependence.vape.d, validdata$pilot))
```

```{r myecig_type}
Days_Pilot("myecig_type")
prop.table(table(validdata$myecig_type, validdata$pilot))
```

```{r covid_63 to covid_89h}
colnames(validdata)[startsWith(colnames(validdata), "covid")][-c(1:10, 79, 80)]

covidvars <- colnames(validdata)[startsWith(colnames(validdata), "covid")][-c(1:10, 79, 80)]

FreqTable <- function(varvec){
  
  temp.table <- table(varvec, useNA = "always")

  report <- list()
  report[[1]] <- names(varvec)
  report[[2]] <- temp.table

  return(report)
  
}

apply(validdata[, covidvars], 2, FreqTable)
```

