---
title: "merge_wide_demographic"
author: "Yi"
date: "7/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(haven)
library(tidyverse)
library(xlsx2dfs)
```

```{r}
alldata <- read_sav("/Users/zhan039/Desktop/USC_HEAL/UAS/07232020/covid_panal_07232020.sav")

varlist <- read.xlsx("/Users/zhan039/Desktop/USC_HEAL/UAS/07232020/variable list.xlsx", colNames = F)

varlist <- as.vector(varlist$X1)
varlist <- varlist[!varlist %in% c("uasid", "wave")]
```

```{r}
time_invariant <- c("statereside", "gender", "maritalstatusD1", "maritalstatusD2", "educationD1", "educationD2", "educationD3", "hhincomeM", "hhincomeQ", "poverty100", "poverty150", "age", "age3Ga", "age4Ga", "age4Gb", "RACEHSP", "RACEHSP4G", "RACEHSP5G", "immigrant_status", "maritalstatus", "livewithpartner", "education", "hispanic", "white", "black", "nativeamer", "asian", "pacific", "race", "hhincome", "hhmembernumber", "Householdnumber")
```


All time-invariant variables would be merged to one variable, whose value is consistent with the baseline's value. For the missing value in baseline, it would be filled with the value with the maximum count in the following up waves. 
```{r}
AlldataWide <- select(alldata, c("uasid", "wave", all_of(varlist))) %>% group_by(uasid) %>% gather(., key = variable, value = value, all_of(varlist)) %>% unite(., newvariable, variable, wave, sep = "_") %>% spread(., newvariable, value)

# write_sav(AlldataWide, "/Users/zhan039/Desktop/USC_HEAL/UAS/07232020/covid_wide_all.sav")

# Age
AlldataWide %>% select(., uasid, starts_with("age_")) %>% summary()

age <- AlldataWide %>% select(., uasid, starts_with("age_"))  # explore age 
table(rowSums(is.na(age)), useNA = "ifany")  # In the final dataset, 9 people will have missing value in age

age.all <- alldata %>% group_by(uasid, age) %>% summarise(n = n()) %>% arrange(., uasid, n) %>% mutate(., rank = row_number(desc(n)))  # get the count of age for each participant 

age.all <- age.all[age.all$rank == 1, ]  # values of age for imputing
age.all <- age.all %>% rename("age_max_count" = age)
summary(age.all$age_max_count)

test <- left_join(AlldataWide, age.all[, 1:2], by = "uasid")
select(AlldataWide, uasid, starts_with("age_"))

test <- mutate(test, age = ifelse(is.na(age_1), age_max_count, age_1)) # keep the baseline value of age 
colSums(is.na(test[, startsWith(colnames(test), "age")]))
summary(test$age)

select(test, age, starts_with("age_"))
```

```{r}

newdata <- AlldataWide

impute <- function(varname){
  
  var.all <- alldata %>% group_by(uasid, get(varname)) %>% summarise(n = n()) %>% arrange(., uasid, n) %>% mutate(., rank = row_number(desc(n)))  # get the count of age for each participant 
  
  var.all <- var.all[var.all$rank == 1, ]  # values of age for imputing
  
  newname <- paste(varname, "max_count", sep = "_")
  colnames(var.all)[colnames(var.all) == "get(varname)"] <- newname
  
  newdata <- left_join(newdata, var.all[, 1:2], by = "uasid")

  basevar <- paste(varname, "_1", sep = "")
  
  newdata <- mutate(newdata, x = ifelse(is.na(get(basevar)), get(newname), get(basevar)))  # keep the baseline value of age 
  colnames(newdata)[colnames(newdata) == "x"] <- varname

  return(newdata)
}

for (i in 1:length(time_invariant)) {
  varname <- time_invariant[i]
  newdata <- impute(varname)
}

select(newdata, age, starts_with("age_"))
select(newdata, statereside, starts_with("statereside_"))
select(newdata, gender, starts_with("gender_"))

delete <- paste(time_invariant, "_", sep = "")
newdata <- select(newdata, -starts_with(delete))

```

```{r}
write.csv(newdata, "/Users/zhan039/Desktop/USC_HEAL/UAS/07232020/covid_panal_imputed.csv", na = "")
write_sav(newdata, "/Users/zhan039/Desktop/USC_HEAL/UAS/07232020/covid_panal_imputed.sav")
```

