---
title: "merge_UAS185_covid19"
author: "Yi"
date: "7/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(haven)
library(tidyverse)
```

```{r}
covid <- read_stata("/Users/zhan039/Desktop/USC_HEAL/UAS/07132020/covid_panal/covidpanel_us_stata_jul_8_2020.dta")

uas185 <- read_stata("/Users/zhan039/Desktop/USC_HEAL/UAS/07132020/UAS185/uas185.dta")
```

```{r}
length(unique(covid$uasid))
```

```{r}
covid_sample <- covid[, c("gender", "age", "maritalstatus", "livewithpartner", "education", "hisplatino", "race", "working", "sick_leave", "unemp_look", "retired", "disabled", "laborstatus", "employmenttype", "workfullpart", "hourswork", "hhincome", "anyhhmember", "hhmembernumber", "final_weight", "start_date", "coping_drinking", "cr026a2", "uasid")]

uas185_sample <- uas185[, c("gender", "age", "maritalstatus", "livewithpartner", "education", "hisplatino", "race", "working", "sick_leave", "unemp_look", "retired", "disabled", "laborstatus", "employmenttype", "workfullpart", "hourswork", "hhincome", "anyhhmember", "hhmembernumber", "start_date", "c128_","c129_", "c130_", "uasid")]

covid_sample$datafile <- 1
uas185_sample$datafile <- 0

colnames(uas185_sample)[colnames(uas185_sample) == "c129_"] <- "coping_drinking"
colnames(uas185_sample)[colnames(uas185_sample) == "c130_"] <- "cr026a2"

mergedata <- merge(covid_sample, uas185_sample, all.x = T, all.y = T)

mergedata$start_date <- format(mergedata$start_date, format = "%Y%m%d")

write_sav(mergedata, "/Users/zhan039/Desktop/USC_HEAL/UAS/07132020/UAS185_COVID19_B.sav")
```

```{r}
table(mergedata$datafile)

sum(is.na(covid_sample$coping_drinking))
sum(is.na(uas185$c129_))
sum(is.na(uas185_sample$coping_drinking))
sum(is.na(mergedata$coping_drinking))

sum(is.na(covid_sample$cr026a2))
sum(is.na(uas185$c130_))
sum(is.na(uas185_sample$cr026a2))
sum(is.na(mergedata$cr026a2))

sum(is.na(covid_sample$final_weight))
sum(is.na(mergedata$final_weight))

sum(is.na(uas185_sample$c128_))
sum(is.na(mergedata$c128_))

table(covid_sample$gender, useNA = "always")
table(uas185_sample$gender, useNA = "always")
table(mergedata$gender, useNA = "always")

class(mergedata$start_date)
table(mergedata$start_date)

table(format(mergedata$start_date, format = "%Y%m%d"))
class(format(mergedata$start_date, format = "%Y%m%d"))
```

