---
title: "tranform_long_wide_data_wave14"
author: "Yi"
date: "10/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(haven)
```

```{r}
data <- read_sav("/Users/zhan039/Desktop/USC_HEAL/UAS/10272020/JC/UAS DATA/UAS_recode_waves_YZ_JC_A.sav")
```

```{r}
time_variant <- select(data, uasid,wave,Binge_drinking,Binge_drinkingA,coping_cannabis,coping_drinking4,coping_drinking7,coping_drugs,coping_exercise,coping_meditate,cr026a2,cr026a2A,disabled,drinkingTotal,employmenttype,final_weight,Heavy_drinking,hourswork,laborstatus,lf_other,phq4_anxious,phq4_depressed,phq4_littleinterest,phq4_worry,retired,sick_leave,start_date,unemp_layoff,unemp_look,wave_7days,wave_14days,workfullpart,working)

demo <- select(data, uasid, wave, gender,maritalstatusD1,maritalstatusD2,educationD1,educationD2,educationD3,hhincomeM,hhincomeQ,poverty100,poverty150,age,age3Ga,age4Ga,age4Gb,RACEHSP,RACEHSP4G,RACEHSP5G,immigrant_status,maritalstatus,livewithpartner,education,hisplatino,hisplatino_group,white,black,nativeamer,asian,pacific,race,hhincome,hhmembernumber,Householdnumber,statereside)

all <- select(data, uasid,wave,Binge_drinking,Binge_drinkingA,coping_cannabis,coping_drinking4,coping_drinking7,coping_drugs,coping_exercise,coping_meditate,cr026a2,cr026a2A,disabled,drinkingTotal,employmenttype,final_weight,Heavy_drinking,hourswork,laborstatus,lf_other,phq4_anxious,phq4_depressed,phq4_littleinterest,phq4_worry,retired,sick_leave,start_date,unemp_layoff,unemp_look,wave_7days,wave_14days,workfullpart,working, gender,maritalstatusD1,maritalstatusD2,educationD1,educationD2,educationD3,hhincomeM,hhincomeQ,poverty100,poverty150,age,age3Ga,age4Ga,age4Gb,RACEHSP,RACEHSP4G,RACEHSP5G,immigrant_status,maritalstatus,livewithpartner,education,hisplatino,hisplatino_group,white,black,nativeamer,asian,pacific,race,hhincome,hhmembernumber,Householdnumber,statereside)
```

```{r transform time-variant only}
time_variant_wide <- time_variant %>% group_by(uasid) %>% gather(., key = variable, value = value, -c(1, 2)) %>% unite(., newvariable, variable, wave, sep = "_") %>% spread(., newvariable, value) 

order_col <- c(sapply(colnames(time_variant)[-c(1,2)], paste, c(1:14), sep = "_"))

time_variant_wide <- select(time_variant_wide, uasid, all_of(order_col))
```

```{r transform all variables}
all_wide <- all %>% group_by(uasid) %>% gather(., key = variable, value = value, -c(1, 2)) %>% unite(., newvariable, variable, wave, sep = "_") %>% spread(., newvariable, value) 

order_col_all <- c(sapply(colnames(all)[-c(1,2)], paste, c(1:14), sep = "_"))

all_wide <- select(all_wide, uasid, all_of(order_col_all))

write_sav(all_wide, "/Users/zhan039/Desktop/USC_HEAL/UAS/10272020/UAS_wide_YZ.sav")
```

