---
title: "w21_transform_long_wide_calc_waves"
author: "Yi"
date: "2/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(haven)
```

```{r}
data <- read_sav("/Users/zhan039/Desktop/USC_HEAL/UAS/02022021/JC/UAS DATA/UAS_recode_waves_create_vars_YZ_B.sav")
```

```{r create the number of waves}
data %>% group_by(uasid, wave) %>% count() %>% filter(n > 1)

n_wave <- data %>% group_by(uasid) %>% summarise(n_wave = n())

n_wave
```

```{r}
all <- select(data, uasid,wave,Binge_drinking,Binge_drinkingA,coping_cannabis,coping_drinking,coping_drinking4,coping_drinking7,coping_drugs,coping_exercise,coping_meditate,cr026a2,cr026a2A,disabled,drinkingTotal,employmenttype,final_weight,Heavy_drinking,hourswork,laborstatus,lf_other,phq4_anxious,phq4_depressed,phq4_littleinterest,phq4_worry,retired,sick_leave,start_date,unemp_layoff,unemp_look,wave_7days,wave_14days,workfullpart,working, gender,maritalstatusD1,maritalstatusD2,educationD1,educationD2,educationD3,hhincomeM,hhincomeQ,poverty100,poverty150,age,age3Ga,age4Ga,age4Gb,RACEHSP,RACEHSP4G,RACEHSP5G,immigrant_status,maritalstatus,livewithpartner,education,hisplatino,hisplatino_group,white,black,nativeamer,asian,pacific,race,hhincome,hhmembernumber,Householdnumber,statereside)

all_wide <- all %>% group_by(uasid) %>% gather(., key = variable, value = value, -c(1, 2)) %>% unite(., newvariable, variable, wave, sep = "_") %>% spread(., newvariable, value) 

order_col_all <- c(sapply(colnames(all)[-c(1,2)], paste, c(1:21), sep = "_"))

all_wide <- select(all_wide, uasid, all_of(order_col_all))

head(all_wide)

newdata <- merge(all_wide, n_wave, by.x = "uasid", by.y = "uasid", all.x = T, all.y = T)
```

```{r}
write_sav(newdata, "/Users/zhan039/Desktop/USC_HEAL/UAS/02022021/YZ/update_calc_waves/UAS_recode_waves_create_vars_YZ_B_wide.sav")
```

