---
title: "Check_datasets"
author: "Yi"
date: "9/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(haven)
library(gmodels)
library(car)
```

```{r}
data_0804 <- read_sas("/Users/zhan039/Desktop/USC_HEAL/HH/HH W10 COVID DATA/hh_w1_to_w10_0804.sas7bdat")
data_0810 <- read_sas("/Users/zhan039/Desktop/USC_HEAL/HH/HH W10 COVID DATA/w10_covid_081020.sas7bdat")

data_age_race <- read_sav("/Users/zhan039/Desktop/USC_HEAL/HH/HH W10 COVID DATA/w10_covid_081020_JC_B.sav")
```

```{r}
a <- intersect(colnames(data_0804), colnames(data_0810))

colnames(data_0804)[!colnames(data_0804) %in% a]
colnames(data_0810)[!colnames(data_0810) %in% a]

data <- data_0804

age_race <- data_age_race[, c("SID", "W10_Age_Calc_new_2", "RACEa")]

data <- merge(data, age_race, by = "SID", all.x = T)
```

```{r define analytical dataset}
select(data, w10_mj_use_last30, w10_mjfood_use_last30, w10_emj_use_last30, w10_smj_use_last30, w10_dabbing_use_last30, w10_mjconc_use_last30) %>% apply(., 2, table, useNA = "always")
length(unique(data$SID))

# create row max of cannibis use in last 30 dyas
data$w10_all_mj_use_last30 = apply(data[, c("w10_mj_use_last30", "w10_mjfood_use_last30", "w10_emj_use_last30", "w10_smj_use_last30", "w10_dabbing_use_last30", "w10_mjconc_use_last30")], 1, max, na.rm = T)

select(data, w10_mj_use_last30, w10_mjfood_use_last30, w10_emj_use_last30, w10_smj_use_last30, w10_dabbing_use_last30, w10_mjconc_use_last30, w10_all_mj_use_last30) 
table(data$w10_all_mj_use_last30, useNA = "always")

# recode to days and in numeric
data$w10_all_mj_use_last30_n <- as.numeric(as.character(factor(data$w10_all_mj_use_last30, levels = c(-99, 1:7), labels = c(NA, 0, 2, 4, 8, 15, 25, 30))))

select(data, w10_mj_use_last30, w10_mjfood_use_last30, w10_emj_use_last30, w10_smj_use_last30, w10_dabbing_use_last30, w10_mjconc_use_last30, w10_all_mj_use_last30, w10_all_mj_use_last30_n) 

table(data$w10_all_mj_use_last30_n, useNA = "always")

# ever use any cannaibis products in past 30 days
data <- mutate(data, w10_ever_any_mj_last30 = ifelse(w10_all_mj_use_last30_n %in% 0, 0, ifelse(w10_all_mj_use_last30_n > 0, 1, NA)))

table(data$w10_ever_any_mj_last30, useNA = "always")

# Analytical Data
ana.data <- data[data$w10_ever_any_mj_last30 %in% 1, ]
```

```{r mj supply}
# w10
select(ana.data, starts_with("w10_mj_supply__")) %>% apply(., 1, sum)
table(ana.data$w10_mj_supply___5, useNA = "always")

ana.data <- mutate(ana.data, w10_mj_supply_n_selfgrown = w10_mj_supply___1, 
                   w10_mj_supply_n_share = w10_mj_supply___2, 
                   w10_mj_supply_n_bfperson = w10_mj_supply___3, 
                   w10_mj_supply_n_bfdisp_card = w10_mj_supply___4, 
                   w10_mj_supply_n_bfdisp_nocard = w10_mj_supply___6)

ana.data$w10_mj_supply_n_online_deliv <- apply(ana.data[, c("w10_mj_supply___7", "w10_mj_supply___8")], 1, max, na.rm = T)

ana.data %>% select(., starts_with("w10_mj_supply__")) %>% apply(., 2, table, useNA = "always")
ana.data %>% select(., starts_with("w10_mj_supply_n_")) %>% apply(., 2, table, useNA = "always")

# w9
select(ana.data, starts_with("W9_Mj_Supply_"))

ana.data <- mutate(ana.data, w9_mj_supply_n_selfgrown = W9_Mj_Supply_1, 
                   w9_mj_supply_n_share = W9_Mj_Supply_2, 
                   w9_mj_supply_n_bfperson = W9_Mj_Supply_3, 
                   w9_mj_supply_n_bfdisp_card = W9_Mj_Supply_4, 
                   w9_mj_supply_n_bfdisp_nocard = W9_Mj_Supply_9)

ana.data$w9_mj_supply_n_online_deliv <- apply(ana.data[, c("W9_Mj_Supply_6", "W9_Mj_Supply_8")], 1, max, na.rm = T)

ana.data %>% select(., starts_with("W9_Mj_Supply_")) %>% apply(., 2, table, useNA = "always")
ana.data %>% select(., starts_with("w9_mj_supply_n_")) %>% apply(., 2, table, useNA = "always")
```

```{r covid_64j order delivery of mj in past two weeks}
table(ana.data$covid_64j, useNA = "always")

ana.data <- mutate(ana.data, covid_mj_deliv_past2weeks = ifelse(covid_64j %in% 1, 0, 
                                                                ifelse(covid_64j > 1, 1, NA)))

table(ana.data$covid_mj_deliv_past2weeks, useNA = "always")
```


```{r table 1 mj_supply by waves}
# transform the dataset
mj.supply.waves <- ana.data %>% select(., SID, starts_with("w9_mj_supply_n"), starts_with("w10_mj_supply_n"))
mj_supply_var <- colnames(mj.supply.waves)[-1]

mj.supply.waves.long <- mj.supply.waves %>% gather(., key = variable, value = value, all_of(mj_supply_var)) %>% separate(variable, c("wave", "mj_supply"), sep = "_", extra = "merge") %>% spread(mj_supply, value)

mj.supply.waves.long$wave <- factor(mj.supply.waves.long$wave, levels = c("w9", "w10"), labels = c(9, 10))
table(mj.supply.waves.long$mj_supply_n_bfdisp_nocard, mj.supply.waves.long$wave, useNA = "always")

# create the table
mj_supply_var_long <- colnames(mj.supply.waves.long)[-c(1, 2)]

apply(mj.supply.waves.long[, mj_supply_var_long], 2, CrossTable, mj.supply.waves.long$wave, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(mj.supply.waves.long$mj_supply_n_selfgrown, mj.supply.waves.long$wave, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(mj.supply.waves.long$mj_supply_n_share, mj.supply.waves.long$wave, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(mj.supply.waves.long$mj_supply_n_bfperson, mj.supply.waves.long$wave, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(mj.supply.waves.long$mj_supply_n_bfdisp_card, mj.supply.waves.long$wave, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(mj.supply.waves.long$mj_supply_n_bfdisp_nocard, mj.supply.waves.long$wave, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(mj.supply.waves.long$mj_supply_n_online_deliv, mj.supply.waves.long$wave, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

```

```{r table 2}
# age 
ana.data %>% group_by(covid_mj_deliv_past2weeks) %>% summarise(mean = mean(W10_Age_Calc_new_2, na.rm = T), sd = sd(W10_Age_Calc_new_2, na.rm = T)) 

leveneTest(ana.data$W10_Age_Calc_new_2, group = as.factor(ana.data$covid_mj_deliv_past2weeks), center = mean)
t.test(ana.data[ana.data$covid_mj_deliv_past2weeks %in% 0, "W10_Age_Calc_new_2"], ana.data[ana.data$covid_mj_deliv_past2weeks %in% 1, "W10_Age_Calc_new_2"], var.equal = T)


# gender
table(ana.data$Gender, useNA = "always")

CrossTable(ana.data$Gender, ana.data$covid_mj_deliv_past2weeks, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

# race
table(ana.data$RACEa, useNA = "always")
attr(ana.data$RACEa, "label")
CrossTable(ana.data$RACEa, ana.data$covid_mj_deliv_past2weeks, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

# pre-Covid cannabis use (times per week) & during-Covid cannabis use (times per week)

select(ana.data, W9_Mj_Use_Last30, W9_MjFood_Use_Last30, W9_eMj_Use_Last30, W9_sMj_Use_Last30, W9_Dabbing_Use_Last30) %>% apply(., 2, table, useNA = "always")

# create row max of cannibis use in last 30 dyas
ana.data$w9_all_mj_use_last30 <- apply(ana.data[, c("W9_Mj_Use_Last30", "W9_MjFood_Use_Last30", "W9_eMj_Use_Last30", "W9_sMj_Use_Last30", "W9_Dabbing_Use_Last30")], 1, max, na.rm = T)

select(ana.data, W9_Mj_Use_Last30, W9_MjFood_Use_Last30, W9_eMj_Use_Last30, W9_sMj_Use_Last30, W9_Dabbing_Use_Last30, w9_all_mj_use_last30) 
table(ana.data$w9_all_mj_use_last30, useNA = "always")

# recode to days and in numeric
ana.data$w9_all_mj_use_last30_n <- as.numeric(as.character(factor(ana.data$w9_all_mj_use_last30, levels = c(-99, 1:7), labels = c(NA, 0, 2, 4, 8, 15, 25, 30))))

select(ana.data, W9_Mj_Use_Last30, W9_MjFood_Use_Last30, W9_eMj_Use_Last30, W9_sMj_Use_Last30, W9_Dabbing_Use_Last30, w9_all_mj_use_last30, w9_all_mj_use_last30_n) 

table(ana.data$w9_all_mj_use_last30_n, useNA = "always")
table(ana.data$w10_all_mj_use_last30_n, useNA = "always")

# ever use any cannaibis products in past 30 days
ana.data <- mutate(ana.data, w9_n_mj_use_perweek = w9_all_mj_use_last30_n/4, w10_n_mj_use_perweek = w10_all_mj_use_last30_n/4)

table(ana.data$w9_n_mj_use_perweek, useNA = "always")
table(ana.data$w10_n_mj_use_perweek, useNA = "always")

ana.data %>% group_by(covid_mj_deliv_past2weeks) %>% summarise(w9_mean = mean(w9_n_mj_use_perweek, na.rm = T), w9_sd = sd(w9_n_mj_use_perweek, na.rm = T))

ana.data %>% group_by(covid_mj_deliv_past2weeks) %>% summarise(w10_mean = mean(w10_n_mj_use_perweek, na.rm = T), w10_sd = sd(w10_n_mj_use_perweek, na.rm = T))

leveneTest(ana.data$w9_n_mj_use_perweek, group = as.factor(ana.data$covid_mj_deliv_past2weeks), center = mean)
t.test(ana.data[ana.data$covid_mj_deliv_past2weeks %in% 0, "w9_n_mj_use_perweek"], ana.data[ana.data$covid_mj_deliv_past2weeks %in% 1, "w9_n_mj_use_perweek"], var.equal = F)

leveneTest(ana.data$w10_n_mj_use_perweek, group = as.factor(ana.data$covid_mj_deliv_past2weeks), center = mean)
t.test(ana.data[ana.data$covid_mj_deliv_past2weeks %in% 0, "w10_n_mj_use_perweek"], ana.data[ana.data$covid_mj_deliv_past2weeks %in% 1, "w10_n_mj_use_perweek"], var.equal = T)

# increase in cannabis use during covid
ana.data <- mutate(ana.data, increase_n_mj_use_perweek = w10_n_mj_use_perweek - w9_n_mj_use_perweek)
select(ana.data, w9_n_mj_use_perweek, w10_n_mj_use_perweek, increase_n_mj_use_perweek)

ana.data %>% group_by(covid_mj_deliv_past2weeks) %>% summarise(increase_mean = mean(increase_n_mj_use_perweek, na.rm = T), increase_sd = sd(increase_n_mj_use_perweek, na.rm = T))

leveneTest(ana.data$increase_n_mj_use_perweek, group = as.factor(ana.data$covid_mj_deliv_past2weeks), center = mean)
t.test(ana.data[ana.data$covid_mj_deliv_past2weeks %in% 0, "increase_n_mj_use_perweek"], ana.data[ana.data$covid_mj_deliv_past2weeks %in% 1, "increase_n_mj_use_perweek"], var.equal = F)

```

```{r another table 1}
# Max Cannabis Use Frequency in Past 30 days
mean(ana.data$w9_all_mj_use_last30_n, na.rm = T)
sd(ana.data$w9_all_mj_use_last30_n, na.rm = T)

mean(ana.data$w10_all_mj_use_last30_n, na.rm = T)
sd(ana.data$w10_all_mj_use_last30_n, na.rm = T)

ana.data <- mutate(ana.data, increase_n_mj_use_last30 = w10_all_mj_use_last30_n - w9_all_mj_use_last30_n)
select(ana.data, w9_all_mj_use_last30_n, w10_all_mj_use_last30_n, increase_n_mj_use_last30)

mean(ana.data$increase_n_mj_use_last30, na.rm = T)
sd(ana.data$increase_n_mj_use_last30, na.rm = T)

ana.data %>% group_by(covid_mj_deliv_past2weeks) %>% summarise(w9_mean = mean(w9_all_mj_use_last30_n, na.rm = T), w9_sd = sd(w9_all_mj_use_last30_n, na.rm = T), w10_mean = mean(w10_all_mj_use_last30_n, na.rm = T), w10_sd = sd(w10_all_mj_use_last30_n, na.rm = T), inc_mean = mean(increase_n_mj_use_last30, na.rm = T), inc_sd = sd(increase_n_mj_use_last30, na.rm = T))

leveneTest(ana.data$w9_all_mj_use_last30_n, group = as.factor(ana.data$covid_mj_deliv_past2weeks), center = mean)
t.test(ana.data[ana.data$covid_mj_deliv_past2weeks %in% 0, "w9_all_mj_use_last30_n"], ana.data[ana.data$covid_mj_deliv_past2weeks %in% 1, "w9_all_mj_use_last30_n"], var.equal = F)

leveneTest(ana.data$w10_all_mj_use_last30_n, group = as.factor(ana.data$covid_mj_deliv_past2weeks), center = mean)
t.test(ana.data[ana.data$covid_mj_deliv_past2weeks %in% 0, "w10_all_mj_use_last30_n"], ana.data[ana.data$covid_mj_deliv_past2weeks %in% 1, "w10_all_mj_use_last30_n"], var.equal = T)

leveneTest(ana.data$increase_n_mj_use_last30, group = as.factor(ana.data$covid_mj_deliv_past2weeks), center = mean)
t.test(ana.data[ana.data$covid_mj_deliv_past2weeks %in% 0, "increase_n_mj_use_last30"], ana.data[ana.data$covid_mj_deliv_past2weeks %in% 1, "increase_n_mj_use_last30"], var.equal = F)

# where usually get cannabis
table(ana.data$w10_mj_supply___7, useNA = "always")
prop.table(table(ana.data$w10_mj_supply___7, useNA = "always"))

table(ana.data$w10_mj_supply___8, useNA = "always")
prop.table(table(ana.data$w10_mj_supply___8, useNA = "always"))

table(ana.data$w10_mj_supply___7, ana.data$w10_mj_supply___8, useNA = "always")

table(ana.data$W9_Mj_Supply_6, useNA = "always")
prop.table(table(ana.data$W9_Mj_Supply_6, useNA = "always"))

table(ana.data$W9_Mj_Supply_8, useNA = "always")
prop.table(table(ana.data$W9_Mj_Supply_8, useNA = "always"))

CrossTable(ana.data$w9_mj_supply_n_selfgrown, ana.data$covid_mj_deliv_past2weeks, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(ana.data$w9_mj_supply_n_share, ana.data$covid_mj_deliv_past2weeks, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(ana.data$w9_mj_supply_n_bfperson, ana.data$covid_mj_deliv_past2weeks, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(ana.data$w9_mj_supply_n_bfdisp_card, ana.data$covid_mj_deliv_past2weeks, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(ana.data$w9_mj_supply_n_bfdisp_nocard, ana.data$covid_mj_deliv_past2weeks, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(ana.data$w9_mj_supply_n_online_deliv, ana.data$covid_mj_deliv_past2weeks, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(ana.data$W9_Mj_Supply_6, ana.data$covid_mj_deliv_past2weeks, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(ana.data$W9_Mj_Supply_8, ana.data$covid_mj_deliv_past2weeks, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(ana.data$w10_mj_supply_n_selfgrown, ana.data$covid_mj_deliv_past2weeks, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(ana.data$w10_mj_supply_n_share, ana.data$covid_mj_deliv_past2weeks, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(ana.data$w10_mj_supply_n_bfperson, ana.data$covid_mj_deliv_past2weeks, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(ana.data$w10_mj_supply_n_bfdisp_card, ana.data$covid_mj_deliv_past2weeks, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(ana.data$w10_mj_supply_n_bfdisp_nocard, ana.data$covid_mj_deliv_past2weeks, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(ana.data$w10_mj_supply_n_online_deliv, ana.data$covid_mj_deliv_past2weeks, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(ana.data$w10_mj_supply___7, ana.data$covid_mj_deliv_past2weeks, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

CrossTable(ana.data$w10_mj_supply___8, ana.data$covid_mj_deliv_past2weeks, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")

# Use cannabis to cope isolation & distancing due to pandemic
table(ana.data$covid_69___11, useNA = "always")
prop.table(table(ana.data$covid_69___11, useNA = "always"))

CrossTable(ana.data$covid_69___11, ana.data$covid_mj_deliv_past2weeks, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = T, fisher = T, format = "SPSS")
```

```{r descriptive statistics for abstracts and results}
mean(ana.data$W10_Age_Calc_new_2)
sd(ana.data$W10_Age_Calc_new_2)

table(ana.data$Gender, useNA = "always")
prop.table(table(ana.data$Gender, useNA = "always"))

table(ana.data$RACEa, useNA = "always")
attr(ana.data$RACEa, "label")
prop.table(table(ana.data$RACEa, useNA = "always"))

table(ana.data$w9_all_mj_use_last30_n, useNA = "always")
pre.ana.data <- ana.data[!ana.data$w9_all_mj_use_last30_n %in% c(0, NA), ]
table(pre.ana.data$w9_all_mj_use_last30_n, useNA = "always")
487/761

pre.w9.age <- data_age_race[, c("SID", "W9_Age_Calc_new_2")]
pre.ana.data <- merge(pre.ana.data, pre.w9.age, by = "SID", all.x = T)

mean(pre.w9.age$W9_Age_Calc_new_2, na.rm = T)

prop.table(table(pre.ana.data$Gender, useNA = "always"))

attr(pre.ana.data$RACEa, "label")
prop.table(table(pre.ana.data$RACEa, useNA = "always"))

```

