---
title: "table1&2_03042020"
author: "Yi"
date: "3/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(haven)
library(tidyverse)
library(psy)
```

```{r}
Mean.sd.n <- function(var){
    a <- cbind(mean(var, na.rm = T), 
               sd(var, na.rm = T),
               sum(!is.na(var)))
    rownames(a) <- attr(var, which = "label")
    colnames(a) <- c("Mean", "SD", "Valid N")
    return(a)
}

Freq.Perc.n <- function(var){
  b <- rbind(table(var),
             table(var)/sum(!is.na(var)))
  rownames(b) <- c("Freq", "Perc")
  return(list(variable = attr(var, which = "label"),b, ValidN = sum(!is.na(var))))
}

```


```{r}
data <- read_sav("/Users/zhan039/Desktop/USC HEAL/GROW JAMES/GROW Manuscript _ Data_03032020/REDCap_wTeleform_Merged (scored + sorted)_06212018 (No 2nd survey) with DIFF_03082019.sav")
```

```{r}
# sample selection: 528
analysis.data <- filter(data, sample528 == 1)
```

```{r}
######### table 1 - Sample Characteristics ##############
# age
range(analysis.data$piq_2, na.rm = T)
Mean.sd.n(analysis.data$piq_2)

# gender
range(analysis.data$piq_1, na.rm = T)
Freq.Perc.n(analysis.data$piq_1)

# age started smoking
range(analysis.data$shq_2, na.rm = T)
Mean.sd.n(analysis.data$shq_2)

# number of cigarettes per day
range(analysis.data$shq_3, na.rm = T)
Mean.sd.n(analysis.data$shq_3)

# menthol cigarette use
range(analysis.data$shq_8, na.rm = T)
Freq.Perc.n(analysis.data$shq_8)

# FTND
range(analysis.data$FTND_SUM, na.rm = T)
Mean.sd.n(analysis.data$FTND_SUM)
```

```{r}
# TABLE 2 - Tobacco Withdraw Symptoms
# WSWS craving
Mean.sd.n(analysis.data$D_WSWS_Craving_Mean)
Mean.sd.n(analysis.data$ND_WSWS_Craving_Mean)
cronbach(analysis.data[, c("d_wsws_7", "d_wsws_9", "d_wsws_17", "d_wsws_21")])
cronbach(analysis.data[, c("nd_wsws_7", "nd_wsws_9", "nd_wsws_17", "nd_wsws_21")])
t.test(analysis.data$D_WSWS_Craving_Mean, analysis.data$ND_WSWS_Craving_Mean, paired = T)
20.559/sqrt(517)
0.922953/1.020766

# QSU Total
Mean.sd.n(analysis.data$D_QSU_Mean)
Mean.sd.n(analysis.data$ND_QSU_Mean)
cronbach(analysis.data[, c("d_qsu_1", "d_qsu_2", "d_qsu_3", "d_qsu_4", "d_qsu_5", "d_qsu_6", "d_qsu_7", "d_qsu_8", "d_qsu_9", "d_qsu_10")])
cronbach(analysis.data[, c("nd_qsu_1", "nd_qsu_2", "nd_qsu_3", "nd_qsu_4", "nd_qsu_5", "nd_qsu_6", "nd_qsu_7", "nd_qsu_8", "nd_qsu_9", "nd_qsu_10")])
t.test(analysis.data$D_QSU_Mean, analysis.data$ND_QSU_Mean, paired = T)
30.621629/sqrt(520)
1.844049/1.373238

# QSU Factor 1
Mean.sd.n(analysis.data$D_QSU_Factor1_Mean)
Mean.sd.n(analysis.data$ND_QSU_Factor1_Mean)
cronbach(analysis.data[, c("d_qsu_1", "d_qsu_3", "d_qsu_6", "d_qsu_7", "d_qsu_10")])
cronbach(analysis.data[, c("nd_qsu_1", "nd_qsu_3", "nd_qsu_6", "nd_qsu_7", "nd_qsu_10")])
t.test(analysis.data$D_QSU_Factor1_Mean, analysis.data$ND_QSU_Factor1_Mean, paired = T)
31.726126/sqrt(517)
2.316925/1.660505

#QSU Fctor 2
Mean.sd.n(analysis.data$D_QSU_Factor2_Mean)
Mean.sd.n(analysis.data$ND_QSU_Factor2_Mean)
cronbach(analysis.data[, c("d_qsu_2", "d_qsu_4", "d_qsu_5", "d_qsu_8", "d_qsu_9")])
cronbach(analysis.data[, c("nd_qsu_2", "nd_qsu_4", "nd_qsu_5", "nd_qsu_8", "nd_qsu_9")])
t.test(analysis.data$D_QSU_Factor2_Mean, analysis.data$ND_QSU_Factor2_Mean, paired = T)
22.536197/sqrt(520)
1.364519/1.380704

# POMS - Negative Affect
Mean.sd.n(analysis.data$D_POMS_NM_Mean)
Mean.sd.n(analysis.data$ND_POMS_NM_Mean)
cronbach(analysis.data[, c("D_POMS_Anger_Mean", "D_POMS_Anxiety_Mean", "D_POMS_Confusion_Mean", "D_POMS_Depression_Mean", "D_POMS_Fatigue_Mean")])
cronbach(analysis.data[, c("ND_POMS_Anger_Mean", "ND_POMS_Anxiety_Mean", "ND_POMS_Confusion_Mean", "ND_POMS_Depression_Mean", "ND_POMS_Fatigue_Mean")])
t.test(analysis.data$D_POMS_NM_Mean, analysis.data$ND_POMS_NM_Mean, paired = T)
6.804124/sqrt(516)
0.155663/0.519683

# WSWS Anger
Mean.sd.n(analysis.data$D_WSWS_Anger_Mean)
Mean.sd.n(analysis.data$ND_WSWS_Anger_Mean)
cronbach(analysis.data[, c("d_wsws_11", "d_wsws_13", "d_wsws_15")])
cronbach(analysis.data[, c("nd_wsws_11", "nd_wsws_13", "nd_wsws_15")])
t.test(analysis.data$D_WSWS_Anger_Mean, analysis.data$ND_WSWS_Anger_Mean, paired = T)
14.122264/sqrt(517)
0.709865/1.142922


# POMS Anger
Mean.sd.n(analysis.data$D_POMS_Anger_Mean)
Mean.sd.n(analysis.data$ND_POMS_Anger_Mean)
cronbach(analysis.data[, c("d_poms_4", "d_poms_14", "d_poms_19", "d_poms_24", "d_poms_30", "d_poms_33", "d_poms_39", "d_poms_42", "d_poms_47", "d_poms_53", "d_poms_57", "d_poms_71")])
cronbach(analysis.data[, c("nd_poms_4", "nd_poms_14", "nd_poms_19", "nd_poms_24", "nd_poms_30", "nd_poms_33", "nd_poms_39", "nd_poms_42", "nd_poms_47", "nd_poms_53", "nd_poms_57", "nd_poms_71")])
t.test(analysis.data$D_POMS_Anger_Mean, analysis.data$ND_POMS_Anger_Mean, paired = T)
7.168788/sqrt(516)
0.188989/0.598846

# WSWS Anxiety
Mean.sd.n(analysis.data$D_WSWS_Anxiety_Mean)
Mean.sd.n(analysis.data$ND_WSWS_Anxiety_Mean)
analysis.data <- mutate(analysis.data, d_wsws_8_reverse = 4 - d_wsws_8, nd_wsws_8_reverse = 4 - nd_wsws_8)
cronbach(analysis.data[, c("d_wsws_2", "d_wsws_4", "d_wsws_6", "d_wsws_8_reverse")])
cronbach(analysis.data[, c("nd_wsws_2", "nd_wsws_4", "nd_wsws_6", "nd_wsws_8_reverse")])
t.test(analysis.data$D_WSWS_Anxiety_Mean, analysis.data$ND_WSWS_Anxiety_Mean, paired = T)
11.882547/sqrt(516)
0.484496/0.926202

# POMS Anxiety
Mean.sd.n(analysis.data$D_POMS_Anxiety_Mean)
Mean.sd.n(analysis.data$ND_POMS_Anxiety_Mean)
analysis.data <- mutate(analysis.data, d_poms_66_reverse = 4 - d_poms_66, nd_poms_66_reverse = 4 - nd_poms_66)
cronbach(analysis.data[, c("d_poms_2", "d_poms_11", "d_poms_18", "d_poms_66_reverse", "d_poms_69", "d_poms_43", "d_poms_48", "d_poms_60", "d_poms_27")])
cronbach(analysis.data[, c("nd_poms_2", "nd_poms_11", "nd_poms_18", "nd_poms_66_reverse", "nd_poms_69", "nd_poms_43", "nd_poms_48", "nd_poms_60", "nd_poms_27")])
t.test(analysis.data$D_POMS_Anxiety_Mean, analysis.data$ND_POMS_Anxiety_Mean, paired = T)
9.593654/sqrt(516)
0.294874/0.698195

# WSWS Sadness
Mean.sd.n(analysis.data$D_WSWS_Sadness_Mean)
Mean.sd.n(analysis.data$ND_WSWS_Sadness_Mean)
analysis.data <- mutate(analysis.data, d_wsws_5_reverse = 4 - d_wsws_5, nd_wsws_5_reverse = 4 - nd_wsws_5, d_wsws_20_reverse = 4 - d_wsws_20, nd_wsws_20_reverse = 4 - nd_wsws_20)
cronbach(analysis.data[, c("d_wsws_5_reverse", "d_wsws_10", "d_wsws_16", "d_wsws_20_reverse")])
cronbach(analysis.data[, c("nd_wsws_5_reverse", "nd_wsws_10", "nd_wsws_16", "nd_wsws_20_reverse")])
t.test(analysis.data$D_WSWS_Sadness_Mean, analysis.data$ND_WSWS_Sadness_Mean, paired = T)
10.055768/sqrt(517)
0.339942/0.768661

# POMS Depression
Mean.sd.n(analysis.data$D_POMS_Depression_Mean)
Mean.sd.n(analysis.data$ND_POMS_Depression_Mean)
cronbach(analysis.data[, c("d_poms_6", "d_poms_10", "d_poms_16", "d_poms_22", "d_poms_25", "d_poms_29", "d_poms_35", "d_poms_36", "d_poms_37", "d_poms_45", "d_poms_46", "d_poms_49", "d_poms_59", "d_poms_62", "d_poms_64")])
cronbach(analysis.data[, c("nd_poms_6", "nd_poms_10", "nd_poms_16", "nd_poms_22", "nd_poms_25", "nd_poms_29", "nd_poms_35", "nd_poms_36", "nd_poms_37", "nd_poms_45", "nd_poms_46", "nd_poms_49", "nd_poms_59", "nd_poms_62", "nd_poms_64")])
t.test(analysis.data$D_POMS_Depression_Mean, analysis.data$ND_POMS_Depression_Mean, paired = T)
3.708016/sqrt(516)
0.087052/0.533289


# POMS Positive Affect
Mean.sd.n(analysis.data$D_POMS_PM_Mean)
Mean.sd.n(analysis.data$ND_POMS_PM_Mean)
cronbach(analysis.data[, c("D_POMS_Elation_Mean", "D_POMS_Vigor_Mean", "D_POMS_Friendliness_Mean")])
cronbach(analysis.data[, c("ND_POMS_Elation_Mean", "ND_POMS_Vigor_Mean", "ND_POMS_Friendliness_Mean")])
t.test(analysis.data$D_POMS_PM_Mean, analysis.data$ND_POMS_PM_Mean, paired = T)
-13.319955/sqrt(515)
-0.443648/0.755857

# POMS Elation
Mean.sd.n(analysis.data$D_POMS_Elation_Mean)
Mean.sd.n(analysis.data$ND_POMS_Elation_Mean)
cronbach(analysis.data[, c("d_poms_3", "d_poms_13", "d_poms_26", "d_poms_40", "d_poms_51", "d_poms_72")])
cronbach(analysis.data[, c("nd_poms_3", "nd_poms_13", "nd_poms_26", "nd_poms_40", "nd_poms_51", "nd_poms_72")])
t.test(analysis.data$D_POMS_Elation_Mean, analysis.data$ND_POMS_Elation_Mean, paired = T)
-11.987361/sqrt(516)
-0.443669/0.840738

# POMS Friendliness
Mean.sd.n(analysis.data$D_POMS_Friendliness_Mean)
Mean.sd.n(analysis.data$ND_POMS_Friendliness_Mean)
cronbach(analysis.data[, c("d_poms_1", "d_poms_15", "d_poms_28", "d_poms_34", "d_poms_44", "d_poms_55", "d_poms_63", "d_poms_70")])
cronbach(analysis.data[, c("nd_poms_1", "nd_poms_15", "nd_poms_28", "nd_poms_34", "nd_poms_44", "nd_poms_55", "nd_poms_63", "nd_poms_70")])
t.test(analysis.data$D_POMS_Friendliness_Mean, analysis.data$ND_POMS_Friendliness_Mean, paired = T)
-13.878571/sqrt(515)
-0.512725/0.838385

# POMS Vigor
Mean.sd.n(analysis.data$D_POMS_Vigor_Mean)
Mean.sd.n(analysis.data$ND_POMS_Vigor_Mean)
cronbach(analysis.data[, c("d_poms_8", "d_poms_17", "d_poms_23", "d_poms_31", "d_poms_41", "d_poms_54", "d_poms_56", "d_poms_61")])
cronbach(analysis.data[, c("nd_poms_8", "nd_poms_17", "nd_poms_23", "nd_poms_31", "nd_poms_41", "nd_poms_54", "nd_poms_56", "nd_poms_61")])
t.test(analysis.data$D_POMS_Vigor_Mean, analysis.data$ND_POMS_Vigor_Mean, paired = T)
-10.468316/sqrt(516)
-0.376534/0.817057

# SHAPS Anhedonia
Mean.sd.n(analysis.data$D_SHAPS_Mean)
Mean.sd.n(analysis.data$ND_SHAPS_Mean)
cronbach(analysis.data[, c("d_shaps_1", "d_shaps_2", "d_shaps_3", "d_shaps_4", "d_shaps_5", "d_shaps_6", "d_shaps_7", "d_shaps_8", "d_shaps_9", "d_shaps_10", "d_shaps_11", "d_shaps_12", "d_shaps_13", "d_shaps_14")])
cronbach(analysis.data[, c("nd_shaps_1", "nd_shaps_2", "nd_shaps_3", "nd_shaps_4", "nd_shaps_5", "nd_shaps_6", "nd_shaps_7", "nd_shaps_8", "nd_shaps_9", "nd_shaps_10", "nd_shaps_11", "nd_shaps_12", "nd_shaps_13", "nd_shaps_14")])
t.test(analysis.data$D_SHAPS_Mean, analysis.data$ND_SHAPS_Mean, paired = T)
-7.332597/sqrt(521)
-0.167407/0.521115

# POMS Confusion
Mean.sd.n(analysis.data$D_POMS_Confusion_Mean)
Mean.sd.n(analysis.data$ND_POMS_Confusion_Mean)
analysis.data <- mutate(analysis.data, d_poms_38_reverse = 4 - d_poms_38, nd_poms_38_reverse = 4 - nd_poms_38)
cronbach(analysis.data[, c("d_poms_7", "d_poms_9", "d_poms_21", "d_poms_67", "d_poms_38_reverse", "d_poms_52", "d_poms_58")])
cronbach(analysis.data[, c("nd_poms_7", "nd_poms_9", "nd_poms_21", "nd_poms_67", "nd_poms_38_reverse", "nd_poms_52", "nd_poms_58")])
t.test(analysis.data$D_POMS_Confusion_Mean, analysis.data$ND_POMS_Confusion_Mean, paired = T)
5.999629/sqrt(516)
0.149631/0.566528

# WSWS Concentration
Mean.sd.n(analysis.data$D_WSWS_Concentration_Mean)
Mean.sd.n(analysis.data$ND_WSWS_Concentration_Mean)
analysis.data <- mutate(analysis.data, d_wsws_3_reverse = 4 - d_wsws_3, nd_wsws_3_reverse = 4 - nd_wsws_3)
cronbach(analysis.data[, c("d_wsws_3_reverse", "d_wsws_19", "d_wsws_22")])
cronbach(analysis.data[, c("nd_wsws_3_reverse", "nd_wsws_19", "nd_wsws_22")])
t.test(analysis.data$D_WSWS_Concentration_Mean, analysis.data$ND_WSWS_Concentration_Mean, paired = T)
12.748854/sqrt(517)
0.499678/0.891177

# CIS Impulsivity
Mean.sd.n(analysis.data$D_CIS_Mean)
Mean.sd.n(analysis.data$ND_CIS_Mean)
analysis.data <- mutate(analysis.data, d_cis_4_reverse = 4 - d_cis_4, d_cis_5_reverse = 4 - d_cis_5, d_cis_6_reverse = 4 - d_cis_6, d_cis_8_reverse = 4 - d_cis_8, d_cis_10_reverse = 4 - d_cis_10, d_cis_12_reverse = 4 - d_cis_12, d_cis_15_reverse = 4 - d_cis_15, d_cis_18_reverse = 4 - d_cis_18, d_cis_19_reverse = 4 - d_cis_19, nd_cis_4_reverse = 4 - nd_cis_4, nd_cis_5_reverse = 4 - nd_cis_5, nd_cis_6_reverse = 4 - nd_cis_6, nd_cis_8_reverse = 4 - nd_cis_8, nd_cis_10_reverse = 4 - nd_cis_10, nd_cis_12_reverse = 4 - nd_cis_12, nd_cis_15_reverse = 4 - nd_cis_15, nd_cis_18_reverse = 4 - nd_cis_18, nd_cis_19_reverse = 4 - nd_cis_19)
cronbach(analysis.data[, c("d_cis_1", "d_cis_2", "d_cis_3", "d_cis_4_reverse", "d_cis_5_reverse", "d_cis_6_reverse", "d_cis_7", "d_cis_8_reverse", "d_cis_9", 
  "d_cis_10_reverse", "d_cis_11", "d_cis_12_reverse", "d_cis_13", "d_cis_14", "d_cis_15_reverse", "d_cis_16", "d_cis_17", "d_cis_18_reverse", "d_cis_19_reverse")])
cronbach(analysis.data[, c("nd_cis_1", "nd_cis_2", "nd_cis_3", "nd_cis_4_reverse", "nd_cis_5_reverse", "nd_cis_6_reverse", "nd_cis_7", "nd_cis_8_reverse", "nd_cis_9", 
  "nd_cis_10_reverse", "nd_cis_11", "nd_cis_12_reverse", "nd_cis_13", "nd_cis_14", "nd_cis_15_reverse", "nd_cis_16", "nd_cis_17", "nd_cis_18_reverse", "nd_cis_19_reverse")])
t.test(analysis.data$D_CIS_Mean, analysis.data$ND_CIS_Mean, paired = T)
11.124267/sqrt(519)
0.205127/0.420083

# WSWS Hunger
Mean.sd.n(analysis.data$D_WSWS_Hunger_Mean)
Mean.sd.n(analysis.data$ND_WSWS_Hunger_Mean)
analysis.data <- mutate(analysis.data, d_wsws_1_reverse = 4 - d_wsws_1, nd_wsws_1_reverse = 4 - nd_wsws_1)
cronbach(analysis.data[, c("d_wsws_1_reverse", "d_wsws_12", "d_wsws_14", "d_wsws_18", "d_wsws_23")])
cronbach(analysis.data[, c("nd_wsws_1_reverse", "nd_wsws_12", "nd_wsws_14", "nd_wsws_18", "nd_wsws_23")])
t.test(analysis.data$D_WSWS_Hunger_Mean, analysis.data$ND_WSWS_Hunger_Mean, paired = T)
8.965797/sqrt(516)
0.348547/0.883073

# Time Delayed
analysis.data <- mutate(analysis.data, d_rat_delay_time_fixed = ifelse(is.na(redcap_id), D_RAT_time_delayed, d_rat_delay_time)) # merge variables from redcap and from teleform

Mean.sd.n(analysis.data$d_rat_delay_time_fixed)
Mean.sd.n(analysis.data$nd_rat_delay_time)
t.test(analysis.data$d_rat_delay_time_fixed, analysis.data$nd_rat_delay_time, paired = T)
-17.264016/sqrt(522)
-17.704981/23.430895

# Cigarettes Smoked
analysis.data <- mutate(analysis.data, d_rat_num_cigs = d_rat_num_cigs_start - d_rat_num_cigs_end, nd_rat_num_cigs = nd_rat_num_cigs_start - nd_rat_num_cigs_end, D_RAT_num_cigs_T = D_RAT_cigs_in_box - D_RAT_cigs_in_box_end, d_rat_num_cigs_fixed = ifelse(is.na(redcap_id), D_RAT_num_cigs_T, d_rat_num_cigs))

analysis.data <- mutate(analysis.data, d_rat_num_cigs_fixed = ifelse(d_rat_num_cigs_fixed >= 0, d_rat_num_cigs_fixed, NA), nd_rat_num_cigs_fixed = ifelse(nd_rat_num_cigs >= 0, nd_rat_num_cigs, NA))
Mean.sd.n(analysis.data$d_rat_num_cigs_fixed)
Mean.sd.n(analysis.data$nd_rat_num_cigs_fixed)
t.test(analysis.data$d_rat_num_cigs_fixed, analysis.data$nd_rat_num_cigs, paired = T)
5.403900/sqrt(504)
0.246032/1.022113
```


